import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { lazy, Suspense, useEffect, type ComponentType, type ReactNode } from "react";
import { Route, Switch, useLocation } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";
import { useSchoolAuth } from "./contexts/SupabaseAuthContext";
import MenweHeroHome from "./pages/MenweHeroHome";
import "./mobile-premium.css";
function lazyWithChunkRecovery<T extends ComponentType = ComponentType>(importer:()=>Promise<{default:T}>,key:string){return lazy(async()=>{try{return await importer();}catch(error){const message=error instanceof Error?error.message:String(error);const chunk=/dynamically imported module|loading chunk|chunkloaderror|failed to fetch/i.test(message);const storage=`menwe:chunk-recovery:${key}`;if(chunk&&typeof window!=="undefined"&&!sessionStorage.getItem(storage)){sessionStorage.setItem(storage,"1");window.location.reload();await new Promise<never>(()=>undefined);}if(typeof window!=="undefined")sessionStorage.removeItem(storage);throw error;}})}
const lp=(path:string,key:string)=>lazyWithChunkRecovery(()=>import(path),key);
const AcademicsPage=lp("./pages/AcademicsPage","academics"),AdmissionsPage=lp("./pages/AdmissionsPage","admissions"),GalleryPage=lp("./pages/GalleryPage","gallery"),AboutPage=lp("./pages/AboutPage","about"),SchoolLifePage=lp("./pages/SchoolLifePage","school-life"),ForFamiliesPage=lp("./pages/ForFamiliesPage","families"),HowItWorksPage=lp("./pages/HowItWorksPage","how-it-works"),CalendarPage=lp("./pages/CalendarPage","calendar"),TermsPage=lp("./pages/TermsPage","terms"),PrivacyPage=lp("./pages/PrivacyPage","privacy"),CookiesPage=lp("./pages/CookiesPage","cookies"),NotFoundPage=lp("./pages/NotFoundPage","not-found"),PortalLoginPage=lp("./pages/PortalLoginPage","portal-login"),PortalGuard=lp("./pages/PortalPages","portal-pages"),AdminDashboardHubPage=lp("./pages/AdminDashboardHubPage","admin-dashboard"),TeacherDashboardPage=lp("./pages/TeacherDashboardPage","teacher-dashboard"),ParentDashboardPage=lp("./pages/ParentDashboardPage","parent-dashboard"),AttendanceDirectory=lp("./pages/AttendanceDirectory","attendance"),AcademicManagementPage=lp("./pages/AcademicManagementPage","academic-management"),ExamManagementPage=lp("./pages/ExamManagementPage","exam-management"),FinanceDirectory=lp("./pages/FinanceDirectory","finance"),HomeworkDirectory=lp("./pages/HomeworkDirectory","homework"),NotificationCenter=lp("./pages/NotificationCenter","notifications"),ReportCardsDirectory=lp("./pages/ReportCardsDirectory","report-cards"),TimetableDirectory=lp("./pages/TimetableDirectory","timetable"),GalleryManagementPage=lp("./pages/GalleryManagementPage","gallery-management"),SchoolSetupPage=lp("./pages/SchoolSetupPage","school-setup"),FirstAdminPage=lp("./pages/FirstAdminPage","first-admin"),PortalAccessPage=lp("./pages/PortalAccessPage","portal-access"),MagicLinkPage=lp("./pages/MagicLinkPage","magic-link"),LoginPage=lp("./pages/PublicPages","login"),ContentManagementRoute=lp("./pages/ContentManagement","content-management"),AdminPeopleManagementPage=lp("./pages/AdminPeopleManagementPage","people-management"),AdminOperationsPage=lp("./pages/AdminOperationsPage","operations"),MessageCenter=lp("./pages/MessageCenter","messages"),EnrollmentDirectory=lp("./pages/EnrollmentDirectory","enrolment"),TeacherAssignmentsDirectory=lp("./pages/TeacherAssignmentsDirectory","assignments");
const MASTER_ADMIN_EMAILS=new Set(["menweprimaryandjunior@gmail.com","menweschool.official@gmail.com"]);type PortalRole="admin"|"teacher"|"parent"|"student";
function resolveRole(user:any,profile:any):PortalRole{const email=user?.email?.trim().toLowerCase()??"";if(MASTER_ADMIN_EMAILS.has(email))return"admin";const r=String(profile?.role??user?.app_metadata?.role??user?.user_metadata?.role??"").toLowerCase();if(["admin","super_admin","head_of_institution","deputy_hoi"].includes(r))return"admin";if(["teacher","class_teacher","classroom_teacher","staff"].includes(r))return"teacher";if(r==="student")return"student";return"parent";}
function Guard({roles,children}:{roles:PortalRole[];children:ReactNode}){const auth=useSchoolAuth();const[,go]=useLocation();useEffect(()=>{if(auth.loading||auth.profileLoading)return;if(!auth.user){go("/portal/login");return;}if(!auth.profile)return;const role=resolveRole(auth.user,auth.profile);if(!roles.includes(role))go(role==="admin"?"/portal/admin":role==="teacher"?"/portal/teacher":"/portal/parent");},[auth.loading,auth.profileLoading,auth.user,auth.profile,roles,go]);if(auth.loading||auth.profileLoading||!auth.user||!auth.profile)return <div className="grid min-h-screen place-items-center bg-[var(--paper)] text-sm text-[var(--ink)]/60">Restoring secure school session…</div>;return roles.includes(resolveRole(auth.user,auth.profile))?<>{children}</>:null;}
function Router(){const[location]=useLocation();useEffect(()=>{document.title=location==="/portal/admin"?"Admin Command Center | Menwe Primary & Junior School":location==="/portal/teacher"?"Teacher Workspace | Menwe Primary & Junior School":location==="/portal/parent"?"Family Workspace | Menwe Primary & Junior School":"Menwe Primary & Junior School | Igoki, Abogeta";},[location]);return <Switch>
<Route path="/" component={MenweHeroHome}/><Route path="/about" component={AboutPage}/><Route path="/academics" component={AcademicsPage}/><Route path="/admissions" component={AdmissionsPage}/><Route path="/news-events" component={lp("./pages/CorePublicPages","news-events")}/><Route path="/news" component={lp("./pages/CorePublicPages","news")}/><Route path="/events" component={lp("./pages/CorePublicPages","events")}/><Route path="/gallery" component={GalleryPage}/><Route path="/contact" component={lp("./pages/CorePublicPages","contact")}/><Route path="/school-life" component={SchoolLifePage}/><Route path="/families" component={ForFamiliesPage}/><Route path="/how-it-works" component={HowItWorksPage}/>
<Route path="/portal/login" component={PortalLoginPage}/><Route path="/portal/admin"><Guard roles={["admin"]}><AdminDashboardHubPage/></Guard></Route><Route path="/portal/teacher"><Guard roles={["admin","teacher"]}><TeacherDashboardPage/></Guard></Route><Route path="/portal/parent"><Guard roles={["parent"]}><ParentDashboardPage/></Guard></Route><Route path="/portal/dashboard"><Guard roles={["parent"]}><ParentDashboardPage/></Guard></Route>
<Route path="/portal/admin/academics"><Guard roles={["admin"]}><AcademicManagementPage/></Guard></Route><Route path="/portal/admin/attendance"><Guard roles={["admin"]}><AttendanceDirectory/></Guard></Route><Route path="/portal/admin/content"><Guard roles={["admin"]}><ContentManagementRoute/></Guard></Route><Route path="/portal/admin/directory"><Guard roles={["admin"]}><AdminPeopleManagementPage/></Guard></Route><Route path="/portal/admin/operations"><Guard roles={["admin"]}><AdminOperationsPage/></Guard></Route><Route path="/portal/admin/finance"><Guard roles={["admin"]}><FinanceDirectory/></Guard></Route>
<Route path="/portal/academics"><Guard roles={["admin","teacher"]}><AcademicManagementPage/></Guard></Route><Route path="/portal/exams"><Guard roles={["admin","teacher"]}><ExamManagementPage/></Guard></Route><Route path="/portal/attendance"><Guard roles={["admin","teacher","parent","student"]}><AttendanceDirectory/></Guard></Route><Route path="/portal/report-cards"><Guard roles={["admin","teacher","parent","student"]}><ReportCardsDirectory/></Guard></Route><Route path="/portal/finance"><Guard roles={["admin","parent"]}><FinanceDirectory/></Guard></Route><Route path="/portal/homework"><Guard roles={["admin","teacher","parent","student"]}><HomeworkDirectory/></Guard></Route><Route path="/portal/timetable"><Guard roles={["admin","teacher","parent","student"]}><TimetableDirectory/></Guard></Route><Route path="/portal/notifications"><Guard roles={["admin","teacher","parent","student"]}><NotificationCenter/></Guard></Route><Route path="/portal/messages"><Guard roles={["admin","teacher","parent","student"]}><MessageCenter role="PARENT"/></Guard></Route><Route path="/portal/gallery"><Guard roles={["admin"]}><GalleryManagementPage/></Guard></Route>
<Route path="/portal/setup/first-admin" component={FirstAdminPage}/><Route path="/portal/setup" component={SchoolSetupPage}/><Route path="/portal/password" component={LoginPage}/><Route path="/portal/email-link" component={MagicLinkPage}/><Route path="/login" component={PortalAccessPage}/><Route path="/calendar" component={CalendarPage}/><Route path="/terms" component={TermsPage}/><Route path="/privacy" component={PrivacyPage}/><Route path="/cookies" component={CookiesPage}/><Route path="/portal" component={PortalGuard}/><Route path="/portal/:rest*" component={PortalGuard}/><Route path="*" component={NotFoundPage}/>
</Switch>}
export default function App(){return <ErrorBoundary><ThemeProvider defaultTheme="light"><TooltipProvider><Toaster/><Suspense fallback={<div className="grid min-h-screen place-items-center bg-[var(--paper)] text-sm text-[var(--ink)]/55">Loading Menwe…</div>}><Router/></Suspense></TooltipProvider></ThemeProvider></ErrorBoundary>}
