import { BookOpen, FlaskConical, Laptop, Music, Trophy, Sprout } from "lucide-react";
import PublicLayout from "@/components/PublicLayout";

const pathways = [
  ["Early Years & Primary", "PP1–PP2 and Grades 1–6", "Foundational literacy, numeracy, creative expression, environmental awareness and social-emotional development.", BookOpen],
  ["Junior Secondary", "Grades 7–9", "Science laboratory learning, digital literacy, languages, mathematics and pre-technical studies within the CBC framework.", FlaskConical],
  ["Talent & Co-curricular", "Learning beyond the classroom", "Football and athletics, music and band, drama, agriculture, STEM clubs and leadership opportunities.", Trophy],
];
export default function AcademicsPage(){return <PublicLayout><section className="mx-auto max-w-7xl px-5 pb-14 pt-16 lg:px-8 lg:pt-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--accent)]">Academic excellence</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-semibold tracking-tight sm:text-6xl">Learning pathways designed for every stage of growth.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[var(--ink)]/65">At Menwe Primary & Junior School, the Competency-Based Curriculum is brought to life through purposeful teaching, practical discovery and strong character formation.</p></section><section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-5 lg:grid-cols-3">{pathways.map(([title,level,copy,Icon])=>{const I=Icon;return <article key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--ink)] text-[var(--accent)]"><I size={21}/></div><p className="mt-7 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--accent)]">{String(level)}</p><h2 className="mt-2 font-serif text-2xl font-semibold">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-[var(--ink)]/62">{String(copy)}</p></article>})}</div></div></section><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--accent)]">Our methodology</p><h2 className="mt-3 font-serif text-3xl font-semibold">CBC with purpose, practice and personal attention.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-[var(--ink)]/65">Our 23 certified educators use learner-centred approaches that connect classroom concepts with practical skills, collaboration, creativity and responsible decision-making.</p></div><div className="grid grid-cols-2 gap-3">{[[Laptop,"Digital literacy"],[FlaskConical,"Science discovery"],[Music,"Music & band"],[Sprout,"Agriculture & STEM"]].map(([Icon,label])=>{const I=Icon as typeof Laptop;return <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5"><I size={19} className="text-[var(--accent)]"/><p className="mt-8 text-sm font-semibold">{String(label)}</p></div>})}</div></div><div className="mt-10 rounded-2xl bg-[var(--ink)] p-7 text-white"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--accent)]">School leadership</p><p className="mt-3 text-sm leading-6 text-white/70">Academic direction is guided by Principal / Headteacher Mr. Simon Muriungi Muthemba and Deputy Principal / Deputy Headteacher Mr. Patrick Kimathi, working alongside our teaching team.</p></div></section></PublicLayout>}
