import { useCallback, useEffect, useMemo, useState } from "react";
import { BookOpen, Loader2, Plus, RefreshCw, ShieldCheck, UserPlus, Users, X } from "lucide-react";
import { useLocation } from "wouter";
import { getSupabase } from "@/lib/supabase";
import { isAdministrator, useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { PortalLayout } from "@/components/PortalLayout";

type Teacher={id:string;employee_number:string;first_name:string;middle_name?:string|null;last_name:string;email?:string|null;profile_id?:string|null;status:string};
type ClassRow={id:string;name:string;code:string};
type Subject={id:string;name:string;code:string};
type Assignment={id:string;teacher_id:string;class_id:string;subject_id:string};
type ClassRole={teacher_id:string;class_id:string;is_class_teacher:boolean};
const input="min-h-11 w-full rounded-xl border border-[var(--ink)]/12 bg-white px-3 text-sm text-[var(--ink)] outline-none focus:border-[var(--gold)] focus:ring-4 focus:ring-[var(--gold)]/10";

export default function AdminTeachersPage(){
 const {user,profile,loading:authLoading}=useSchoolAuth(); const [,navigate]=useLocation();
 const [teachers,setTeachers]=useState<Teacher[]>([]); const [classes,setClasses]=useState<ClassRow[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [roles,setRoles]=useState<ClassRole[]>([]);
 const [selected,setSelected]=useState(""); const [classId,setClassId]=useState(""); const [subjectId,setSubjectId]=useState(""); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!user||!profile||!isAdministrator(profile.role))return;setLoading(true);setError("");try{const db=getSupabase();const [t,c,s,a,r]=await Promise.all([
  db.from("teachers").select("id,employee_number,first_name,middle_name,last_name,email,profile_id,status").order("first_name").order("last_name"),
  db.from("classes").select("id,name,code").eq("status","ACTIVE").order("name"),
  db.from("subjects").select("id,name,code").eq("status","ACTIVE").order("name"),
  db.from("teacher_assignments").select("id,teacher_id,class_id,subject_id"),
  db.from("teacher_class_roles").select("teacher_id,class_id,is_class_teacher")
 ]);const first=[t,c,s,a,r].find(x=>x.error);if(first?.error)throw first.error;setTeachers((t.data??[]) as Teacher[]);setClasses((c.data??[]) as ClassRow[]);setSubjects((s.data??[]) as Subject[]);setAssignments((a.data??[]) as Assignment[]);setRoles((r.data??[]) as ClassRole[]);}catch(e){setError(e instanceof Error?e.message:"Teacher data could not be loaded.");}finally{setLoading(false)}},[profile,user]);
 useEffect(()=>{if(authLoading)return;if(!user||!profile){navigate("/portal/login");return}if(!isAdministrator(profile.role)){navigate("/portal/teacher");return}void load()},[authLoading,load,navigate,profile,user]);
 const teacher=teachers.find(t=>t.id===selected); const teacherAssignments=useMemo(()=>assignments.filter(a=>a.teacher_id===selected),[assignments,selected]); const classTeacherIds=new Set(roles.filter(r=>r.is_class_teacher).map(r=>`${r.teacher_id}:${r.class_id}`));
 const addAssignment=async()=>{if(!selected||!classId||!subjectId)return;setBusy(true);setError("");setMessage("");try{const db=getSupabase();const {error:e}=await db.from("teacher_assignments").insert({teacher_id:selected,class_id:classId,subject_id:subjectId});if(e)throw e;setMessage("Teaching assignment added.");setClassId("");setSubjectId("");await load()}catch(e){setError(e instanceof Error?e.message:"Assignment could not be added.")}finally{setBusy(false)}};
 const removeAssignment=async(id:string)=>{if(!confirm("Remove this teaching assignment?"))return;setBusy(true);setError("");try{const {error:e}=await getSupabase().from("teacher_assignments").delete().eq("id",id);if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Assignment could not be removed.")}finally{setBusy(false)}};
 const toggleClassTeacher=async(cid:string)=>{if(!selected)return;setBusy(true);setError("");setMessage("");try{const db=getSupabase();const key=`${selected}:${cid}`;const isNow=classTeacherIds.has(key);if(isNow){const {error:e}=await db.from("teacher_class_roles").update({is_class_teacher:false}).eq("teacher_id",selected).eq("class_id",cid);if(e)throw e;const {error:e2}=await db.from("classes").update({class_teacher_id:null}).eq("id",cid).eq("class_teacher_id",selected);if(e2)throw e2;}else{const {error:e}=await db.from("teacher_class_roles").upsert({teacher_id:selected,class_id:cid,is_class_teacher:true},{onConflict:"teacher_id,class_id"});if(e)throw e;const {error:e2}=await db.from("classes").update({class_teacher_id:selected}).eq("id",cid);if(e2)throw e2;}setMessage(isNow?"Class-teacher role removed.":"Class-teacher role assigned.");await load()}catch(e){setError(e instanceof Error?e.message:"Class-teacher role could not be changed.")}finally{setBusy(false)}};
 if(authLoading||loading)return <PortalLayout role="ADMIN"><main className="grid min-h-[60vh] place-items-center"><div className="flex items-center gap-3 text-sm text-[var(--ink)]/60"><Loader2 className="animate-spin text-[var(--gold)]" size={19}/>Loading teachers…</div></main></PortalLayout>;
 return <PortalLayout role="ADMIN"><main className="mx-auto w-full max-w-[1200px] space-y-6 px-4 py-6 sm:px-6 lg:px-8 lg:py-10">
  <header className="menwe-admin-hero relative overflow-hidden rounded-[2.25rem] p-6 text-white shadow-2xl sm:p-9"><div className="relative z-10"><span className="menwe-admin-kicker"><Users size={14}/> Staff management</span><h1 className="mt-5 text-4xl font-extrabold tracking-[-.04em] sm:text-5xl">Teachers</h1><p className="mt-4 max-w-2xl text-[15px] leading-7 text-white/75">Manage teacher records, teaching subjects, classes, class-teacher roles and school account access from one place.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>navigate("/portal/admin/teacher-invitations")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--gold)] px-4 text-sm font-black text-[var(--ink)]"><UserPlus size={16}/> Invite teacher</button><button onClick={()=>void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 text-sm font-bold text-white"><RefreshCw size={16}/> Refresh</button></div></div></header>
  {message&&<div role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{message}</div>}{error&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800">{error}</div>}
  <section className="grid gap-4 sm:grid-cols-3"><div className="menwe-card rounded-2xl p-5"><p className="text-xs font-black uppercase tracking-widest text-[var(--ink)]/45">Teachers</p><p className="mt-2 text-3xl font-black">{teachers.length}</p></div><div className="menwe-card rounded-2xl p-5"><p className="text-xs font-black uppercase tracking-widest text-[var(--ink)]/45">Assignments</p><p className="mt-2 text-3xl font-black">{assignments.length}</p></div><div className="menwe-card rounded-2xl p-5"><p className="text-xs font-black uppercase tracking-widest text-[var(--ink)]/45">Accounts linked</p><p className="mt-2 text-3xl font-black">{teachers.filter(t=>t.profile_id).length}</p></div></section>
  <section className="grid gap-6 lg:grid-cols-[340px_1fr]">
   <div className="menwe-card rounded-[1.75rem] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="menwe-premium-label">Staff directory</p><h2 className="menwe-premium-title mt-1">All teachers</h2></div><span className="rounded-full bg-[var(--gold)]/10 px-3 py-1 text-xs font-black text-[var(--gold)]">{teachers.length}</span></div><div className="mt-5 grid gap-2">{teachers.map(t=><button key={t.id} onClick={()=>{setSelected(t.id);setMessage("");setError("")}} className={`rounded-xl border p-3 text-left transition ${selected===t.id?"border-[var(--gold)] bg-[var(--gold)]/8":"border-[var(--ink)]/8 hover:border-[var(--gold)]/30"}`}><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--ink)] text-xs font-black text-white">{`${t.first_name[0]??""}${t.last_name[0]??""}`}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{t.first_name} {t.last_name}</p><p className="truncate text-xs text-[var(--ink)]/50">Staff ID {t.employee_number}</p></div><span className={`ml-auto h-2.5 w-2.5 rounded-full ${t.profile_id?"bg-emerald-500":"bg-[var(--gold)]"}`} title={t.profile_id?"Account linked":"Not invited"}/></div></button>)}</div></div>
   <div className="menwe-card rounded-[1.75rem] p-5 sm:p-7">{!teacher?<div className="grid min-h-[420px] place-items-center text-center text-sm text-[var(--ink)]/50"><div><Users className="mx-auto mb-3 opacity-40" size={38}/><p className="font-bold">Select a teacher</p><p className="mt-1">Choose a staff member to manage their classes and subjects.</p></div></div>:<><div className="flex flex-col gap-4 border-b border-[var(--ink)]/8 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="menwe-premium-label">Teacher profile</p><h2 className="mt-1 text-2xl font-black">{teacher.first_name} {teacher.middle_name?`${teacher.middle_name} `:""}{teacher.last_name}</h2><p className="mt-1 text-sm text-[var(--ink)]/55">Staff ID {teacher.employee_number} · {teacher.email||"No email on record"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${teacher.profile_id?"bg-emerald-50 text-emerald-700":"bg-[var(--gold)]/10 text-[var(--gold)]"}`}>{teacher.profile_id?"Account linked":"Invite pending"}</span></div>
    <div className="mt-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[var(--ink)]/45">Teaching assignments</p><p className="mt-1 text-sm text-[var(--ink)]/55">Assign the classes and subjects this teacher teaches.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><select className={input} value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className={input} value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button disabled={busy||!classId||!subjectId} onClick={()=>void addAssignment()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 text-sm font-black text-white disabled:opacity-50"><Plus size={16}/> Add</button></div><div className="mt-4 grid gap-2">{teacherAssignments.length===0?<p className="rounded-xl bg-[var(--mist)] p-4 text-sm text-[var(--ink)]/50">No teaching assignments yet.</p>:teacherAssignments.map(a=>{const c=classes.find(x=>x.id===a.class_id),s=subjects.find(x=>x.id===a.subject_id);return <div key={a.id} className="flex items-center gap-3 rounded-xl border border-[var(--ink)]/8 p-3"><BookOpen size={17} className="text-[var(--gold)]"/><div className="min-w-0 flex-1"><p className="text-sm font-bold">{c?.name||"Unknown class"} · {s?.name||"Unknown subject"}</p><p className="text-xs text-[var(--ink)]/45">{c?.code||""} · {s?.code||""}</p></div><button disabled={busy} onClick={()=>void removeAssignment(a.id)} aria-label="Remove assignment" className="grid h-9 w-9 place-items-center rounded-lg text-[var(--ink)]/45 hover:bg-red-50 hover:text-red-600"><X size={16}/></button></div>})}</div></div>
    <div className="mt-7 border-t border-[var(--ink)]/8 pt-6"><div className="flex items-start gap-3"><ShieldCheck size={19} className="mt-0.5 text-[var(--gold)]"/><div><p className="text-xs font-black uppercase tracking-widest text-[var(--ink)]/45">Class-teacher roles</p><p className="mt-1 text-sm text-[var(--ink)]/55">Choose which class this teacher is responsible for as class teacher.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{classes.map(c=>{const active=classTeacherIds.has(`${selected}:${c.id}`);return <button key={c.id} disabled={busy} onClick={()=>void toggleClassTeacher(c.id)} className={`flex items-center justify-between rounded-xl border p-3 text-left ${active?"border-[var(--gold)] bg-[var(--gold)]/8":"border-[var(--ink)]/8"}`}><span className="text-sm font-bold">{c.name}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${active?"bg-[var(--gold)] text-[var(--ink)]":"bg-[var(--mist)] text-[var(--ink)]/50"}`}>{active?"Class teacher":"Not class teacher"}</span></button>})}</div></div>
    <div className="mt-7 rounded-2xl bg-[var(--mist)] p-4 text-sm text-[var(--ink)]/60"><p className="font-bold text-[var(--ink)]">Account access</p><p className="mt-1 leading-6">{teacher.profile_id?"This teacher has a linked school portal account.":"This teacher has no linked portal account yet."}</p>{!teacher.profile_id&&<button onClick={()=>navigate("/portal/admin/teacher-invitations")} className="mt-3 inline-flex items-center gap-2 font-black text-[var(--gold)]"><UserPlus size={15}/> Invite this teacher</button>}</div>
   </>}</div>
  </section>
 </main></PortalLayout>;
}
