import { useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, Loader2, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { getSupabase } from "@/lib/supabase";

const grades = ["PP1", "PP2", "Primary 1", "Primary 2", "Primary 3", "Primary 4", "Primary 5", "Primary 6", "JSS 7", "JSS 8", "JSS 9"];
const steps = ["Learner Details", "Parent / Guardian", "Academic History", "Checklist & Submit"];
const documents = ["Birth Certificate Copy", "Two Passport-Size Photos", "Transfer Letter / Assessment Report (Grades 2–9)", "Parent / Guardian ID Copy"];

type FormState = { learnerName: string; dob: string; gender: string; grade: string; upi: string; guardianName: string; phone: string; whatsapp: string; email: string; location: string; previousSchool: string; results: string; notes: string; birth: boolean; photos: boolean; transfer: boolean; confirm: boolean };
const initial: FormState = { learnerName: "", dob: "", gender: "", grade: "", upi: "", guardianName: "", phone: "", whatsapp: "", email: "", location: "", previousSchool: "", results: "", notes: "", birth: false, photos: false, transfer: false, confirm: false };
const inputClass = "mt-2 min-h-[48px] w-full min-w-0 max-w-full box-border rounded-xl border border-slate-200 bg-white px-4 py-3 text-base text-slate-900 outline-none transition focus:border-[#D89B28] focus:ring-2 focus:ring-[#D89B28]/20";
const buttonClass = "min-h-[48px] active:scale-[0.98] transition-all";
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block min-w-0 text-sm font-bold text-[#061229]">{label}{children}</label>; }
function referenceCode() { return `MNW-2026-${Math.floor(1000 + Math.random() * 9000)}`; }

export default function AdmissionsPage() {
  const [, navigate] = useLocation();
  const [step, setStep] = useState(1);
  const [form, setForm] = useState<FormState>(initial);
  const [busy, setBusy] = useState(false);
  const [success, setSuccess] = useState("");
  const [error, setError] = useState("");
  const update = (key: keyof FormState, value: string | boolean) => setForm(current => ({ ...current, [key]: value }));
  const validate = () => {
    if (step === 1 && (!form.learnerName.trim() || !form.dob || !form.gender || !form.grade)) return "Please complete the learner's name, date of birth, gender and grade.";
    if (step === 2 && (!form.guardianName.trim() || !form.phone.trim() || !form.email.trim() || !form.location.trim())) return "Please complete the guardian name, phone, email and location.";
    if (step === 3 && !form.previousSchool.trim()) return "Enter the previous school, or write Not applicable for a first-time learner.";
    if (step === 4 && (!form.birth || !form.photos || !form.confirm)) return "Please acknowledge the required documents and confirm the information is accurate.";
    return "";
  };
  const next = () => { setError(""); const message = validate(); if (message) { setError(message); return; } setStep(current => Math.min(4, current + 1)); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError(""); const message = validate(); if (message) { setError(message); return; }
    const reference = referenceCode(); setBusy(true);
    try {
      const supabase = getSupabase();
      const payload = { reference_code: reference, learner_full_name: form.learnerName.trim(), date_of_birth: form.dob, gender: form.gender, grade_applied: form.grade, nemis_upi_number: form.upi.trim() || null, parent_full_name: form.guardianName.trim(), parent_phone: form.phone.trim(), parent_whatsapp: form.whatsapp.trim() || null, parent_email: form.email.trim().toLowerCase(), sub_county_location: form.location.trim(), previous_school: form.previousSchool.trim(), last_kpsea_results: form.results.trim() || null, medical_dietary_notes: form.notes.trim() || null, status: "pending" };
      const { error: insertError } = await supabase.from("admissions").insert([payload]);
      if (insertError) throw insertError;
      setForm(initial); setSuccess(reference); window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (caught) {
      const detail = caught instanceof Error ? caught.message : "Unable to submit the application right now.";
      setError(`${detail} Your reference code is ${reference}. Please contact Admissions on 0142550882 and quote this code.`);
    } finally { setBusy(false); }
  };

  if (success) return <PublicLayout><main className="w-full overflow-hidden bg-[#F8F9FA] px-4 py-16 sm:px-6 lg:px-8"><section className="mx-auto w-full max-w-3xl rounded-3xl bg-white p-7 text-center shadow-xl sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 size={34}/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-[#D89B28]">Application received</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight text-[#061229] sm:text-4xl">Thank you — your application is on its way.</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-600">Your application reference is <strong>{success}</strong>. Keep this code when contacting the Admissions Office at 0142550882.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><a href="tel:0142550882" className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl bg-[#061229] px-5 py-3 font-bold text-white`}><Phone size={17}/> Call Admissions</a><a href="https://wa.me/254142550882" target="_blank" rel="noreferrer" className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 py-3 font-bold text-[#061229]`}><MessageCircle size={17}/> WhatsApp</a></div><button onClick={() => navigate("/")} className={`${buttonClass} mt-4 px-4 text-sm font-bold text-[#D89B28]`}>Return to homepage</button></section></main></PublicLayout>;

  return <PublicLayout><section className="relative overflow-hidden bg-gradient-to-br from-[#061229] via-[#0b1d3a] to-[#061229] text-white"><div className="pointer-events-none absolute -right-24 -top-24 h-80 w-80 rounded-full bg-[#D89B28]/15 blur-3xl"/><div className="relative mx-auto w-full max-w-7xl overflow-hidden px-4 py-16 sm:px-6 sm:py-20 lg:px-8"><span className="inline-flex rounded-full border border-[#D89B28]/30 bg-[#D89B28]/15 px-4 py-1.5 text-xs font-semibold uppercase tracking-wide text-[#D89B28]">2026 Admissions Open • PP1 to Grade 9 JSS</span><h1 className="mt-5 max-w-4xl text-3xl font-extrabold leading-tight tracking-tight sm:text-5xl">Join Our Learning Community</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-white/70 sm:text-lg">Enrol a new learner at Menwe Primary &amp; Junior School in Abogeta Sub-County, Meru. Complete the guided application below and our Admissions Office will contact your family about the next step.</p></div></section>
  <main className="w-full overflow-hidden bg-[#F8F9FA] px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto grid w-full max-w-7xl min-w-0 grid-cols-1 gap-7 lg:grid-cols-[minmax(0,1.25fr)_minmax(280px,.75fr)]"><section className="min-w-0 rounded-3xl bg-white p-5 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D89B28]">Digital application</p><h2 className="mt-2 text-2xl font-extrabold text-[#061229] sm:text-3xl">Step {step} of 4</h2></div><span className="shrink-0 rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600">{Math.round(step / 4 * 100)}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#D89B28] transition-all" style={{ width: `${step / 4 * 100}%` }}/></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{steps.map((label, index) => <button key={label} type="button" onClick={() => index + 1 < step && setStep(index + 1)} disabled={index + 1 > step} className={`${buttonClass} shrink-0 rounded-full px-3 py-2 text-xs font-bold ${index + 1 === step ? "bg-[#D89B28] text-[#061229]" : "bg-slate-100 text-slate-500 disabled:opacity-60"}`}>{index + 1}. {label}</button>)}</div>
  <form onSubmit={submit} className="mt-6">
    {step === 1 && <div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Learner Full Name"><input required className={inputClass} value={form.learnerName} onChange={e => update("learnerName", e.target.value)} /></Field><Field label="Date of Birth"><input required type="date" className={inputClass} value={form.dob} onChange={e => update("dob", e.target.value)} /></Field><Field label="Gender"><select required className={inputClass} value={form.gender} onChange={e => update("gender", e.target.value)}><option value="">Select gender</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></Field><Field label="Grade Applied For"><select required className={inputClass} value={form.grade} onChange={e => update("grade", e.target.value)}><option value="">Select grade</option>{grades.map(g => <option key={g}>{g}</option>)}</select></Field><Field label="NEMIS / Assessment UPI (if transferring)"><input className={inputClass} value={form.upi} onChange={e => update("upi", e.target.value)} /></Field></div>}
    {step === 2 && <div className="grid grid-cols-1 gap-5 sm:grid-cols-2"><Field label="Parent / Guardian Full Name"><input required className={inputClass} value={form.guardianName} onChange={e => update("guardianName", e.target.value)} /></Field><Field label="Primary Phone Number"><input required type="tel" className={inputClass} value={form.phone} onChange={e => update("phone", e.target.value)} /></Field><Field label="WhatsApp Number"><input type="tel" className={inputClass} value={form.whatsapp} onChange={e => update("whatsapp", e.target.value)} /></Field><Field label="Email Address"><input required type="email" className={inputClass} value={form.email} onChange={e => update("email", e.target.value)} /></Field><Field label="Sub-County / Village Location"><input required className={inputClass} value={form.location} onChange={e => update("location", e.target.value)} /></Field></div>}
    {step === 3 && <div className="grid grid-cols-1 gap-5"><Field label="Previous School Attended"><input required className={inputClass} value={form.previousSchool} onChange={e => update("previousSchool", e.target.value)} /></Field><Field label="Last KPSEA / Assessment Results"><textarea className="mt-2 min-h-[110px] w-full min-w-0 max-w-full box-border rounded-xl border border-slate-200 bg-white px-4 py-3 text-base outline-none focus:border-[#D89B28] focus:ring-2 focus:ring-[#D89B28]/20" value={form.results} onChange={e => update("results", e.target.value)} /></Field><Field label="Medical / Dietary Notes"><textarea className="mt-2 min-h-[110px] w-full min-w-0 max-w-full box-border rounded-xl border border-slate-200 bg-white px-4 py-3 text-base outline-none focus:border-[#D89B28] focus:ring-2 focus:ring-[#D89B28]/20" value={form.notes} onChange={e => update("notes", e.target.value)} /></Field></div>}
    {step === 4 && <div className="space-y-4"><div className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold text-[#061229]">Document checklist</h3><p className="mt-1 text-sm text-slate-500">Acknowledge what you will provide during the enrollment process.</p><div className="mt-4 space-y-3">{[["birth","Birth Certificate Copy"],["photos","Two Passport-Size Photos"],["transfer","Leaving / Transfer Certificate where applicable"]].map(([key, label]) => <label key={key} className="flex min-h-[48px] cursor-pointer items-center gap-3 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={Boolean(form[key as keyof FormState])} onChange={e => update(key as keyof FormState, e.target.checked)} className="h-5 w-5 shrink-0 accent-[#D89B28]" />{label}</label>)}</div></div><label className="flex min-h-[48px] cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 text-sm leading-6 text-slate-600"><input type="checkbox" checked={form.confirm} onChange={e => update("confirm", e.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-[#D89B28]" />I confirm that the information supplied is accurate and understand that final admission is subject to school review and document verification.</label></div>}
    {error && <div role="alert" className="mt-5 rounded-xl border border-red-100 bg-red-50 p-4 text-sm leading-6 text-red-700">{error}</div>}
    <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between">{step > 1 ? <button type="button" onClick={() => setStep(current => current - 1)} className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 py-3 font-bold text-[#061229]`}><ArrowLeft size={17}/> Back</button> : <span/>}{step < 4 ? <button type="button" onClick={next} className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl bg-[#061229] px-6 py-3 font-bold text-white`}>Continue <ArrowRight size={17}/></button> : <button type="submit" disabled={busy} className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl bg-[#D89B28] px-6 py-3 font-extrabold text-[#061229] disabled:cursor-not-allowed disabled:opacity-60`}>{busy ? <><Loader2 size={17} className="animate-spin"/> Submitting application…</> : <><ClipboardCheck size={17}/> Submit application</>}</button>}</div>
  </form></section>
  <aside className="grid min-w-0 gap-5 self-start"><section className="w-full min-w-0 rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D89B28]">Requirements</p><h2 className="mt-2 text-2xl font-extrabold text-[#061229]">What to prepare</h2><div className="mt-5 space-y-3">{documents.map(item => <div key={item} className="flex gap-3 rounded-xl bg-slate-50 p-3 text-sm leading-5 text-slate-700"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" size={17}/>{item}</div>)}</div></section><section className="w-full min-w-0 rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D89B28]">Enrolment schedule</p><h2 className="mt-2 text-2xl font-extrabold text-[#061229]">Plan ahead</h2><p className="mt-4 text-sm leading-6 text-slate-600">Confirm term opening dates and assessment interview availability with Admissions. Arrange uniform fitting before the learner's start date.</p></section><section className="w-full min-w-0 rounded-3xl bg-gradient-to-br from-[#061229] to-[#0b1d3a] p-6 text-white shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-xl bg-white/10 text-[#D89B28]"><ShieldCheck size={22}/></div><h2 className="mt-5 text-2xl font-extrabold">Need help?</h2><p className="mt-2 text-sm leading-6 text-white/65">Speak directly with the Admissions Office or arrange a campus visit.</p><div className="mt-5 grid gap-3"><a href="tel:0142550882" className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl bg-[#D89B28] px-4 py-3 font-extrabold text-[#061229]`}><Phone size={17}/> Call Admissions Office</a><a href="https://wa.me/254142550882" target="_blank" rel="noreferrer" className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-3 font-bold text-white`}><MessageCircle size={17}/> WhatsApp Admissions</a><a href="https://www.google.com/maps/search/?api=1&query=Menwe%20Primary%20Junior%20School%20Kionyo%20Meru%20Kenya" target="_blank" rel="noreferrer" className={`${buttonClass} inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-3 font-bold text-white`}><MapPin size={17}/> Map Directions</a></div></section></aside></div></main></PublicLayout>;
}
