import { AlertCircle, CheckCircle2, Clock3, MessageCircle, RefreshCw, Send, Settings, ShieldCheck, Smartphone, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { getSupabase } from "@/lib/supabase";
import { isAdministrator, useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { PortalLayout } from "@/components/PortalLayout";

type Setting = { key: string; value: any; is_public: boolean };
type Channel = { channel: "SMS" | "WHATSAPP"; enabled: boolean; provider: string | null; sender_label?: string | null; mode: "QUEUE_ONLY" | "PROVIDER" };
type QueueRow = { id: string; channel: string; recipient: string; message: string; event_type: string; status: string; attempts: number; scheduled_at: string; created_at: string; last_error?: string | null };
const fields = [["school_name", "School name", "text", true], ["contact_email", "Contact email", "email", true], ["contact_phone", "Contact phone", "text", true], ["address", "School address", "text", true], ["website", "Website", "text", true], ["admissions_open", "Admissions open", "boolean", true]] as const;
const channelDefaults: Record<"SMS" | "WHATSAPP", Channel> = { SMS: { channel: "SMS", enabled: false, provider: null, sender_label: null, mode: "QUEUE_ONLY" }, WHATSAPP: { channel: "WHATSAPP", enabled: false, provider: null, sender_label: null, mode: "QUEUE_ONLY" } };
const statusMeta: Record<string, { label: string; icon: typeof Clock3 }> = { QUEUED: { label: "Queued", icon: Clock3 }, PROCESSING: { label: "Processing", icon: RefreshCw }, SENT: { label: "Sent", icon: CheckCircle2 }, FAILED: { label: "Failed", icon: XCircle }, CANCELLED: { label: "Cancelled", icon: XCircle } };

export default function AdminSettingsPage() {
  const { user, profile, loading: authLoading } = useSchoolAuth(); const [, navigate] = useLocation();
  const [settings, setSettings] = useState<Record<string, any>>({}); const [publicFlags, setPublicFlags] = useState<Record<string, boolean>>({}); const [channels, setChannels] = useState<Record<"SMS" | "WHATSAPP", Channel>>(channelDefaults);
  const [queue, setQueue] = useState<QueueRow[]>([]); const [counts, setCounts] = useState<Record<string, number>>({}); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");

  const load = useCallback(async () => { if (!user || !profile || !isAdministrator(profile.role)) return; setLoading(true); setMessage(""); try { const db = getSupabase(); const [s, c, q] = await Promise.all([
    db.from("school_settings").select("key,value,is_public").order("key"), db.from("notification_channels").select("channel,enabled,provider,sender_label,mode").order("channel"), db.from("notification_outbox").select("id,channel,recipient,message,event_type,status,attempts,scheduled_at,created_at,last_error").order("created_at", { ascending: false }).limit(25)
  ]); if (s.error) throw s.error; if (c.error) throw c.error; if (q.error) throw q.error;
    const next: Record<string, any> = {}; const flags: Record<string, boolean> = {}; (s.data ?? []).forEach((r: Setting) => { next[r.key] = r.value; flags[r.key] = r.is_public; }); const nextChannels = { ...channelDefaults }; (c.data ?? []).forEach((r: Channel) => { if (r.channel === "SMS" || r.channel === "WHATSAPP") nextChannels[r.channel] = r; });
    const nextQueue = (q.data ?? []) as QueueRow[]; const nextCounts: Record<string, number> = {}; nextQueue.forEach(r => { nextCounts[r.status] = (nextCounts[r.status] ?? 0) + 1; }); setSettings(next); setPublicFlags(flags); setChannels(nextChannels); setQueue(nextQueue); setCounts(nextCounts);
  } catch (e) { setMessage(e instanceof Error ? e.message : "Settings and communication data could not be loaded."); } finally { setLoading(false); } }, [profile, user]);
  useEffect(() => { if (authLoading) return; if (!user || !profile) { navigate("/portal/login"); return; } if (!isAdministrator(profile.role)) { navigate("/portal/parent"); return; } void load(); }, [authLoading, load, navigate, profile, user]);

  const save = async () => { if (!user) return; setBusy(true); setMessage(""); try { const db = getSupabase(); for (const [key] of fields) { const raw = settings[key]; const value = key === "admissions_open" ? Boolean(raw) : String(raw ?? "").trim(); const r = await db.from("school_settings").upsert({ key, value, is_public: publicFlags[key] ?? true, updated_by: user.id, updated_at: new Date().toISOString() }, { onConflict: "key" }); if (r.error) throw r.error; } for (const channel of ["SMS", "WHATSAPP"] as const) { const r = await db.from("notification_channels").upsert({ channel, enabled: channels[channel].enabled, provider: channels[channel].provider, sender_label: channels[channel].sender_label ?? null, mode: channels[channel].mode, updated_by: user.id, updated_at: new Date().toISOString() }, { onConflict: "channel" }); if (r.error) throw r.error; } setMessage("School and communication settings saved."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Settings could not be saved."); } finally { setBusy(false); } };

  const summary = useMemo(() => ([ ["Queued", counts.QUEUED ?? 0, Clock3], ["Processing", counts.PROCESSING ?? 0, RefreshCw], ["Sent", counts.SENT ?? 0, CheckCircle2], ["Failed", counts.FAILED ?? 0, XCircle] ] as const), [counts]);
  return <PortalLayout role={profile?.role ?? "ADMIN"}><main className="mx-auto w-full max-w-[1400px] space-y-6 px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
    <header className="menwe-admin-hero rounded-[2rem] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="menwe-admin-kicker"><Settings size={14}/> System configuration</span><h1 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl">School settings</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/70">One secure control room for school details, parent communications and notification delivery readiness.</p></div><button onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 text-sm font-bold"><RefreshCw size={16}/>Refresh</button></div></header>
    {message && <div role="status" className="rounded-2xl border border-[var(--gold)]/25 bg-[var(--gold)]/10 px-4 py-3 text-sm font-semibold">{message}</div>}
    <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2">{loading ? <div className="py-12 text-center sm:col-span-2">Loading settings…</div> : fields.map(([key, label, type, publicDefault]) => <label key={key} className="grid gap-2 text-sm font-bold">{label}{type === "boolean" ? <div className="flex min-h-12 items-center justify-between rounded-xl border border-[var(--ink)]/12 bg-white px-3.5"><span className="text-[var(--ink)]/60">{settings[key] ? "Enabled" : "Disabled"}</span><input type="checkbox" checked={Boolean(settings[key])} onChange={e => setSettings(v => ({ ...v, [key]: e.target.checked }))}/></div> : <input type={type} value={settings[key] ?? ""} onChange={e => setSettings(v => ({ ...v, [key]: e.target.value }))} className="min-h-12 rounded-xl border border-[var(--ink)]/12 bg-white px-3.5 font-normal outline-none focus:border-[var(--gold)] focus:ring-4 focus:ring-[var(--gold)]/10"/>}<span className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.12em] text-[var(--ink)]/45"><input type="checkbox" checked={publicFlags[key] ?? publicDefault} onChange={e => setPublicFlags(v => ({ ...v, [key]: e.target.checked }))}/> Public setting</span></label>)}</div></section>

    <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><span className="menwe-admin-kicker !text-[var(--gold)]"><MessageCircle size={14}/> Parent communication</span><h2 className="mt-3 text-2xl font-extrabold tracking-tight">SMS & WhatsApp control room</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--ink)]/60">Enable a channel for internal queueing now. Actual external delivery remains blocked until a server-side provider is configured.</p></div><div className="hidden rounded-2xl bg-[var(--gold)]/10 p-3 sm:block"><Smartphone className="text-[var(--gold)]" size={24}/></div></div>
      <div className="mt-6 grid gap-4 md:grid-cols-2">{(["SMS", "WHATSAPP"] as const).map(channel => <div key={channel} className="rounded-2xl border border-[var(--ink)]/10 bg-white p-5 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-bold">{channel === "SMS" ? "SMS" : "WhatsApp"}</h3><span className="mt-2 inline-flex rounded-full bg-[var(--gold)]/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[var(--gold)]">{channels[channel].mode === "QUEUE_ONLY" ? "Queue only" : "Provider"}</span></div><label className="flex items-center gap-2 text-xs font-bold"><span>{channels[channel].enabled ? "Enabled" : "Off"}</span><input type="checkbox" checked={channels[channel].enabled} onChange={e => setChannels(v => ({ ...v, [channel]: { ...v[channel], enabled: e.target.checked } }))}/></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-[var(--ink)]/55">Provider<input value={channels[channel].provider ?? ""} onChange={e => setChannels(v => ({ ...v, [channel]: { ...v[channel], provider: e.target.value || null } }))} placeholder="Not connected" className="min-h-10 rounded-xl border px-3 font-normal text-[var(--ink)] outline-none focus:border-[var(--gold)]"/></label><label className="grid gap-1 text-xs font-bold text-[var(--ink)]/55">Sender label<input value={channels[channel].sender_label ?? ""} onChange={e => setChannels(v => ({ ...v, [channel]: { ...v[channel], sender_label: e.target.value || null } }))} placeholder="Menwe School" className="min-h-10 rounded-xl border px-3 font-normal text-[var(--ink)] outline-none focus:border-[var(--gold)]"/></label></div><div className="mt-4 flex items-start gap-2 rounded-xl border border-dashed border-[var(--ink)]/10 bg-[var(--paper)] p-3 text-xs leading-5 text-[var(--ink)]/55"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-[var(--gold)]"/>API keys are never entered here and are never exposed to the browser.</div></div>)}</div>
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summary.map(([label,value,Icon]) => <div key={label} className="menwe-card rounded-2xl p-5"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--ink)]/5 text-[var(--ink)]"><Icon size={18}/></span><strong className="text-3xl font-black">{value}</strong></div><p className="mt-4 text-sm font-bold">{label}</p><p className="mt-1 text-xs text-[var(--ink)]/50">Recent queue records</p></div>)}</section>

    <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><span className="menwe-admin-kicker !text-[var(--gold)]"><Send size={14}/> Delivery queue</span><h2 className="mt-3 text-2xl font-extrabold">Recent notification jobs</h2><p className="mt-2 text-sm text-[var(--ink)]/60">Administrators can monitor jobs without exposing provider credentials or sending test messages accidentally.</p></div><button type="button" onClick={() => navigate("/portal/notifications")} className="inline-flex min-h-10 items-center gap-2 rounded-xl border px-4 text-sm font-bold">Open notification inbox</button></div>{queue.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wider text-[var(--ink)]/45"><th className="px-3 py-3">Channel</th><th className="px-3 py-3">Recipient</th><th className="px-3 py-3">Event</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Attempts</th><th className="px-3 py-3">Created</th></tr></thead><tbody>{queue.map(row => { const meta = statusMeta[row.status] ?? statusMeta.QUEUED; const Icon = meta.icon; return <tr key={row.id} className="border-b last:border-0"><td className="px-3 py-4 font-bold">{row.channel}</td><td className="px-3 py-4">{row.recipient}</td><td className="px-3 py-4 text-[var(--ink)]/60">{row.event_type}</td><td className="px-3 py-4"><span className="inline-flex items-center gap-1.5 rounded-full bg-[var(--gold)]/10 px-2.5 py-1 text-xs font-bold text-[var(--gold)]"><Icon size={13}/>{meta.label}</span></td><td className="px-3 py-4">{row.attempts}</td><td className="px-3 py-4 text-xs text-[var(--ink)]/50">{new Date(row.created_at).toLocaleString("en-KE")}</td></tr>})}</tbody></table></div> : <div className="mt-6 rounded-2xl border border-dashed p-10 text-center"><AlertCircle className="mx-auto text-[var(--gold)]" size={22}/><p className="mt-3 text-sm font-bold">No delivery jobs yet</p><p className="mt-1 text-xs text-[var(--ink)]/50">The queue is ready. Jobs will appear here when a school event creates a notification.</p></div>}</section>

    <div className="flex flex-wrap items-center gap-3"><button disabled={busy || loading} onClick={() => void save()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--ink)] px-5 text-sm font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Save settings"}</button><span className="flex items-center gap-2 text-xs font-semibold text-[var(--ink)]/55"><ShieldCheck size={15} className="text-[var(--gold)]"/>Administrator-only configuration</span></div>
    <section className="rounded-[1.75rem] border border-[var(--gold)]/20 bg-[var(--gold)]/5 p-5 sm:p-7"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 text-[var(--gold)]" size={20}/><div><h2 className="font-bold">Safe provider architecture</h2><p className="mt-1 text-sm leading-6 text-[var(--ink)]/60">The portal is provider-ready but deliberately does not pretend SMS or WhatsApp delivery is connected. When the school chooses a provider, its secret belongs in server-side/Edge Function secrets—not in this page.</p></div></div></section>
  </main></PortalLayout>;
}
