import { Loader2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";

type Tab = "pages" | "news" | "events" | "admissions" | "contacts";
type Row = Record<string, unknown>;
const pageSize = 25;
const adminClass = "w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[var(--accent)]";
const text = (v: unknown) => v == null || v === "" ? "—" : String(v);

export default function ContentManagement() {
  const [tab, setTab] = useState<Tab>("pages"); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [page, setPage] = useState(0);
  const [values, setValues] = useState({ slug: "", title: "", headline: "", body: "", excerpt: "", status: "Draft", starts_at: "", ends_at: "" });
  const set = (k: keyof typeof values, v: string) => setValues(s => ({ ...s, [k]: v }));
  const reset = () => setValues({ slug: "", title: "", headline: "", body: "", excerpt: "", status: "Draft", starts_at: "", ends_at: "" });

  const refresh = useCallback(async () => { setLoading(true); setMessage(null); const from = page * pageSize; const to = from + pageSize - 1; const db = getSupabase();
    const request = tab === "pages" ? db.from("content_pages").select("id,slug,title,headline,body,status,updated_at", { count: "exact" }).order("updated_at", { ascending: false }).range(from,to)
      : tab === "news" ? db.from("news_articles").select("id,title,slug,excerpt,status,published_at,created_at", { count: "exact" }).order("created_at", { ascending: false }).range(from,to)
      : tab === "events" ? db.from("events").select("id,title,description,starts_at,ends_at,audience", { count: "exact" }).order("starts_at", { ascending: false }).range(from,to)
      : tab === "admissions" ? db.from("applications").select("id,reference,student_name,parent_name,parent_email,parent_phone,status,created_at", { count: "exact" }).order("created_at", { ascending: false }).range(from,to)
      : db.from("contact_submissions").select("id,name,email,subject,status,created_at,read_at", { count: "exact" }).order("created_at", { ascending: false }).range(from,to);
    const { data, error } = await request; if (error) setMessage("Unable to load authorised content records."); else setRows((data ?? []) as Row[]); setLoading(false);
  }, [page, tab]);
  useEffect(() => { void refresh(); }, [refresh]);
  const choose = (next: Tab) => { setTab(next); setPage(0); reset(); setMessage(null); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); const db = getSupabase(); try {
    if (tab === "pages") { const { error } = await db.from("content_pages").upsert({ slug: values.slug, title: values.title, headline: values.headline || null, body: { content: values.body }, status: values.status, published_at: values.status === "Published" ? new Date().toISOString() : null }); if (error) throw error; }
    if (tab === "news") { const slug = values.slug.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""); const { error } = await db.from("news_articles").upsert({ slug, title: values.title, excerpt: values.excerpt || null, body: values.body, status: values.status, published_at: values.status === "Published" ? new Date().toISOString() : null }); if (error) throw error; }
    if (tab === "events") { const { error } = await db.from("events").insert({ title: values.title, description: values.body || null, starts_at: values.starts_at, ends_at: values.ends_at, audience: "all" }); if (error) throw error; }
    reset(); setMessage("Saved to Supabase."); await refresh();
  } catch { setMessage("The record could not be saved. Check required fields and permissions."); } finally { setBusy(false); } };
  const updateStatus = async (table: "applications" | "contact_submissions", id: string, status: string) => { setBusy(true); const payload = table === "applications" ? { status } : { status, read_at: status === "Read" ? new Date().toISOString() : null }; const { error } = await getSupabase().from(table).update(payload).eq("id", id); setBusy(false); setMessage(error ? "Status update failed." : "Status updated."); if (!error) await refresh(); };
  const tabs: Tab[] = ["pages","news","events","admissions","contacts"];
  return <div className="grid gap-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">School publishing</p><h1 className="mt-2 font-serif text-4xl font-semibold">Public content & enquiries</h1></div><div className="flex flex-wrap gap-2">{tabs.map(t => <button key={t} type="button" onClick={() => choose(t)} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab===t?"bg-[var(--ink)] text-white":"bg-white text-[var(--ink)]/65"}`}>{t}</button>)}</div>
  <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="menwe-card rounded-[1.75rem] p-5 sm:p-7">{loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin"/></div>:rows.length===0?<p className="py-12 text-center text-sm text-[var(--ink)]/55">No records yet.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-[var(--ink)]/45">{["Record","Details","Status","Created","Action"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={text(r.id)} className="border-b"><td className="p-3 font-semibold">{text(r.title ?? r.reference ?? r.name)}</td><td className="p-3">{text(r.student_name ?? r.excerpt ?? r.description ?? r.slug ?? r.subject)}</td><td className="p-3">{text(r.status ?? r.audience)}</td><td className="p-3">{text(r.created_at ?? r.updated_at)}</td><td className="p-3">{tab==="admissions"?<select value={text(r.status)} disabled={busy} onChange={e=>void updateStatus("applications",text(r.id),e.target.value)} className="rounded border px-2 py-1"><option>Submitted</option><option>Under Review</option><option>Admitted</option><option>Rejected</option><option>Converted</option></select>:tab==="contacts"?<select value={text(r.status)} disabled={busy} onChange={e=>void updateStatus("contact_submissions",text(r.id),e.target.value)} className="rounded border px-2 py-1"><option>New</option><option>Read</option><option>Archived</option></select>:"—"}</td></tr>)}</tbody></table></div>}{page>0&&<button className="mt-4 rounded-lg border px-3 py-2 text-sm" onClick={()=>setPage(p=>p-1)}>Previous</button>}{rows.length===pageSize&&<button className="ml-2 mt-4 rounded-lg border px-3 py-2 text-sm" onClick={()=>setPage(p=>p+1)}>Next</button>}</section>
  {(tab==="pages"||tab==="news"||tab==="events")&&<section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><h2 className="font-serif text-2xl font-semibold">Create content</h2><form onSubmit={save} className="mt-5 grid gap-3">{tab!=="events"&&<input required placeholder={tab==="pages"?"Slug":"News slug"} value={values.slug} onChange={e=>set("slug",e.target.value)} className={adminClass}/>}<input required placeholder="Title" value={values.title} onChange={e=>set("title",e.target.value)} className={adminClass}/>{tab==="pages"&&<input placeholder="Headline" value={values.headline} onChange={e=>set("headline",e.target.value)} className={adminClass}/>} {tab==="news"&&<input placeholder="Excerpt" value={values.excerpt} onChange={e=>set("excerpt",e.target.value)} className={adminClass}/>} {tab==="events"&&<><input required type="datetime-local" value={values.starts_at} onChange={e=>set("starts_at",e.target.value)} className={adminClass}/><input required type="datetime-local" value={values.ends_at} onChange={e=>set("ends_at",e.target.value)} className={adminClass}/></>}<textarea required placeholder="Content" value={values.body} onChange={e=>set("body",e.target.value)} className={`${adminClass} min-h-40`}/>{tab!=="events"&&<select value={values.status} onChange={e=>set("status",e.target.value)} className={adminClass}><option>Draft</option><option>Published</option><option>Archived</option></select>}<button disabled={busy} className="rounded-xl bg-[var(--ink)] px-4 py-3 font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save"}</button>{message&&<p className="text-sm text-[var(--ink)]/60">{message}</p>}</form></section>}</div></div>;
}
