import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, GraduationCap, HeartHandshake, LayoutDashboard, LockKeyhole, MessageCircle, ShieldCheck, Sparkles, UsersRound, WalletCards } from "lucide-react";
import { useLocation } from "wouter";
import PublicLayout from "@/components/PublicLayout";

const experience = [
  { icon: BookOpen, title: "Learning, connected", text: "Academics, homework, exams, results and report cards are designed to work together as one learning record.", path: "/academics" },
  { icon: CalendarDays, title: "A clearer school day", text: "Attendance and timetables give authorised members of the school community a shared, current view of the day.", path: "/portal/login" },
  { icon: MessageCircle, title: "Communication with context", text: "School messages and notifications stay in the secure portal, with access shaped by each person's role.", path: "/portal/login" },
  { icon: WalletCards, title: "Finance without fragments", text: "Charges, payments, allocations and balances remain connected for the people authorised to see them.", path: "/portal/login" },
  { icon: ShieldCheck, title: "Privacy as a foundation", text: "Public information is separated from protected school records, with database authorization behind the interface.", path: "/about" },
  { icon: LayoutDashboard, title: "One calm workspace", text: "Administrators get the operational tools they need without making families or learners navigate the same complexity.", path: "/portal/login" },
];

function Card({ item }: { item: typeof experience[number] }) {
  const [, go] = useLocation();
  const Icon = item.icon;
  return <button type="button" onClick={() => go(item.path)} className="menwe-feature group relative overflow-hidden rounded-[1.5rem] border border-[var(--ink)]/9 bg-white p-6 text-left transition duration-500 hover:-translate-y-1 hover:shadow-[0_22px_55px_rgba(29,43,37,.09)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"><span className="menwe-feature-orb" aria-hidden="true" /><span className="relative grid h-11 w-11 place-items-center rounded-xl bg-[var(--mist)] text-[var(--accent)] transition group-hover:scale-110"><Icon size={20} /></span><p className="relative mt-7 font-serif text-2xl font-semibold tracking-tight">{item.title}</p><p className="relative mt-3 text-sm leading-6 text-[var(--ink)]/58">{item.text}</p><span className="relative mt-6 inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.16em] text-[var(--accent)]">Explore <ArrowRight size={13} className="transition group-hover:translate-x-1" /></span></button>;
}

export function SchoolLifePage() {
  const [, go] = useLocation();
  return <PublicLayout><section className="relative overflow-hidden bg-[var(--ink)] text-white"><div className="menwe-aurora menwe-aurora-one" /><div className="menwe-aurora menwe-aurora-two" /><div className="relative mx-auto max-w-[1440px] px-5 py-24 lg:px-10 lg:py-32"><p className="text-[9px] font-extrabold uppercase tracking-[.25em] text-[var(--gold)]">School life</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-semibold leading-[.94] tracking-[-.05em] sm:text-7xl">A window into the moments that make a school.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-white/58 sm:text-lg sm:leading-8">Published news, events and gallery stories can bring the public side of school life to one calm, welcoming space.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => go("/gallery")} className="inline-flex items-center gap-2 rounded-full bg-[var(--gold)] px-6 py-3.5 text-sm font-extrabold text-[var(--ink)]">Explore gallery <ArrowRight size={16} /></button><button onClick={() => go("/events")} className="inline-flex items-center gap-2 rounded-full border border-white/14 bg-white/[.06] px-6 py-3.5 text-sm font-bold text-white">See events <CalendarDays size={16} /></button></div></div></section><section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10 lg:py-32"><div className="max-w-2xl"><p className="text-[9px] font-extrabold uppercase tracking-[.25em] text-[var(--accent)]">Explore</p><h2 className="mt-4 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">The public story stays connected to the real school.</h2><p className="mt-5 text-base leading-7 text-[var(--ink)]/55">Only content intentionally published by authorised school administrators appears here. When there is nothing published yet, the experience stays honest rather than inventing stories.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><Card item={experience[0]} /><Card item={experience[1]} /><Card item={experience[4]} /></div></section></PublicLayout>;
}

export function FamiliesPage() {
  const [, go] = useLocation();
  const familyCards = [
    { icon: HeartHandshake, title: "A clearer connection", text: "Keep the school relationship in one secure place instead of searching across disconnected channels." },
    { icon: UsersRound, title: "Your children, your view", text: "Authorised parent access is designed around linked children, keeping unrelated student records out of view." },
    { icon: CheckCircle2, title: "Progress you can follow", text: "Attendance, homework, results, report cards and timetable information can be brought together as school records become available." },
  ];
  return <PublicLayout><section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-[9px] font-extrabold uppercase tracking-[.25em] text-[var(--accent)]">For families</p><h1 className="mt-5 font-serif text-5xl font-semibold leading-[.95] tracking-[-.05em] sm:text-7xl">School information, without the chase.</h1></div><div><p className="max-w-2xl text-lg leading-8 text-[var(--ink)]/58">Menwe gives families a focused view of the information they are authorised to access — from learning and attendance to communication and fees.</p><button onClick={() => go("/portal/login")} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[var(--ink)] px-6 py-3.5 text-sm font-extrabold text-white">Open family portal <ArrowRight size={16} /></button></div></div><div className="mt-16 grid gap-5 md:grid-cols-3">{familyCards.map(({ icon: Icon, title, text }) => <div key={title} className="menwe-value-card"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[var(--mist)] text-[var(--accent)]"><Icon size={20} /></span><div><h2 className="font-serif text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-[var(--ink)]/58">{text}</p></div></div>)}</div><div className="mt-10 grid gap-5 md:grid-cols-2"><div className="rounded-[1.8rem] bg-[var(--mist)] p-8"><LockKeyhole className="text-[var(--accent)]" size={24} /><h2 className="mt-8 font-serif text-3xl font-semibold">Private where it matters.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[var(--ink)]/58">Family records are not public website content. Portal access is protected by authentication and role-aware database permissions.</p></div><div className="rounded-[1.8rem] bg-[var(--ink)] p-8 text-white"><Sparkles className="text-[var(--gold)]" size={24} /><h2 className="mt-8 font-serif text-3xl font-semibold">Simple on the surface.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-white/55">The interface stays calm even when the underlying school workflows are complex.</p></div></div></section></PublicLayout>;
}

export function HowItWorksPage() {
  const [, go] = useLocation();
  const steps = [
    ["01", "Set the foundation", "School administrators establish academic periods, terms, classes, subjects and staff using the real school structure."],
    ["02", "Connect the community", "Students, parents and teachers are connected through enrolments and authorised relationships."],
    ["03", "Run the day", "Attendance, homework, timetable, messages, notifications and admissions support everyday operations."],
    ["04", "Understand progress", "Exams, results, report cards and finance turn activity into useful records for authorised users."],
  ];
  return <PublicLayout><section className="relative overflow-hidden bg-[var(--mist)]"><div className="menwe-section-glow" /><div className="relative mx-auto max-w-[1440px] px-5 py-24 lg:px-10 lg:py-32"><p className="text-[9px] font-extrabold uppercase tracking-[.25em] text-[var(--accent)]">How Menwe works</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-semibold leading-[.94] tracking-[-.05em] sm:text-7xl">A school platform built as one connected system.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--ink)]/58">The value is not another dashboard. It is the relationship between the records that make school operations work.</p></div></section><section className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10 lg:py-32"><div className="grid gap-5 lg:grid-cols-2">{steps.map(([number,title,text]) => <div key={number} className="group rounded-[1.7rem] border border-[var(--ink)]/8 bg-white p-8 transition duration-500 hover:-translate-y-1 hover:shadow-[0_22px_55px_rgba(29,43,37,.08)]"><span className="font-mono text-xs font-bold text-[var(--accent)]">{number}</span><h2 className="mt-12 font-serif text-3xl font-semibold tracking-tight">{title}</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[var(--ink)]/58">{text}</p></div>)}</div><div className="mt-12 flex flex-wrap items-center justify-between gap-6 rounded-[1.8rem] bg-[var(--ink)] p-8 text-white"><div><p className="font-serif text-2xl font-semibold">Ready to explore?</p><p className="mt-2 text-sm text-white/50">Start with the public story or enter the secure portal.</p></div><div className="flex flex-wrap gap-3"><button onClick={() => go("/about")} className="rounded-full border border-white/15 px-5 py-3 text-sm font-bold">About Menwe</button><button onClick={() => go("/portal/login")} className="rounded-full bg-[var(--gold)] px-5 py-3 text-sm font-extrabold text-[var(--ink)]">Open portal <ArrowRight size={15} className="ml-1 inline" /></button></div></div></section></PublicLayout>;
}
