import { CreditCard, Loader2, RefreshCw, Search, TrendingDown, TrendingUp, Save, ReceiptText, Download, Printer } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useLocation } from "wouter";
import { getSupabase } from "@/lib/supabase";
import { isAdministrator, useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { PortalLayout } from "@/components/PortalLayout";

type Row=Record<string,any>;
const PAGE_SIZE=50; const text=(v:unknown,fallback="—")=>v==null||v===""?fallback:String(v); const money=(v:unknown)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(v??0));
const input="min-h-11 w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[var(--gold)]";
const csvCell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;

export default function FinanceDirectory(){
 const {user,profile,loading:authLoading}=useSchoolAuth(); const [,navigate]=useLocation();
 const [tab,setTab]=useState<"invoices"|"payments">("invoices"); const [rows,setRows]=useState<Row[]>([]); const [invoices,setInvoices]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState<string|null>(null); const [query,setQuery]=useState(""); const [teacherClass,setTeacherClass]=useState(false); const [teacherClasses,setTeacherClasses]=useState<Row[]>([]);
 const [paymentInvoice,setPaymentInvoice]=useState(""); const [paymentAmount,setPaymentAmount]=useState(""); const [paymentMethod,setPaymentMethod]=useState("CASH"); const [paymentReference,setPaymentReference]=useState(""); const [paymentDate,setPaymentDate]=useState(()=>new Date().toISOString().slice(0,10)); const [busy,setBusy]=useState(false);
 const admin=!!profile&&isAdministrator(profile.role); const teacher=profile?.role==="TEACHER";
 const refresh=useCallback(async()=>{if(!user||!profile||(!admin&&!teacher))return;setLoading(true);setMessage(null);try{const db=getSupabase();
   if(teacher){const tr=await db.from("teachers").select("id").eq("profile_id",user.id).maybeSingle();if(tr.error)throw tr.error;if(!tr.data)throw new Error("Your teacher record is not linked yet.");const roles=await db.from("teacher_class_roles").select("class_id,is_class_teacher,classes(id,name,code)").eq("teacher_id",tr.data.id).eq("is_class_teacher",true);if(roles.error)throw roles.error;setTeacherClasses(roles.data??[]);setTeacherClass((roles.data??[]).length>0);}
   if(tab==="invoices"){let q=db.from("invoices").select("id,student_id,academic_year_id,term_id,invoice_number,issued_on,due_on,status,total_amount,students(admission_number,first_name,middle_name,last_name)").order("issued_on",{ascending:false});if(query.trim())q=q.ilike("invoice_number",`%${query.trim()}%`);const r=await q.range(0,PAGE_SIZE-1);if(r.error)throw r.error;setRows(r.data??[]);setInvoices(r.data??[]);}else{let q=db.from("payments").select("id,invoice_id,amount,payment_method,provider,transaction_reference,provider_reference,status,paid_at,verified_at,verified_by,created_at,invoices(invoice_number,student_id,students(admission_number,first_name,middle_name,last_name))").order("created_at",{ascending:false});if(query.trim())q=q.or(`transaction_reference.ilike.%${query.trim()}%,provider_reference.ilike.%${query.trim()}%`);const r=await q.range(0,PAGE_SIZE-1);if(r.error)throw r.error;setRows(r.data??[]);}}
   catch(e){setRows([]);setMessage(e instanceof Error?e.message:"Finance records could not be loaded.");}finally{setLoading(false);}},[admin,profile,query,tab,teacher,user]);
 useEffect(()=>{if(authLoading)return;if(!user||!profile){navigate("/portal/login");return;}if(!admin&&!teacher){navigate("/portal");return;}void refresh();},[admin,authLoading,navigate,profile,refresh,teacher,user]);
 const totals=rows.reduce((a,r)=>a+Number(r.amount??0),0);
 const downloadRecords=()=>{if(rows.length===0)return;const headers=tab==="invoices"?["Invoice","Learner","Admission No.","Issued","Due","Status","Total Amount (KES)"]:["Invoice","Learner","Admission No.","Amount (KES)","Payment Method","Receipt / Reference","Status","Paid At","Verified At"];const data=rows.map(r=>{const s=tab==="invoices"?r.students as Row|null:(r.invoices as Row|null)?.students as Row|null;const inv=tab==="payments"?r.invoices as Row|null:null;return tab==="invoices"?[r.invoice_number,[s?.first_name,s?.middle_name,s?.last_name].filter(Boolean).join(" "),s?.admission_number,r.issued_on,r.due_on,r.status,r.total_amount]:[inv?.invoice_number,[s?.first_name,s?.middle_name,s?.last_name].filter(Boolean).join(" "),s?.admission_number,r.amount,r.payment_method,r.transaction_reference||r.provider_reference,r.status,r.paid_at,r.verified_at]});const csv=[headers,...data].map(row=>row.map(csvCell).join(",")).join("\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`menwe-${tab}-records-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage(`${tab==="payments"?"Receipt/payment":"Invoice"} records downloaded as CSV.`);};
 const printRecords=()=>window.print();
 const recordPayment=async(e:React.FormEvent)=>{e.preventDefault();if(!teacher||!teacherClass||!paymentInvoice||!paymentAmount||!paymentReference.trim())return;setBusy(true);setMessage(null);try{const r=await getSupabase().from("payments").insert({invoice_id:paymentInvoice,amount:Number(paymentAmount),payment_method:paymentMethod,transaction_reference:paymentReference.trim(),paid_at:new Date(`${paymentDate}T12:00:00`).toISOString()});if(r.error)throw r.error;setPaymentAmount("");setPaymentReference("");setPaymentInvoice("");setPaymentDate(new Date().toISOString().slice(0,10));setMessage("Receipt recorded as PENDING. An administrator must verify it before it is treated as confirmed school revenue.");setTab("payments");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Receipt could not be recorded.");}finally{setBusy(false);}};
 const updatePayment=async(id:string,amount:string,method:string,reference:string)=>{if(!teacher||!teacherClass)return;setBusy(true);setMessage(null);try{const r=await getSupabase().from("payments").update({amount:Number(amount),payment_method:method,transaction_reference:reference.trim()}).eq("id",id);if(r.error)throw r.error;setMessage("Class receipt updated. It remains subject to administrator verification.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Receipt could not be updated.");}finally{setBusy(false);}};
 if(authLoading)return <main className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-[var(--accent)]"/></main>; if(!profile)return null;
 return <PortalLayout role={profile.role}><main className="mx-auto w-full max-w-[1440px] space-y-6 px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
  <header className="menwe-portal-hero rounded-[2rem] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="menwe-portal-kicker"><CreditCard size={14}/> Finance</span><h1 className="mt-4 font-serif text-4xl font-semibold">{teacher?"My class fees":"Fees & payments"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">{teacher?"Class teachers can record receipts for learners in their designated class(es) as payments arrive. Every teacher-entered receipt stays PENDING until an administrator verifies it.":"Live invoices and payment records from the canonical school finance model."}</p></div><button type="button" onClick={()=>void refresh()} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 text-sm font-bold"><RefreshCw className={loading?"animate-spin":""} size={17}/>Refresh</button></div></header>
  {teacher&&<section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><p className="menwe-premium-label">Class teacher access</p><h2 className="menwe-premium-title mt-1">{teacherClass?"Your designated class(es)":"No class-teacher designation"}</h2><div className="mt-4 flex flex-wrap gap-2">{teacherClasses.map(r=><span key={text(r.class_id)} className="rounded-full bg-[var(--gold)]/10 px-3 py-1 text-xs font-bold text-[var(--gold)]">{text(r.classes?.name)}</span>)}</div>{!teacherClass&&<p className="mt-3 text-sm text-[var(--ink)]/55">You can teach subjects without seeing class finances. A class-teacher designation is required for fee access.</p>}</section>}
  {teacher&&teacherClass&&<form onSubmit={recordPayment} className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex items-start gap-3"><div className="rounded-xl bg-[var(--gold)]/10 p-2 text-[var(--gold)]"><ReceiptText size={20}/></div><div><p className="menwe-premium-label">Record receipt</p><h2 className="menwe-premium-title mt-1">Update fees as payments arrive</h2><p className="mt-2 text-sm text-[var(--ink)]/55">Enter the learner's invoice, amount received, payment method and receipt/reference number. The receipt is immediately visible to authorised finance staff but remains PENDING until an administrator verifies it.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-5"><select required value={paymentInvoice} onChange={e=>setPaymentInvoice(e.target.value)} className={input}><option value="">Select learner / invoice</option>{invoices.map(i=><option key={text(i.id)} value={text(i.id)}>{text(i.invoice_number)} — {[i.students?.first_name,i.students?.last_name].filter(Boolean).join(" ")} ({money(i.total_amount)})</option>)}</select><input required min="0.01" type="number" step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} placeholder="Amount received (KES)" className={input}/><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} className={input}><option>CASH</option><option>MPESA</option><option>BANK</option><option>CHEQUE</option><option>OTHER</option></select><input required type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)} className={input}/><div className="flex gap-2"><input required value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} placeholder="Receipt / reference no." className={input}/><button disabled={busy} className="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[var(--ink)] px-4 text-sm font-bold text-white"><Save size={16}/>Record</button></div></div></form>}
  {message&&<div role="alert" className="rounded-2xl border border-[var(--gold)]/20 bg-[var(--gold)]/10 px-4 py-3 text-sm text-[var(--ink)]">{message}</div>}
  <section className="grid gap-4 sm:grid-cols-3"><article className="menwe-card rounded-2xl p-5"><CreditCard className="text-[var(--accent)]" size={20}/><p className="mt-3 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/50">Records on page</p><p className="mt-1 text-2xl font-black">{rows.length}</p></article><article className="menwe-card rounded-2xl p-5"><TrendingUp className="text-[var(--accent)]" size={20}/><p className="mt-3 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/50">Value on page</p><p className="mt-1 text-2xl font-black">{money(totals)}</p></article><article className="menwe-card rounded-2xl p-5"><TrendingDown className="text-[var(--accent)]" size={20}/><p className="mt-3 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/50">Access</p><p className="mt-1 text-sm font-bold">{admin?"Whole school":"Designated class(es) only"}</p></article></section>
  <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={()=>setTab("invoices")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${tab==="invoices"?"bg-[var(--ink)] text-white":"border border-[var(--ink)]/15"}`}>Invoices</button><button type="button" onClick={()=>setTab("payments")} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${tab==="payments"?"bg-[var(--ink)] text-white":"border border-[var(--ink)]/15"}`}>Receipts / payments</button><div className="ml-auto flex flex-wrap gap-2"><button type="button" disabled={rows.length===0} onClick={downloadRecords} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--ink)]/15 px-3 py-2 text-xs font-bold disabled:opacity-40"><Download size={15}/>Download CSV</button><button type="button" disabled={rows.length===0} onClick={printRecords} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--ink)]/15 px-3 py-2 text-xs font-bold disabled:opacity-40"><Printer size={15}/>Print / PDF</button></div></div><label className="mt-4 flex min-h-12 items-center gap-2 rounded-xl border border-[var(--ink)]/15 bg-white px-3"><Search size={17} className="text-[var(--accent)]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tab==="invoices"?"Search invoice number…":"Search receipt / transaction reference…"} className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/></label></section>
  <section className="menwe-card overflow-hidden rounded-[1.75rem] p-5 sm:p-7">{loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin text-[var(--accent)]"/></div>:rows.length===0?<div className="rounded-2xl border border-dashed border-[var(--ink)]/15 p-12 text-center"><p className="font-semibold">No finance records yet</p><p className="mt-1 text-sm text-[var(--ink)]/55">{teacher&&!teacherClass?"No class-teacher finance access is currently assigned.":"This is a genuine empty state. Finance records will appear here when created."}</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="border-b border-[var(--ink)]/10 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/45">{(tab==="invoices"?["Invoice","Learner","Issued","Due","Status"]:["Invoice","Learner","Amount","Method","Receipt / reference","Status","Action"]).map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=>{const s=tab==="invoices"?r.students as Row|null:(r.invoices as Row|null)?.students as Row|null;const inv=tab==="payments"?r.invoices as Row|null:null;return <tr key={text(r.id)} className="border-b border-[var(--ink)]/7"><td className="p-3 font-semibold">{text(tab==="invoices"?r.invoice_number:inv?.invoice_number)}</td><td className="p-3">{[s?.first_name,s?.middle_name,s?.last_name].filter(Boolean).join(" ")||text(s?.admission_number)}</td>{tab==="invoices"?<><td className="p-3">{text(r.issued_on)}</td><td className="p-3">{text(r.due_on)}</td><td className="p-3">{text(r.status)}</td></>:<><td className="p-3">{money(r.amount)}</td><td className="p-3">{text(r.payment_method)}</td><td className="p-3">{text(r.transaction_reference,text(r.provider_reference))}</td><td className="p-3">{text(r.status)}</td><td className="p-3">{teacher&&teacherClass?<button type="button" disabled={busy} onClick={()=>void updatePayment(text(r.id),text(r.amount,"0"),text(r.payment_method,"CASH"),text(r.transaction_reference,text(r.provider_reference)))} className="rounded-lg border px-3 py-2 text-xs font-bold">Save</button>:"—"}</td></>}</tr>})}</tbody></table></div>}</section>
 </main></PortalLayout>;
}
