import { useLocation } from "wouter";
import { BarChart3, CheckCircle2, CircleDollarSign, MessageCircle, UsersRound, WalletCards } from "lucide-react";
import PublicLayout from "@/components/PublicLayout";

const card = "rounded-2xl border border-gray-100 bg-white p-7 shadow-md transition-all duration-300 hover:-translate-y-1.5 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900";
const icon = "flex h-12 w-12 items-center justify-center rounded-xl bg-[#061229]/5 text-[#061229]";

export default function ForFamiliesPage() {
 const [,go]=useLocation();
 return <PublicLayout><section className="bg-[#F8F9FA]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#D89B28]">For families · Parent engagement hub</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-semibold leading-tight text-[#061229] sm:text-7xl">A clear partnership between home and Menwe.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Families are important partners in learning. Menwe Primary & Junior School, Kionyo, Abogeta Sub-County, Meru County, provides structured opportunities for guardians to understand progress, ask questions, participate in school life and keep communication practical.</p><button onClick={()=>go("/portal/login")} className="mt-9 rounded-full bg-[#061229] px-6 py-3.5 text-sm font-extrabold text-white">Open parent / student portal</button></div></section>
 <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-6 md:grid-cols-2"><article className={card}><div className={icon}><UsersRound size={21}/></div><h2 className="mt-6 font-serif text-3xl font-semibold text-[#061229] dark:text-white">Parent-Teacher Association</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">The PTA provides a structured channel for parent representation, school-family dialogue and practical support for learners. Termly consultative meetings create space to review priorities, discuss learner welfare, hear school updates and raise matters that benefit from collective attention.</p><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">Parents should use official school meetings and the administration office for formal concerns. The goal is a respectful partnership in which teachers bring professional learning insight and families bring knowledge of each child's needs.</p></article><article className={card}><div className={icon}><BarChart3 size={21}/></div><h2 className="mt-6 font-serif text-3xl font-semibold text-[#061229] dark:text-white">Progress tracking & academic reports</h2><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">CBC assessment looks beyond a single examination mark. Teachers gather evidence from classroom tasks, projects, practical activities, observation and other appropriate assessments, then communicate progress using competency-focused feedback.</p><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">Guardians receive academic reports and assessment information through school-approved channels. Reports help families see strengths, areas needing practice and the next learning steps rather than treating assessment as a one-off event.</p></article></div></section>
 <section className="bg-[#F8F9FA]"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-5 lg:grid-cols-3"><article className={card}><div className={icon}><CircleDollarSign size={21}/></div><h2 className="mt-5 font-serif text-2xl font-semibold text-[#061229] dark:text-white">Financial transparency</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">Menwe communicates school charges through official notices and administrative channels. Families should request the current fee structure from the school office rather than relying on forwarded or unofficial figures.</p><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">Where payment needs to be staged, guardians should discuss an agreed payment plan directly with the administration. Receipts and payment records should be retained for reconciliation.</p></article><article className={card}><div className={icon}><MessageCircle size={21}/></div><h2 className="mt-5 font-serif text-2xl font-semibold text-[#061229] dark:text-white">Communication channels</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">Families can use direct WhatsApp updates and SMS notifications where enabled by the school, alongside physical office hours for matters that require a conversation or document review.</p><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">Official contact: 0142550882. Email: Menweprimaryandjunior@gmail.com or menweprimaryschool94@gmail.com.</p></article><article className={card}><div className={icon}><WalletCards size={21}/></div><h2 className="mt-5 font-serif text-2xl font-semibold text-[#061229] dark:text-white">Practical family checklist</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{["Keep emergency contacts current.","Review academic reports each term.","Attend PTA and parent-teacher consultations where possible.","Use official channels for fee and account questions.","Encourage completion of CBC home-based projects.","Report welfare or safeguarding concerns promptly."].map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-[#D89B28]"/>{x}</li>)}</ul></article></div></div></section>
 <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="rounded-2xl bg-[#061229] p-8 text-white shadow-md"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#D89B28]">School office</p><h2 className="mt-3 font-serif text-3xl font-semibold">Menwe Primary & Junior School</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-white/70">Kionyo, Abogeta Sub-County, Meru County, Kenya · P.O. Box 19, Kionyo · Phone/WhatsApp 0142550882. The school was established in 1961 and is led by Principal Mr. Simon Muriungi Muthemba and Deputy Principal Mr. Patrick Kimathi, with 23 certified TSC & BOM educators.</p></div></section></PublicLayout>
}
