import { ImagePlus, Loader2, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { PortalLayout } from "@/components/PortalLayout";
import { isAdministrator, useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabase } from "@/lib/supabase";

type Row=Record<string,unknown>; const allowed=new Set(["image/jpeg","image/png","image/webp","image/gif"]); const maxBytes=10*1024*1024; const text=(v:unknown,fallback="—")=>v==null||v===""?fallback:String(v);
export default function GalleryManagementPage(){const {profile,user,loading}=useSchoolAuth();const [albums,setAlbums]=useState<Row[]>([]),[images,setImages]=useState<Row[]>([]),[albumId,setAlbumId]=useState(""),[file,setFile]=useState<File|null>(null),[caption,setCaption]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);const admin=!!profile&&isAdministrator(profile.role);
 const refresh=useCallback(async()=>{const db=getSupabase();const [a,i]=await Promise.all([db.from("gallery_albums").select("id,title,description,status,created_at").order("created_at",{ascending:false}),db.from("gallery_images").select("id,album_id,file_id,caption,sort_order,status,created_at,uploaded_files(filename,public_url,mime_type,byte_size)").order("created_at",{ascending:false})]);if(a.error)throw a.error;if(i.error)throw i.error;setAlbums(a.data??[]);setImages(i.data??[]);},[]);
 useEffect(()=>{if(!loading&&admin)void refresh().catch(e=>setError(e instanceof Error?e.message:"Gallery could not be loaded."));},[admin,loading,refresh]);
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!albumId||!file||!user)return;setBusy(true);setError(null);setMessage(null);try{if(!allowed.has(file.type)||file.size>maxBytes)throw new Error("Use JPEG, PNG, WebP or GIF up to 10 MB.");const ext=file.name.split(".").pop()?.toLowerCase();if(!ext)throw new Error("The image extension is missing.");const path=`gallery/${albumId}/${crypto.randomUUID()}.${ext}`;const db=getSupabase();const up=await db.storage.from("public-assets").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const pub=db.storage.from("public-assets").getPublicUrl(path).data.publicUrl;const f=await db.from("uploaded_files").insert({owner_id:user.id,storage_key:path,public_url:pub,filename:file.name,mime_type:file.type,byte_size:file.size,purpose:"gallery"}).select("id").single();if(f.error){await db.storage.from("public-assets").remove([path]);throw f.error;}const img=await db.from("gallery_images").insert({album_id:albumId,file_id:f.data.id,caption:caption.trim()||null,sort_order:0,status:"PUBLISHED"});if(img.error){await db.from("uploaded_files").delete().eq("id",f.data.id);await db.storage.from("public-assets").remove([path]);throw img.error;}setFile(null);setCaption("");setMessage("Image uploaded to the live gallery.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false);}};
 const remove=async(r:Row)=>{if(!window.confirm("Delete this gallery image and its file?"))return;setBusy(true);setError(null);try{const db=getSupabase();const f=r.uploaded_files as Row|null;const path=text(f?.public_url,"");const img=await db.from("gallery_images").delete().eq("id",text(r.id));if(img.error)throw img.error;const fileId=text(r.file_id,"");if(fileId){const fr=await db.from("uploaded_files").select("storage_key").eq("id",fileId).maybeSingle();if(fr.error)throw fr.error;if(fr.data?.storage_key)await db.storage.from("public-assets").remove([String(fr.data.storage_key)]);const dr=await db.from("uploaded_files").delete().eq("id",fileId);if(dr.error)throw dr.error;}setMessage("Gallery image removed.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Deletion failed.");}finally{setBusy(false);}};
 if(loading)return <div className="grid min-h-screen place-items-center"><Loader2 className="animate-spin"/></div>;if(!admin)return <PortalLayout role={profile?.role??"STUDENT"}><main className="mx-auto max-w-3xl p-6"><div className="menwe-card rounded-3xl p-8">Gallery management is restricted to authorised administrators.</div></main></PortalLayout>;
 return <PortalLayout role={profile.role}><main className="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8"><header className="rounded-[2rem] bg-[var(--ink)] p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--gold)]">Content administration</p><h1 className="mt-3 font-serif text-4xl font-semibold">Gallery</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Upload real school images into albums. Public visibility follows the album and image status.</p></header>{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</div>}{message&&<div className="rounded-2xl bg-[var(--sage)]/15 p-4 text-sm">{message}</div>}<section className="menwe-card rounded-3xl p-6"><form onSubmit={upload} className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Album<select required value={albumId} onChange={e=>setAlbumId(e.target.value)} className={input}><option value="">Select an album</option>{albums.map(a=><option key={text(a.id)} value={text(a.id)}>{text(a.title)} · {text(a.status)}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Image<input required type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0]??null)} className="rounded-xl border p-3"/></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">Caption<input value={caption} onChange={e=>setCaption(e.target.value)} maxLength={500} className={input}/></label><button disabled={busy} className="inline-flex min-h-11 w-fit items-center gap-2 rounded-xl bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={17}/>:<ImagePlus size={17}/>}Upload image</button></form></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.length===0?<div className="menwe-card rounded-3xl border-dashed p-8 text-sm text-[var(--ink)]/55">No gallery images have been uploaded yet.</div>:images.map(r=>{const f=r.uploaded_files as Row|null;return <article key={text(r.id)} className="menwe-card rounded-3xl p-5"><p className="font-semibold">{text(f?.filename)}</p><p className="mt-1 text-xs text-[var(--ink)]/50">Album · {text((albums.find(a=>String(a.id)===String(r.album_id)) as Row|null)?.title)}</p>{r.caption&&<p className="mt-2 text-sm text-[var(--ink)]/60">{text(r.caption)}</p>}<button disabled={busy} onClick={()=>void remove(r)} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-700"><Trash2 size={16}/>Delete</button></article>})}</section></main></PortalLayout>}
const input="min-h-11 w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm";
