import { ImagePlus, Loader2, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { PortalLayout } from "@/components/PortalLayout";
import { isAdministrator, useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabase } from "@/lib/supabase";

const allowed = new Set(["image/jpeg", "image/png", "image/webp", "image/gif"]); const maxBytes = 10 * 1024 * 1024;
type Album = { id: string; title: string; status: string };
type Image = { id: string; document_id: string; caption: string | null; storage_path: string; original_name: string };

export default function GalleryManagementPage() {
  const { profile, user, loading } = useSchoolAuth(); const [albums, setAlbums] = useState<Album[]>([]); const [images, setImages] = useState<Image[]>([]); const [albumId, setAlbumId] = useState(""); const [file, setFile] = useState<File | null>(null); const [caption, setCaption] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = async () => { const supabase = getSupabase(); const [{ data: albumRows, error: albumError }, { data: imageRows, error: imageError }] = await Promise.all([supabase.from("gallery_albums").select("id,title,status").order("created_at", { ascending: false }), supabase.from("gallery_images").select("id,document_id,caption,documents(storage_path,original_name)").order("created_at", { ascending: false })]); if (albumError) throw albumError; if (imageError) throw imageError; setAlbums((albumRows ?? []) as Album[]); setImages((imageRows ?? []).map((row: any) => ({ id: row.id, document_id: row.document_id, caption: row.caption, storage_path: row.documents?.storage_path, original_name: row.documents?.original_name })) .filter((row: Image) => row.storage_path)); };
  useEffect(() => { if (!loading && profile && isAdministrator(profile.role)) void refresh().catch(cause => setError(cause.message)); }, [loading, profile]);
  if (loading) return <div className="grid min-h-screen place-items-center"><Loader2 className="animate-spin" /></div>;
  if (!profile || !isAdministrator(profile.role)) return <PortalLayout role={profile?.role ?? "STUDENT"}><main className="mx-auto max-w-3xl p-6"><div className="menwe-card rounded-3xl p-8">Gallery management is restricted to authorised administrators.</div></main></PortalLayout>;
  const upload = async (event: React.FormEvent) => { event.preventDefault(); setError(null); setMessage(null); if (!albumId || !file) { setError("Choose an album and image."); return; } if (!allowed.has(file.type) || file.size > maxBytes) { setError("Images must be JPEG, PNG, WebP, or GIF and no larger than 10 MB."); return; } const ext = file.name.split(".").pop()?.toLowerCase(); if (!ext || !["jpg","jpeg","png","webp","gif"].includes(ext)) { setError("The file extension is not permitted."); return; } setBusy(true); const supabase = getSupabase(); const path = `gallery/${albumId}/${crypto.randomUUID()}.${ext}`; try { const { error: uploadError } = await supabase.storage.from("public-assets").upload(path, file, { contentType: file.type, upsert: false }); if (uploadError) throw uploadError; const { data: document, error: documentError } = await supabase.from("documents").insert({ category: "gallery_image", storage_path: path, original_name: file.name, mime_type: file.type, byte_size: file.size, created_by: user?.id }).select("id").single(); if (documentError) { await supabase.storage.from("public-assets").remove([path]); throw documentError; } const { error: imageError } = await supabase.from("gallery_images").insert({ album_id: albumId, document_id: document.id, caption: caption.trim() || null }); if (imageError) { await supabase.from("documents").delete().eq("id", document.id); await supabase.storage.from("public-assets").remove([path]); throw imageError; } setFile(null); setCaption(""); setMessage("Image uploaded and persisted. It is publicly visible only when its album is Published."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Upload failed."); } finally { setBusy(false); } };
  const remove = async (image: Image) => { if (!window.confirm("Delete this gallery image and its storage object?")) return; setBusy(true); setError(null); try { const supabase = getSupabase(); const { error: imageError } = await supabase.from("gallery_images").delete().eq("id", image.id); if (imageError) throw imageError; const { error: objectError } = await supabase.storage.from("public-assets").remove([image.storage_path]); if (objectError) throw objectError; const { error: documentError } = await supabase.from("documents").delete().eq("id", image.document_id); if (documentError) throw documentError; setMessage("Image and metadata deleted."); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Deletion failed."); } finally { setBusy(false); } };
  return <PortalLayout role={profile.role}><main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8"><div className="grid gap-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">Content administration</p><h1 className="mt-2 font-serif text-4xl font-semibold">Gallery</h1><p className="mt-3 text-sm text-[var(--ink)]/60">Storage enforces image MIME types and a 10 MB maximum. Public access is limited to images linked to published albums.</p></header>{error && <div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</div>}{message && <div className="rounded-2xl bg-[var(--sage)]/15 p-4 text-sm">{message}</div>}<section className="menwe-card rounded-3xl p-6"><form onSubmit={upload} className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Album<select value={albumId} onChange={event => setAlbumId(event.target.value)} className="rounded-xl border p-3"><option value="">Select an album</option>{albums.map(album => <option value={album.id} key={album.id}>{album.title} — {album.status}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={event => setFile(event.target.files?.[0] ?? null)} className="rounded-xl border p-3" /></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">Caption<input value={caption} onChange={event => setCaption(event.target.value)} className="rounded-xl border p-3" maxLength={500} /></label><button disabled={busy} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--ink)] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50"><ImagePlus size={17} />{busy ? "Saving…" : "Upload image"}</button></form></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.length === 0 ? <div className="menwe-card rounded-3xl border-dashed p-8 text-sm text-[var(--ink)]/55">No gallery images have been uploaded.</div> : images.map(image => <article className="menwe-card rounded-3xl p-5" key={image.id}><p className="font-semibold">{image.original_name}</p>{image.caption && <p className="mt-2 text-sm text-[var(--ink)]/60">{image.caption}</p>}<button disabled={busy} onClick={() => void remove(image)} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-red-200 px-3 py-2 text-sm text-red-700"><Trash2 size={16}/>Delete</button></article>)}</section></div></main></PortalLayout>;
}
