import { BookOpenCheck, Loader2, Plus } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

type Row = Record<string, unknown>;
const text=(v:unknown,fallback="")=>v==null?fallback:String(v);
const input="min-h-11 w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[var(--accent)]";
export default function HomeworkDirectory(){
 const {user,profile}=useSchoolAuth(); const [rows,setRows]=useState<Row[]>([]),[classes,setClasses]=useState<Row[]>([]),[subjects,setSubjects]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null); const [form,setForm]=useState({title:"",instructions:"",class_id:"",subject_id:"",due_at:""});
 const admin=["SUPER_ADMIN","ADMIN"].includes(profile?.role??""); const teacher=profile?.role==="TEACHER";
 const load=useCallback(async()=>{if(!user||!profile)return;setLoading(true);setMessage(null);try{const db=getSupabase();let teacherId="";if(teacher){const tr=await db.from("teachers").select("id").eq("profile_id",user.id).maybeSingle();if(tr.error)throw tr.error;if(!tr.data)throw new Error("Your teacher record is not linked yet. Ask an administrator to complete your staff profile.");teacherId=String(tr.data.id);}const assignments=teacher?await db.from("teacher_assignments").select("class_id,subject_id").eq("teacher_id",teacherId):null;if(assignments?.error)throw assignments.error;const classIds=(assignments?.data??[]).map(x=>String(x.class_id));const subjectIds=(assignments?.data??[]).map(x=>String(x.subject_id));let cq=db.from("classes").select("id,name,level,academic_year_id").eq("status","ACTIVE").order("name");let sq=db.from("subjects").select("id,code,name").eq("status","ACTIVE").order("name");if(teacher){cq=cq.in("id",classIds.length?classIds:["00000000-0000-0000-0000-000000000000"]);sq=sq.in("id",subjectIds.length?subjectIds:["00000000-0000-0000-0000-000000000000"]);}const [c,s]=await Promise.all([cq,sq]);if(c.error)throw c.error;if(s.error)throw s.error;setClasses(c.data??[]);setSubjects(s.data??[]);let q=db.from("homework").select("id,class_id,subject_id,teacher_id,title,instructions,due_at,status,created_at,classes(name,level),subjects(name,code)").order("due_at");if(teacher)q=q.eq("teacher_id",teacherId);const r=await q;if(r.error)throw r.error;setRows(r.data??[]);}catch(e){setMessage(e instanceof Error?e.message:"Homework could not be loaded.");}finally{setLoading(false);}},[profile,user,teacher]);
 useEffect(()=>{void load()},[load]);
 const canCreate=admin||teacher;
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!user||!canCreate)return;setBusy(true);setMessage(null);try{const db=getSupabase();let teacherId:string|null=null;if(teacher){const tr=await db.from("teachers").select("id").eq("profile_id",user.id).maybeSingle();if(tr.error)throw tr.error;if(!tr.data)throw new Error("Your teacher record is not linked yet.");teacherId=String(tr.data.id);const allowed=await db.from("teacher_assignments").select("id").eq("teacher_id",teacherId).eq("class_id",form.class_id).eq("subject_id",form.subject_id).maybeSingle();if(allowed.error)throw allowed.error;if(!allowed.data)throw new Error("You are not assigned to this class and subject.");}const r=await db.from("homework").insert({class_id:form.class_id,subject_id:form.subject_id,teacher_id:teacherId,title:form.title.trim(),instructions:form.instructions.trim()||null,due_at:form.due_at||null,status:"PUBLISHED"});if(r.error)throw r.error;setForm({title:"",instructions:"",class_id:"",subject_id:"",due_at:""});setMessage("Homework published to the live school system.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Homework could not be created.");}finally{setBusy(false);}};
 return <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><h1 className="font-serif text-3xl font-semibold">Homework</h1><p className="mt-2 text-sm leading-6 text-[var(--ink)]/60">Real assignments use authorised class, subject and teacher relationships.</p></div><BookOpenCheck className="text-[var(--accent)]" size={24}/></div>{canCreate&&<form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl border border-[var(--ink)]/10 p-4 md:grid-cols-2"><input required placeholder="Assignment title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={input}/><select required value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})} className={input}><option value="">Select class</option>{classes.map(c=><option key={text(c.id)} value={text(c.id)}>{text(c.name)} · {text(c.level)}</option>)}</select><select required value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})} className={input}><option value="">Select subject</option>{subjects.map(s=><option key={text(s.id)} value={text(s.id)}>{text(s.name)} ({text(s.code)})</option>)}</select><input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})} className={input}/><textarea placeholder="Instructions" value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} className={`${input} min-h-24 md:col-span-2`}/><button disabled={busy||!classes.length||!subjects.length} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 text-sm font-bold text-white md:w-max disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={16}/>:<Plus size={16}/>}Publish homework</button></form>}{loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin"/></div>:rows.length===0?<p className="mt-6 rounded-2xl border border-dashed border-[var(--ink)]/15 px-5 py-10 text-center text-sm text-[var(--ink)]/55">{teacher&&!classes.length?"No teaching assignments have been granted yet. An administrator must assign your class and subject before you can publish homework.":"No authorised homework is available yet."}</p>:<div className="mt-6 grid gap-3">{rows.map(r=><article key={text(r.id)} className="rounded-2xl border border-[var(--ink)]/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{text(r.title)}</h2><p className="mt-1 text-sm text-[var(--ink)]/60">{text((r.subjects as Row|null)?.name)} · {text((r.classes as Row|null)?.name)}</p></div><span className="text-sm font-semibold">{r.due_at?`Due ${text(r.due_at)}`:"No due date"}</span></div>{r.instructions&&<p className="mt-3 text-sm leading-6 text-[var(--ink)]/70">{text(r.instructions)}</p>}</article>)}</div>}{message&&<p role="status" className="mt-5 rounded-xl bg-[var(--sage)]/15 px-4 py-3 text-sm">{message}</p>}</section>;
}
