import { useLocation } from "wouter";
import { BarChart3, Beaker, CheckCircle2, Home, Palette, Trophy } from "lucide-react";
import PublicLayout from "@/components/PublicLayout";

const card="rounded-2xl border border-gray-100 bg-white p-7 shadow-md transition-all duration-300 hover:-translate-y-1.5 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900";
const icon="flex h-12 w-12 items-center justify-center rounded-xl bg-[#061229]/5 text-[#061229]";

export default function HowItWorksPage(){const [,go]=useLocation();return <PublicLayout>
<section className="bg-[#061229] text-white"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#D89B28]">How it works · CBC at Menwe</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-semibold leading-tight sm:text-7xl">Competency-Based Curriculum with purpose, evidence and partnership.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/70">At Menwe Primary & Junior School, the CBC framework supports learning across PP1–PP2, Grades 1–6 and JSS Grades 7–9. The emphasis is on knowledge, skills, values, attitudes, practical application and continuous growth.</p></div></section>
<section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["01","Plan","Teachers organise learning around curriculum outcomes, learner needs, practical activities and age-appropriate experiences."],["02","Teach & practise","Classroom instruction is combined with discussion, demonstration, projects, collaboration, creativity and guided practice."],["03","Assess","Evidence is collected during learning and at appropriate end points so teachers can identify strengths and support needs."],["04","Respond","Feedback informs remediation, enrichment, family engagement and the next cycle of teaching and learning."]].map(([n,t,d])=><article className={card} key={n}><span className="text-xs font-extrabold text-[#D89B28]">{n}</span><h2 className="mt-10 font-serif text-2xl font-semibold text-[#061229] dark:text-white">{t}</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{d}</p></article>)}</div></section>
<section className="bg-[#F8F9FA]"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#D89B28]">Assessment</p><h2 className="mt-3 font-serif text-4xl font-semibold text-[#061229]">Formative and summative assessment work together.</h2><p className="mt-5 text-base leading-8 text-slate-600">Formative assessment happens during learning. It can include observation, questions, classwork, practical tasks, projects, oral responses and other evidence that helps a teacher adjust instruction. Summative assessment reviews achievement at a defined point, such as the end of a learning period, and contributes to formal reporting.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["Exceeding Expectation","The learner demonstrates the competency confidently and independently, often applying it in new or more complex situations."],["Meeting Expectation","The learner demonstrates the expected competency with appropriate consistency and understanding."],["Approaching Expectation","The learner is developing the competency and benefits from additional practice, modelling or targeted support."],["Below Expectation","The learner needs focused intervention and further opportunities to build the required knowledge or skill."]].map(([t,d])=><article className={card} key={t}><div className={icon}><BarChart3 size={21}/></div><h3 className="mt-5 font-serif text-xl font-semibold text-[#061229] dark:text-white">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{d}</p></article>)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#D89B28]">JSS pathways · Grades 7–9</p><h2 className="mt-3 max-w-3xl font-serif text-4xl font-semibold text-[#061229]">Broad pathways help learners explore future strengths.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[[Beaker,"STEM","Science, technology, engineering and mathematics experiences develop inquiry, experimentation, numeracy, digital literacy and problem-solving."],[Home,"Social Sciences","Learners investigate people, society, language, history, geography, citizenship and the relationships that shape communities."],[Palette,"Arts & Sports","Creative arts, performance and sport develop expression, physical fitness, teamwork, discipline and talent discovery."]].map(([I,t,d])=>{const C=I as typeof Beaker;return <article className={card} key={String(t)}><div className={icon}><C size={21}/></div><h3 className="mt-6 font-serif text-2xl font-semibold text-[#061229] dark:text-white">{String(t)}</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{String(d)}</p></article>})}</div><p className="mt-7 text-sm leading-7 text-slate-600">Menwe's JSS provision includes Science and Computer Labs to support practical and digital learning within the school's CBC programme.</p></section>
<section className="bg-[#061229] text-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#D89B28]">Parents at home</p><h2 className="mt-3 font-serif text-4xl font-semibold">Home-based projects are part of the learning partnership.</h2></div><div className="text-sm leading-8 text-white/70"><p>Parents and guardians can support CBC by helping learners plan, ask questions, gather safe materials, practise skills and reflect on what they discover. The adult's role is to guide rather than complete the learner's work.</p><p className="mt-4">Where a project requires resources, families should use affordable, safe and locally available materials. Learners can document observations, steps, challenges and conclusions so teachers can discuss the process at school.</p><p className="mt-4">Menwe's 23 certified TSC & BOM educators can use this evidence alongside classroom work to understand progress. Families can ask teachers for clarification through the school's official communication channels.</p><button onClick={()=>go("/families")} className="mt-7 rounded-full bg-[#D89B28] px-6 py-3.5 font-extrabold text-[#061229]">Family engagement hub</button></div></div></div></section>
</PublicLayout>}
