import { useEffect, useState } from "react";
import { CheckCircle2, Download, ShieldCheck, Utensils } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

type Row={learner_id:string;admission_number:string|null;learner_name:string;maize:number;beans:number;sorghum:number;millet:number;rice_paid:number;rice_expected:number;rice_balance:number};
export default function LearnerFoodPage(){
 const {profile}=useSchoolAuth();const[row,setRow]=useState<Row|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{let cancelled=false;(async()=>{if(!profile?.id)return;const{data,error:e}=await getSupabase().rpc("get_my_food_accountability");if(cancelled)return;if(e||!data?.[0])setError(e?.message||"Your learner food record is not linked to this account yet.");else setRow(data[0] as Row);setLoading(false)})();return()=>{cancelled=true}},[profile?.id]);
 const download=async()=>{const{data,error:e}=await getSupabase().rpc("get_my_food_accountability_csv");if(e){setError(e.message);return}const blob=new Blob([data||""],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="my-menwe-food-record.csv";a.click();URL.revokeObjectURL(url)};
 if(loading)return <main className="mx-auto max-w-4xl px-4 py-12 text-center text-sm text-slate-500">Loading your food record…</main>;
 return <main className="mx-auto max-w-4xl px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><Utensils size={23}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D89B28]">My school record</p><h1 className="text-2xl font-black text-[#061229] sm:text-3xl">My food & rice record</h1><p className="mt-1 text-sm text-slate-500">View your own recorded food contributions and rice payment balance.</p></div></div>{row&&<button onClick={()=>void download()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#061229] px-4 py-2.5 text-sm font-bold text-white"><Download size={17}/> Download my record</button>}</div>{error?<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">{error}</div>:row&&<><div className="mt-6 rounded-2xl border border-gray-100 bg-white p-6 shadow-md"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Learner</p><h2 className="mt-1 text-xl font-black text-[#061229]">{row.learner_name}</h2><p className="mt-1 text-sm text-slate-500">Admission No. {row.admission_number||"—"}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Maize",row.maize],["Beans",row.beans],["Sorghum",row.sorghum],["Millet",row.millet]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-md"><p className="text-xs font-bold uppercase tracking-wider text-[#D89B28]">{label}</p><p className="mt-2 text-2xl font-black text-[#061229]">{Number(value).toLocaleString()} kg</p></div>)}</div><div className="mt-5 rounded-2xl border border-gray-100 bg-white p-6 shadow-md"><div className="flex items-center gap-3"><CheckCircle2 className={Number(row.rice_balance)>0?"text-amber-600":"text-emerald-600"} size={22}/><div><h2 className="font-black text-[#061229]">Rice payment</h2><p className="text-xs text-slate-500">Expected: KSh {Number(row.rice_expected).toLocaleString()}</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Paid</p><p className="text-xl font-black">KSh {Number(row.rice_paid).toLocaleString()}</p></div><div><p className="text-xs text-slate-400">Balance</p><p className="text-xl font-black">KSh {Number(row.rice_balance).toLocaleString()}</p></div><div><p className="text-xs text-slate-400">Status</p><p className="text-xl font-black">{Number(row.rice_balance)>0?"Balance due":"Paid"}</p></div></div></div><div className="mt-5 flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs text-slate-500"><ShieldCheck size={17} className="shrink-0"/> You can only view your own learner food record. Other learners cannot access your payment or contribution data.</div></>}</main>;
}
