import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, CheckCircle2, ClipboardList, Download, LibraryBig, Plus, Printer, RotateCcw, Search, TriangleAlert, Users } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { isAdministrator, useSchoolAuth, type AppRole } from "@/contexts/SupabaseAuthContext";

type Book = { id:string; accession_number:string; isbn:string|null; title:string; author:string|null; category:string; shelf_location:string|null; total_copies:number; available_copies:number; status:string; school_code?:string|null; lost_copies?:number; damaged_copies?:number; condition?:string; replacement_cost?:number };
type Loan = { id:string; book_id:string; student_id:string; issued_at:string; due_at:string; returned_at:string|null; fine_amount:number; issue_date?:string|null; return_date?:string|null; status?:string; replacement_required?:boolean; replacement_received?:boolean; book?:{title:string;accession_number:string;school_code?:string|null}|null; student?:{first_name:string;last_name:string;admission_number:string}|null };
type Student = { id:string; first_name:string; last_name:string; admission_number:string };
const staffRoles=["SUPER_ADMIN","ADMIN","HEAD_OF_INSTITUTION","DEPUTY_HOI","TEACHER"];
const adminRoles=["SUPER_ADMIN","ADMIN","HEAD_OF_INSTITUTION","DEPUTY_HOI"];
const today=()=>new Date().toISOString().slice(0,10);

export default function LibraryPage(){
 const {profile}=useSchoolAuth(); const role=profile?.role as AppRole|undefined; const admin=isAdministrator(role as any); const staff=!!role&&staffRoles.includes(role); const canManage=!!role&&adminRoles.includes(role);
 const [tab,setTab]=useState<"catalogue"|"loans"|"learners"|"replacements"|"register">("catalogue");
 const [books,setBooks]=useState<Book[]>([]); const [loans,setLoans]=useState<Loan[]>([]); const [students,setStudents]=useState<Student[]>([]); const [q,setQ]=useState(""); const [learnerQ,setLearnerQ]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 const [showAdd,setShowAdd]=useState(false); const [checkout,setCheckout]=useState<Book|null>(null); const [studentId,setStudentId]=useState(""); const [issueDate,setIssueDate]=useState(today()); const [returnDate,setReturnDate]=useState("");
 const [form,setForm]=useState({accession_number:"",school_code:"",title:"",author:"",isbn:"",category:"Textbook",shelf_location:"",total_copies:1});
 const load=async()=>{setLoading(true);setError("");const s=getSupabase();const [b,l,st]=await Promise.all([s.from("library_books").select("*").order("title"),s.from("library_loans").select("id,book_id,student_id,issued_at,due_at,returned_at,fine_amount,issue_date,return_date,status,replacement_required,replacement_received,book:library_books(title,accession_number,school_code),student:students(first_name,last_name,admission_number)").order("issued_at",{ascending:false}),staff?s.from("students").select("id,first_name,last_name,admission_number").is("deleted_at",null).order("first_name"):Promise.resolve({data:[] as Student[],error:null})]);const e=b.error||l.error||st.error;if(e)setError(e.message);else{setBooks((b.data||[]) as Book[]);setLoans((l.data||[]) as unknown as Loan[]);setStudents((st.data||[]) as Student[])}setLoading(false)};
 useEffect(()=>{void load()},[staff]);
 const filtered=useMemo(()=>books.filter(b=>`${b.title} ${b.author||""} ${b.accession_number} ${b.school_code||""} ${b.category}`.toLowerCase().includes(q.toLowerCase())),[books,q]);
 const active=loans.filter(l=>!l.returned_at&&l.status!=="RETURNED"&&l.status!=="LOST"&&l.status!=="REPLACED"); const overdue=active.filter(l=>(l.return_date||l.due_at?.slice(0,10))<today()); const lost=loans.filter(l=>l.status==="LOST"&&l.replacement_required&&!l.replacement_received); const total=books.reduce((n,b)=>n+Number(b.total_copies||0),0); const available=books.reduce((n,b)=>n+Number(b.available_copies||0),0);
 const learnerRows=useMemo(()=>students.map(student=>{const history=loans.filter(l=>l.student_id===student.id);const current=history.filter(l=>!l.returned_at&&l.status!=="RETURNED"&&l.status!=="LOST"&&l.status!=="REPLACED");const late=current.filter(l=>(l.return_date||l.due_at?.slice(0,10))<today()).length;const lostCount=history.filter(l=>l.status==="LOST").length;return{student,history,current,late,lostCount}}).filter(r=>`${r.student.first_name} ${r.student.last_name} ${r.student.admission_number}`.toLowerCase().includes(learnerQ.toLowerCase())),[students,loans,learnerQ]);
 const downloadRegister=()=>{const rows=learnerRows.map(r=>[`${r.student.first_name} ${r.student.last_name}`,r.student.admission_number,r.current.length,r.history.length,r.late,r.lostCount,r.current.length?"TEXTBOOKS ISSUED":"NO TEXTBOOKS ISSUED"]);const csv=[["Learner","Admission No.","Current Books","Loan Records","Overdue","Lost","Status"],...rows].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`library-learner-register-${today()}.csv`;a.click();URL.revokeObjectURL(url)};
 const addBook=async()=>{if(!form.title.trim()||!form.accession_number.trim())return;setSaving(true);setError("");const copies=Math.max(1,Number(form.total_copies));const {error:e}=await getSupabase().from("library_books").insert({...form,author:form.author||null,isbn:form.isbn||null,shelf_location:form.shelf_location||null,total_copies:copies,available_copies:copies,lost_copies:0,damaged_copies:0,condition:"GOOD",status:"AVAILABLE",created_by:profile?.id});if(e)setError(e.message);else{setShowAdd(false);setMessage("Textbook added to the school catalogue.");await load()}setSaving(false)};
 const issue=async()=>{if(!checkout||!studentId||!returnDate)return;if(returnDate<issueDate){setError("Return date cannot be before the issue date.");return}setSaving(true);setError("");const {error:e}=await getSupabase().rpc("library_checkout_book",{p_book_id:checkout.id,p_student_id:studentId,p_due_at:new Date(`${returnDate}T23:59:59`).toISOString(),p_notes:null,p_issue_date:issueDate});if(e)setError(e.message);else{setCheckout(null);setStudentId("");setReturnDate("");setIssueDate(today());setMessage(`Issued “${checkout.title}” to the learner.`);await load()}setSaving(false)};
 const returned=async(l:Loan)=>{if(!confirm("Confirm that this textbook has been returned?"))return;setSaving(true);const {error:e}=await getSupabase().rpc("library_return_book",{p_loan_id:l.id,p_fine_amount:0});if(e)setError(e.message);else{setMessage("Textbook returned and stock updated.");await load()}setSaving(false)};
 const markLost=async(l:Loan)=>{if(!confirm("Mark this textbook as LOST? It will enter the BUY NEW replacement register."))return;setSaving(true);const {error:e}=await getSupabase().rpc("library_mark_lost",{p_loan_id:l.id,p_notes:"Lost textbook; new replacement required."});if(e)setError(e.message);else{setMessage("Lost textbook recorded for replacement.");await load()}setSaving(false)};
 const replacementReceived=async(l:Loan)=>{if(!confirm("Confirm the new replacement copy has been received?"))return;setSaving(true);const {error:e}=await getSupabase().rpc("library_receive_replacement",{p_loan_id:l.id,p_notes:"Replacement copy received by school."});if(e)setError(e.message);else{setMessage("Replacement received and stock restored.");await load()}setSaving(false)};
 return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 print:max-w-none print:px-2">
  <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between print:hidden"><div><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><LibraryBig size={23}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D89B28]">School library</p><h1 className="text-2xl font-black tracking-tight text-[#061229] sm:text-3xl">Textbook control centre</h1></div></div><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Complete learner accountability, textbook circulation, overdue follow-up, lost books, replacements and stock control.</p></div>{admin&&<button onClick={()=>setShowAdd(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#061229] px-4 text-sm font-bold text-white shadow-md"><Plus size={17}/>Add textbook</button>}</header>
  {message&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800 print:hidden">{message}</div>}{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 print:hidden">{error}</div>}
  <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6 print:hidden"><Stat icon={BookOpen} label="Titles" value={books.length}/><Stat icon={CheckCircle2} label="Available" value={available}/><Stat icon={ClipboardList} label="Issued" value={active.length}/><Stat icon={CalendarDays} label="Overdue" value={overdue.length}/><Stat icon={TriangleAlert} label="Lost / replace" value={lost.length}/><Stat icon={Users} label="Active learners" value={students.length}/></div>
  <nav className="mt-6 flex flex-wrap gap-2 print:hidden">{([["catalogue","Catalogue"],["loans","Issue & return"],["learners","Learner register"],["replacements","Replacement register"],["register","Stock summary"]] as const).map(([k,label])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${tab===k?"bg-[#061229] text-white shadow":"border border-slate-200 bg-white text-slate-600 hover:border-[#D89B28]"}`}>{label}</button>)}</nav>
  {loading?<div className="py-16 text-center text-sm text-slate-500">Loading library…</div>:tab==="learners"?<section className="mt-5" id="library-learner-register"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black text-[#061229]">All active learners</h2><p className="text-sm text-slate-500">Every active learner is shown, including learners with zero textbook records.</p></div><div className="flex gap-2 print:hidden"><button onClick={downloadRegister} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-[#061229]"><Download size={16}/>Download</button><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl bg-[#061229] px-4 py-2.5 text-sm font-bold text-white"><Printer size={16}/>Print</button></div></div><div className="relative mt-4 print:hidden"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={learnerQ} onChange={e=>setLearnerQ(e.target.value)} placeholder="Search learner name or admission number…" className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-4 text-sm outline-none focus:border-[#D89B28]"/></div><div className="mt-4 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-md"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-[#061229] text-xs uppercase tracking-wider text-white"><tr><th className="px-4 py-3">Learner</th><th className="px-4 py-3">Admission No.</th><th className="px-4 py-3">Current books</th><th className="px-4 py-3">Loan records</th><th className="px-4 py-3">Overdue</th><th className="px-4 py-3">Lost</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{learnerRows.map(r=><tr key={r.student.id} className="border-t border-slate-100"><td className="px-4 py-3 font-bold text-[#061229]">{r.student.first_name} {r.student.last_name}</td><td className="px-4 py-3">{r.student.admission_number}</td><td className="px-4 py-3 font-bold">{r.current.length}</td><td className="px-4 py-3">{r.history.length}</td><td className="px-4 py-3 font-bold text-red-600">{r.late}</td><td className="px-4 py-3 font-bold text-red-600">{r.lostCount}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.current.length?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"}`}>{r.current.length?"TEXTBOOKS ISSUED":"NO TEXTBOOKS ISSUED"}</span></td></tr>)}{learnerRows.length===0&&<tr><td colSpan={7} className="p-10 text-center text-sm text-slate-500">No learners match your search.</td></tr>}</tbody></table></div></div></section>:<>
   {tab!=="register"&&<div className="relative mt-4 print:hidden"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search book name, school code, author or category…" className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-10 pr-4 text-sm outline-none focus:border-[#D89B28]"/></div>}
   {tab==="catalogue"&&<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(b=><article key={b.id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-md transition-all duration-300 hover:-translate-y-1.5 hover:shadow-xl"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-[#D89B28]/10 px-3 py-1 text-xs font-bold uppercase text-[#D89B28]">{b.category}</span><span className={`text-xs font-bold ${b.available_copies>0?"text-emerald-600":"text-red-600"}`}>{b.available_copies}/{b.total_copies} available</span></div><h2 className="mt-4 text-lg font-black text-[#061229]">{b.title}</h2><p className="mt-1 text-sm text-slate-500">{b.author||"Author not recorded"}</p><div className="mt-4 grid gap-1 text-xs text-slate-500"><p>School code: <b className="text-slate-700">{b.school_code||"—"}</b></p><p>Accession: <b className="text-slate-700">{b.accession_number}</b></p>{b.shelf_location&&<p>Shelf: {b.shelf_location}</p>}{Number(b.lost_copies||0)>0&&<p className="font-bold text-red-600">Lost copies: {b.lost_copies}</p>}</div>{staff&&<button disabled={b.available_copies<1||b.status!=="AVAILABLE"} onClick={()=>{setCheckout(b);setIssueDate(today())}} className="mt-5 min-h-10 w-full rounded-xl bg-[#061229] text-sm font-bold text-white disabled:opacity-40">Issue to learner</button>}</article>)}</div>}
   {tab==="loans"&&<div className="mt-5 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-md overflow-x-auto"><table className="min-w-[980px] w-full text-left text-sm"><thead className="bg-[#061229] text-xs uppercase tracking-wider text-white"><tr><th className="px-4 py-3">Textbook</th><th className="px-4 py-3">Learner</th><th className="px-4 py-3">Issue date</th><th className="px-4 py-3">Return date</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{active.map(l=>{const late=(l.return_date||l.due_at?.slice(0,10))<today();return <tr key={l.id} className="border-t border-slate-100"><td className="px-4 py-4 font-bold">{l.book?.title}<div className="text-xs font-normal text-slate-400">{l.book?.school_code||l.book?.accession_number}</div></td><td className="px-4 py-4">{l.student?.first_name} {l.student?.last_name}<div className="text-xs text-slate-400">{l.student?.admission_number}</div></td><td className="px-4 py-4">{l.issue_date||l.issued_at?.slice(0,10)}</td><td className="px-4 py-4">{l.return_date||l.due_at?.slice(0,10)}</td><td className={`px-4 py-4 font-bold ${late?"text-red-600":"text-emerald-600"}`}>{late?"OVERDUE":"ISSUED"}</td><td className="px-4 py-4 flex gap-2"><button disabled={saving} onClick={()=>void returned(l)} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-bold text-emerald-700"><RotateCcw size={14} className="mr-1 inline"/>Returned</button><button disabled={saving} onClick={()=>void markLost(l)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700"><TriangleAlert size={14} className="mr-1 inline"/>Lost</button></td></tr>})}</tbody></table>{active.length===0&&<div className="p-10 text-center text-sm text-slate-500">No active textbook issues.</div>}</div>}
   {tab==="replacements"&&<div className="mt-5 grid gap-4">{lost.map(l=><article key={l.id} className="rounded-2xl border border-red-100 bg-white p-5 shadow-md"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold uppercase text-red-700">BUY NEW</span><h2 className="mt-3 font-black text-[#061229]">{l.book?.title}</h2><p className="mt-1 text-sm text-slate-600">Learner: {l.student?.first_name} {l.student?.last_name} · {l.student?.admission_number}</p><p className="mt-1 text-xs text-slate-500">School code: {l.book?.school_code||l.book?.accession_number}</p></div>{canManage&&<button disabled={saving} onClick={()=>void replacementReceived(l)} className="rounded-xl bg-[#D89B28] px-4 py-2.5 text-sm font-bold text-[#061229]">Replacement received</button>}</div></article>)}{lost.length===0&&<div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">No textbooks awaiting replacement.</div>}</div>}
   {tab==="register"&&<div className="mt-5 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-md overflow-x-auto"><table className="min-w-[780px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Book</th><th className="px-4 py-3">School code</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Available</th><th className="px-4 py-3">Lost</th><th className="px-4 py-3">Damaged</th><th className="px-4 py-3">Need to buy</th></tr></thead><tbody>{books.map(b=><tr key={b.id} className="border-t border-slate-100"><td className="px-4 py-3 font-bold">{b.title}</td><td className="px-4 py-3">{b.school_code||b.accession_number}</td><td className="px-4 py-3">{b.total_copies}</td><td className="px-4 py-3 font-bold text-emerald-600">{b.available_copies}</td><td className="px-4 py-3 font-bold text-red-600">{b.lost_copies||0}</td><td className="px-4 py-3 font-bold text-amber-600">{b.damaged_copies||0}</td><td className="px-4 py-3 font-bold text-[#D89B28]">{b.lost_copies||0}</td></tr>)}</tbody></table></div>}
  </>}
  {showAdd&&<Modal title="Add textbook to school register" onClose={()=>setShowAdd(false)}><div className="grid gap-3 sm:grid-cols-2">{([['title','Book name'],['school_code','School book code'],['accession_number','Accession number'],['author','Author'],['isbn','ISBN'],['category','Category'],['shelf_location','Shelf location']] as const).map(([k,label])=><label key={k} className="text-xs font-bold text-slate-600">{label}<input value={(form as any)[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal"/></label>)}<label className="text-xs font-bold text-slate-600">Number of copies<input type="number" min={1} value={form.total_copies} onChange={e=>setForm(f=>({...f,total_copies:Math.max(1,Number(e.target.value))}))} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label></div><button onClick={()=>void addBook()} disabled={saving||!form.title||!form.accession_number} className="mt-5 min-h-11 w-full rounded-xl bg-[#061229] text-sm font-bold text-white disabled:opacity-40">{saving?"Saving…":"Save textbook"}</button></Modal>}
  {checkout&&<Modal title="Issue textbook to learner" onClose={()=>setCheckout(null)}><div className="rounded-xl bg-slate-50 p-3 text-sm"><b>{checkout.title}</b><div className="text-xs text-slate-500">School code: {checkout.school_code||checkout.accession_number}</div></div><label className="mt-4 block text-xs font-bold text-slate-600">Learner<select value={studentId} onChange={e=>setStudentId(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Select learner</option>{students.map(s=><option key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.admission_number}</option>)}</select></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Issue date<input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-xs font-bold text-slate-600">Return date<input type="date" min={issueDate} value={returnDate} onChange={e=>setReturnDate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3"/></label></div><button onClick={()=>void issue()} disabled={saving||!studentId||!returnDate} className="mt-5 min-h-11 w-full rounded-xl bg-[#061229] text-sm font-bold text-white disabled:opacity-40">{saving?"Issuing…":"Issue textbook"}</button></Modal>}
 </main>;
}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:number}){return <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-md transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><Icon size={18}/></span><span className="text-2xl font-black text-[#061229]">{value}</span></div><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-[#061229]/55 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-black text-[#061229]">{title}</h2><button onClick={onClose} className="rounded-lg px-3 py-2 text-sm font-bold text-slate-500">Close</button></div><div className="mt-4">{children}</div></div></div>}
