import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, CheckCircle2, ClipboardList, Download, Search, TriangleAlert, UserRound } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

const supabase = getSupabase();
type Book = { id:string; title:string; author:string|null; school_code:string|null; category:string; shelf_location:string|null; total_copies:number; available_copies:number; lost_copies:number; damaged_copies:number; condition:string; status:string };
type Loan = { id:string; book_id:string; student_id:string; issue_date:string|null; return_date:string|null; returned_at:string|null; status:string; replacement_required:boolean; replacement_received:boolean; fine_amount:number; students?:{first_name:string;last_name:string;admission_number:string}|null; library_books?:{title:string;school_code:string|null}|null };

const isAdmin=(role:string)=>["SUPER_ADMIN","ADMIN","HEAD_OF_INSTITUTION","DEPUTY_HOI"].includes(role);
const isStaff=(role:string)=>isAdmin(role)||role==="TEACHER";
const today=()=>new Date().toISOString().slice(0,10);

export default function LibraryDirectory(){
 const {profile}=useSchoolAuth(); const role=String(profile?.role||""); const canManage=isStaff(role); const canAdmin=isAdmin(role);
 const [tab,setTab]=useState<"catalogue"|"issues"|"replacements">("catalogue"); const [books,setBooks]=useState<Book[]>([]); const [loans,setLoans]=useState<Loan[]>([]); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [showBook,setShowBook]=useState(false); const [showIssue,setShowIssue]=useState(false); const [message,setMessage]=useState("");
 const [book,setBook]=useState({title:"",author:"",school_code:"",category:"Textbook",shelf_location:"",total_copies:1}); const [issue,setIssue]=useState({book_id:"",student_id:"",issue_date:today(),return_date:""});
 const [students,setStudents]=useState<{id:string;first_name:string;last_name:string;admission_number:string}[]>([]);
 const load=async()=>{setLoading(true);setError(""); const [b,l,s]=await Promise.all([supabase.from("library_books").select("id,title,author,school_code,category,shelf_location,total_copies,available_copies,lost_copies,damaged_copies,condition,status").order("title"),supabase.from("library_loans").select("id,book_id,student_id,issue_date,return_date,returned_at,status,replacement_required,replacement_received,fine_amount,students(first_name,last_name,admission_number),library_books(title,school_code)").order("return_date",{ascending:true}),canManage?supabase.from("students").select("id,first_name,last_name,admission_number").order("first_name"):Promise.resolve({data:[],error:null})]); if(b.error||l.error||s.error)setError((b.error||l.error||s.error)?.message||"Could not load library"); setBooks((b.data||[]) as Book[]); setLoans((l.data||[]) as unknown as Loan[]); setStudents((s.data||[]) as any[]); setLoading(false);};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>books.filter(b=>[b.title,b.author,b.school_code,b.category,b.shelf_location].join(" ").toLowerCase().includes(search.toLowerCase())),[books,search]);
 const active=loans.filter(l=>!l.returned_at&&["ISSUED","OVERDUE","LOST"].includes(l.status)); const overdue=active.filter(l=>l.return_date&&l.return_date<today()&&l.status!=="LOST"); const lost=loans.filter(l=>l.status==="LOST"||l.replacement_required); const available=books.reduce((n,b)=>n+Number(b.available_copies||0),0); const total=books.reduce((n,b)=>n+Number(b.total_copies||0),0);
 const addBook=async(e:any)=>{e.preventDefault(); setMessage(""); const total=Math.max(1,Number(book.total_copies)); const {error}=await supabase.from("library_books").insert({...book,total_copies:total,available_copies:total,created_by:profile?.id}); if(error){setError(error.message);return;} setShowBook(false);setBook({title:"",author:"",school_code:"",category:"Textbook",shelf_location:"",total_copies:1});setMessage("Book added to catalogue.");await load();};
 const issueBook=async(e:any)=>{e.preventDefault(); const b=books.find(x=>x.id===issue.book_id); if(!b||b.available_copies<1){setError("That book has no available copies.");return;} const {error}=await supabase.from("library_loans").insert({book_id:issue.book_id,student_id:issue.student_id,issued_by:profile?.id,issue_date:issue.issue_date,return_date:issue.return_date,issued_at:`${issue.issue_date}T00:00:00`,due_at:`${issue.return_date}T23:59:59`,status:"ISSUED"}); if(error){setError(error.message);return;} await supabase.from("library_books").update({available_copies:b.available_copies-1,updated_at:new Date().toISOString()}).eq("id",b.id); setShowIssue(false);setIssue({book_id:"",student_id:"",issue_date:today(),return_date:""});setMessage("Textbook issued successfully.");await load();};
 const returnBook=async(l:Loan,lostBook=false)=>{const b=books.find(x=>x.id===l.book_id); const status=lostBook?"LOST":"RETURNED"; const patch:any={returned_at:new Date().toISOString(),returned_by:profile?.id,status,replacement_required:lostBook}; const {error}=await supabase.from("library_loans").update(patch).eq("id",l.id); if(error){setError(error.message);return;} if(b&&!lostBook) await supabase.from("library_books").update({available_copies:Math.min(b.total_copies,b.available_copies+1),updated_at:new Date().toISOString()}).eq("id",b.id); if(b&&lostBook) await supabase.from("library_books").update({lost_copies:Number(b.lost_copies||0)+1,updated_at:new Date().toISOString()}).eq("id",b.id); if(lostBook) await supabase.from("library_replacement_records").insert({loan_id:l.id,book_id:l.book_id,learner_id:l.student_id,replacement_type:"BUY_NEW",expected_cost:0,notes:"Lost textbook — replacement required."}); setMessage(lostBook?"Marked lost. Replacement required — add the new copy when purchased.":"Book returned and stock updated.");await load();};
 const replaceBook=async(l:Loan)=>{const b=books.find(x=>x.id===l.book_id); if(!b)return; await supabase.from("library_loans").update({status:"REPLACED",replacement_received:true}).eq("id",l.id); await supabase.from("library_books").update({total_copies:b.total_copies+1,available_copies:b.available_copies+1,lost_copies:Math.max(0,Number(b.lost_copies||0)-1),updated_at:new Date().toISOString()}).eq("id",b.id); await supabase.from("library_replacement_records").update({resolved_at:new Date().toISOString(),resolved_by:profile?.id}).eq("loan_id",l.id).is("resolved_at",null); setMessage("Replacement recorded and stock restored.");await load();};
 if(loading)return <div className="grid min-h-[60vh] place-items-center text-sm text-[var(--ink)]/60">Loading library…</div>;
 return <main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[var(--gold)]">Menwe Library</p><h1 className="mt-1 text-3xl font-black tracking-tight text-[var(--ink)]">Textbook & library control</h1><p className="mt-2 max-w-2xl text-sm text-[var(--ink)]/60">Know exactly which learner has which textbook, when it was issued, when it is due, and which lost books need replacement.</p></div>{canManage&&<div className="flex gap-2"><button onClick={()=>setShowIssue(true)} className="rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-bold text-white">Issue textbook</button>{canAdmin&&<button onClick={()=>setShowBook(true)} className="rounded-xl bg-[var(--gold)] px-4 py-2.5 text-sm font-bold text-[var(--ink)]">Add book</button>}</div>}</div>
 {message&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{message}</div>}{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Total titles",books.length,BookOpen],["Copies in stock",available,CheckCircle2],["Issued",active.length,ClipboardList],["Overdue",overdue.length,TriangleAlert],["Lost / replace",lost.length,TriangleAlert]].map(([label,value,Icon]:any)=><div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-md"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--ink)]/5 text-[var(--ink)]"><Icon size={18}/></span><span className="text-2xl font-black text-[var(--ink)]">{value}</span></div><p className="mt-3 text-xs font-bold uppercase tracking-wider text-[var(--ink)]/50">{label}</p></div>)}</div>
 <div className="mt-7 flex flex-wrap gap-2"><button onClick={()=>setTab("catalogue")} className={`rounded-full px-4 py-2 text-sm font-bold ${tab==="catalogue"?"bg-[var(--ink)] text-white":"bg-white text-[var(--ink)]/60"}`}>Catalogue</button><button onClick={()=>setTab("issues")} className={`rounded-full px-4 py-2 text-sm font-bold ${tab==="issues"?"bg-[var(--ink)] text-white":"bg-white text-[var(--ink)]/60"}`}>Issue & return</button><button onClick={()=>setTab("replacements")} className={`rounded-full px-4 py-2 text-sm font-bold ${tab==="replacements"?"bg-[var(--ink)] text-white":"bg-white text-[var(--ink)]/60"}`}>Replacement register</button></div>
 {tab==="catalogue"&&<><div className="mt-4 flex items-center gap-2 rounded-2xl border border-gray-100 bg-white px-4 py-3 shadow-sm"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search book name, school code, author or shelf…" className="w-full bg-transparent text-sm outline-none"/></div><div className="mt-4 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-md"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[var(--ink)] text-white"><tr><th className="px-4 py-3">Book</th><th>School code</th><th>Category</th><th>Stock</th><th>Location</th><th>Status</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id} className="border-t border-gray-100"><td className="px-4 py-3"><p className="font-bold">{b.title}</p><p className="text-xs text-[var(--ink)]/50">{b.author||"No author recorded"}</p></td><td className="font-mono text-xs">{b.school_code||"—"}</td><td>{b.category}</td><td><b>{b.available_copies}</b> / {b.total_copies}<span className="ml-2 text-xs text-red-600">{b.lost_copies?`${b.lost_copies} lost`:""}</span></td><td>{b.shelf_location||"—"}</td><td><span className="rounded-full bg-[var(--gold)]/10 px-2 py-1 text-xs font-bold text-[var(--gold)]">{b.status}</span></td></tr>)}</tbody></table></div></div></>}
 {tab!=="catalogue"&&<div className="mt-4 grid gap-4">{(tab==="issues"?active:lost).map(l=><div key={l.id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-md"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="font-black text-[var(--ink)]">{l.library_books?.title||"Textbook"}</p><p className="mt-1 text-sm text-[var(--ink)]/65"><UserRound size={14} className="mr-1 inline"/>{l.students?.first_name} {l.students?.last_name} · {l.students?.admission_number}</p><p className="mt-2 text-xs text-[var(--ink)]/55"><CalendarDays size={13} className="mr-1 inline"/> Issued {l.issue_date||"—"} · Return {l.return_date||"—"}</p></div><div className="flex flex-wrap gap-2">{tab==="issues"&&<><button onClick={()=>void returnBook(l,false)} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Returned</button><button onClick={()=>void returnBook(l,true)} className="rounded-xl bg-red-600 px-3 py-2 text-xs font-bold text-white">Lost</button></>}{tab==="replacements"&&<button onClick={()=>void replaceBook(l)} className="rounded-xl bg-[var(--gold)] px-3 py-2 text-xs font-bold text-[var(--ink)]">Replacement received</button>}</div></div></div>)}{((tab==="issues"&&active.length===0)||(tab==="replacements"&&lost.length===0))&&<div className="rounded-2xl border border-dashed border-gray-200 bg-white p-10 text-center text-sm text-[var(--ink)]/50">No records in this section.</div>}</div>}
 {showBook&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={addBook} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">Add textbook</h2><div className="mt-4 grid gap-3">{([["title","Book name"],["author","Author"],["school_code","School code"],["category","Category"],["shelf_location","Shelf location"]] as const).map(([k,l])=><input key={k} required={k==="title"} value={(book as any)[k]} onChange={e=>setBook({...book,[k]:e.target.value})} placeholder={l} className="rounded-xl border border-gray-200 px-3 py-3 text-sm"/>)}<input type="number" min="1" value={book.total_copies} onChange={e=>setBook({...book,total_copies:Number(e.target.value)})} placeholder="Number of copies" className="rounded-xl border border-gray-200 px-3 py-3 text-sm"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowBook(false)} className="rounded-xl px-4 py-2 font-bold">Cancel</button><button className="rounded-xl bg-[var(--ink)] px-4 py-2 font-bold text-white">Save textbook</button></div></form></div>}
 {showIssue&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={issueBook} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">Issue textbook to learner</h2><div className="mt-4 grid gap-3"><select required value={issue.book_id} onChange={e=>setIssue({...issue,book_id:e.target.value})} className="rounded-xl border border-gray-200 px-3 py-3 text-sm"><option value="">Select available textbook</option>{books.filter(b=>b.available_copies>0).map(b=><option value={b.id} key={b.id}>{b.title} · {b.school_code||"No code"} · {b.available_copies} available</option>)}</select><select required value={issue.student_id} onChange={e=>setIssue({...issue,student_id:e.target.value})} className="rounded-xl border border-gray-200 px-3 py-3 text-sm"><option value="">Select learner</option>{students.map(s=><option value={s.id} key={s.id}>{s.first_name} {s.last_name} · {s.admission_number}</option>)}</select><label className="text-xs font-bold">Issue date<input type="date" required value={issue.issue_date} onChange={e=>setIssue({...issue,issue_date:e.target.value})} className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-3 text-sm"/></label><label className="text-xs font-bold">Return date<input type="date" required value={issue.return_date} onChange={e=>setIssue({...issue,return_date:e.target.value})} className="mt-1 w-full rounded-xl border border-gray-200 px-3 py-3 text-sm"/></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowIssue(false)} className="rounded-xl px-4 py-2 font-bold">Cancel</button><button className="rounded-xl bg-[var(--ink)] px-4 py-2 font-bold text-white">Issue textbook</button></div></form></div>}
 </main>;
}