import { AtSign, CheckCircle2, Loader2 } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

export default function MagicLinkPage() {
  const { sendMagicLink } = useSchoolAuth(); const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [failure, setFailure] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); setFailure(null); try { const result = await sendMagicLink(email); if (result.error) throw new Error(result.error); setMessage("If the email is linked to an active school account, a secure sign-in link has been sent. Check your inbox and spam folder."); } catch (cause) { setFailure(cause instanceof Error ? cause.message : "The email sign-in link could not be sent."); } finally { setBusy(false); } };
  return <PublicLayout><section className="mx-auto grid min-h-[calc(100vh-10rem)] max-w-7xl items-center px-5 py-16 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="hidden lg:block"><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--accent)]">Passwordless access</p><h1 className="mt-4 max-w-md font-serif text-5xl font-semibold tracking-tight">A secure portal link, delivered to your school email.</h1><p className="mt-6 max-w-md text-lg leading-8 text-[var(--ink)]/65">Use this option when you have an authorised school account and prefer not to enter a password. The system never creates an account from this form.</p></div><form onSubmit={submit} className="mx-auto w-full max-w-md rounded-[2rem] bg-white p-7 shadow-[0_18px_45px_rgba(29,43,37,.12)] sm:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--mist)] text-[var(--accent)]"><AtSign size={22} /></div><h1 className="mt-6 font-serif text-3xl font-semibold">Email sign-in link</h1><p className="mt-2 text-sm leading-6 text-[var(--ink)]/60">Enter the email address registered with your authorised school account.</p><label className="mt-7 grid gap-2 text-sm font-semibold">Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} className="rounded-xl border border-[var(--ink)]/15 px-3 py-3 font-normal outline-none ring-[var(--accent)] focus:ring-2" /></label>{failure && <p role="alert" className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{failure}</p>}{message && <p className="mt-4 rounded-xl bg-[var(--sage)]/15 px-4 py-3 text-sm leading-6 text-[var(--accent)]"><CheckCircle2 className="mr-2 inline" size={16} />{message}</p>}<button disabled={busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-full bg-[var(--ink)] px-5 py-3.5 text-sm font-semibold text-white disabled:opacity-60">{busy && <Loader2 className="animate-spin" size={16} />}Email me a secure link</button><Link href="/portal/login" className="mt-4 block text-center text-sm font-semibold text-[var(--accent)]">Use email and password instead</Link></form></section></PublicLayout>;
}
