import { ArrowRight, BookOpen, CalendarDays, ChevronLeft, ChevronRight, FlaskConical, Globe2, GraduationCap, HeartHandshake, MapPin, Medal, Phone, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import AboutSection from "@/components/AboutSection";
import "@/styles/menwe-hero-exact.css";

const slides=[
 {src:"https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=88",alt:"Learner reading in a school library"},
 {src:"https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=88",alt:"Learner writing in a notebook"},
 {src:"https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=900&q=88",alt:"Learner exploring a science experiment"},
 {src:"https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=88",alt:"Learner playing sport"},
 {src:"https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=900&q=88",alt:"Students performing music"}
];
const features=[[BookOpen,"Quality Education","Strong academic foundation with modern teaching approaches."],[UsersRound,"Holistic Development","Nurturing talents, character and life skills for today and tomorrow."],[ShieldCheck,"Safe Environment","A secure, inclusive and caring place where every child belongs."],[Medal,"Discipline & Values","Building responsible, respectful and God-fearing members of society."],[Globe2,"Bright Future","Preparing learners to thrive, lead and make a positive impact."]] as const;
const programs=[[BookOpen,"Early Childhood & Primary","Build strong foundations in literacy, numeracy, creative arts and social development through joyful, learner-centred experiences."],[FlaskConical,"Junior Secondary School","Develop competencies through science, languages, digital literacy, practical discovery and the confidence to solve real-world problems."],[Medal,"Co-Curricular & Talent Pathways","Grow the whole learner through music and band, football, athletics, STEM clubs, leadership and purposeful teamwork."]] as const;
const news=[["Admissions","Applications open for the upcoming academic term","Plan ahead for your child’s next learning journey with Menwe. Our admissions team is ready to guide families through the process."],["Learning","Celebrating progress beyond the classroom","From academic milestones to sport, music and practical projects, our learners are encouraged to discover where they can thrive."]] as const;
const events=[["SEP","12","Parents-Teachers Meeting","09:00 AM · Main School Campus"],["OCT","03","Annual Sports Day","08:00 AM · School Sports Field"],["OCT","17","Menwe Science Fair","10:00 AM · Science & Innovation Hall"]] as const;

function HeroGallery(){const [active,setActive]=useState(0);const move=(d:number)=>setActive((active+d+slides.length)%slides.length);useEffect(()=>{const t=window.setInterval(()=>setActive(v=>(v+1)%slides.length),6500);return()=>window.clearInterval(t)},[]);return <div className="menwe-gallery-wrap"><svg className="menwe-hero-swoosh" viewBox="0 0 760 650" preserveAspectRatio="none" aria-hidden="true"><path d="M90 620C82 360 190 105 505 54C600 39 674 50 736 82" fill="none" stroke="#D89B28" strokeWidth="2"/><path d="M68 624C54 338 182 77 510 30" fill="none" stroke="#D89B28" strokeOpacity=".22"/></svg><div className="menwe-gallery"><button className="menwe-gallery-arrow left" onClick={()=>move(-1)} aria-label="Previous image"><ChevronLeft/></button><div className="menwe-gallery-track">{slides.map((s,i)=><button key={s.src} className={`menwe-photo-card ${i===active?"current":""}`} onClick={()=>setActive(i)} aria-label={`Show image ${i+1}`}><img src={s.src} alt={s.alt}/><span className="menwe-photo-shade"/></button>)}</div><button className="menwe-gallery-arrow right" onClick={()=>move(1)} aria-label="Next image"><ChevronRight/></button><div className="menwe-pagination">{slides.map((_,i)=><button key={i} className={i===active?"active":""} onClick={()=>setActive(i)} aria-label={`Go to image ${i+1}`}/>)}</div></div></div>}
function FeatureStrip(){return <div className="menwe-features">{features.map(([Icon,title,text])=><article key={title} className="menwe-feature-card"><span className="menwe-feature-icon"><Icon size={22}/></span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div>}

export default function MenweHeroHome(){const [,go]=useLocation();return <PublicLayout><div className="menwe-exact-page">
<section className="menwe-hero-exact" aria-labelledby="hero-title"><div className="menwe-hero-inner"><div className="menwe-copy"><p className="menwe-eyebrow">WELCOME TO</p><h1 id="hero-title">Menwe Primary &amp; Junior School</h1><p className="menwe-tagline">Inspire. Empower. Thrive.</p><span className="menwe-gold-line"/><p className="menwe-description">Nurture every learner to learn, grow and succeed in a caring environment that builds character and confidence for a brighter future.</p><div className="menwe-cta-row"><button className="menwe-cta primary" onClick={()=>go("/academics")}><GraduationCap size={18}/>Our Academics</button><button className="menwe-cta secondary" onClick={()=>go("/admissions")}><UsersRound size={18}/>Join Our School</button></div></div><HeroGallery/></div><FeatureStrip/></section>
<AboutSection />
<section id="academics" className="menwe-section menwe-programs-section"><div className="menwe-section-inner"><div className="menwe-heading-row"><div><p className="menwe-section-kicker">ACADEMIC PROGRAMS &amp; CURRICULUM</p><h2>Learning Designed for Every Stage</h2></div><p>From early foundations to junior secondary and talent pathways, we connect knowledge with confidence, character and practical skills.</p></div><div className="menwe-program-grid">{programs.map(([Icon,title,text])=><article className="menwe-program-card" key={title}><span className="menwe-program-icon"><Icon size={23}/></span><h3>{title}</h3><p>{text}</p><button onClick={()=>go("/academics")} className="menwe-text-link">Learn More <ArrowRight size={15}/></button></article>)}</div></div></section>
<section className="menwe-section menwe-principal-section"><div className="menwe-section-inner"><div className="menwe-welcome-card"><div className="menwe-principal-photo"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=700&q=88" alt="School leader portrait placeholder"/></div><div className="menwe-quote"><span className="menwe-quote-mark">“</span><p className="menwe-section-kicker">A MESSAGE FROM SCHOOL LEADERSHIP</p><h2>Welcome to a place where every child is encouraged to become their best self.</h2><blockquote>“We warmly welcome parents and guardians to Menwe. Our promise is to provide a safe, purposeful learning environment where children are known, supported and challenged to grow. When school and family work together, learners gain the confidence and character to thrive.”</blockquote><div className="menwe-signature"><span className="menwe-signature-line"/><div><strong>School Leadership</strong><small>Menwe Primary &amp; Junior School</small></div></div></div></div></div></section>
<section id="news-events" className="menwe-section menwe-news-section"><div className="menwe-section-inner menwe-news-grid"><div><p className="menwe-section-kicker">LATEST FROM MENWE</p><div className="menwe-news-heading"><h2>News, Announcements &amp; Events</h2><button className="menwe-text-link" onClick={()=>go("/news")}>View all news <ArrowRight size={15}/></button></div><div className="menwe-news-cards">{news.map(([tag,title,text])=><article key={title} className="menwe-news-card"><span>{tag}</span><h3>{title}</h3><p>{text}</p><button className="menwe-text-link" onClick={()=>go("/news")}>Read story <ArrowRight size={14}/></button></article>)}</div></div><div className="menwe-events"><p className="menwe-section-kicker">UPCOMING</p><h2>What’s Next</h2>{events.map(([month,day,title,meta])=><button className="menwe-event" key={title} onClick={()=>go("/events")}><span className="menwe-date"><b>{month}</b><strong>{day}</strong></span><span><b>{title}</b><small>{meta}</small></span><ArrowRight size={16}/></button>)}</div></div></section>
<section className="menwe-admissions-banner"><div className="menwe-banner-inner"><div><p className="menwe-section-kicker">ADMISSIONS ARE OPEN</p><h2>Ready to Give Your Child a Brighter Future?</h2><p>Admissions are currently open for the upcoming academic term. Join the Menwe Primary &amp; Junior School family today.</p></div><div className="menwe-banner-actions"><button onClick={()=>go("/admissions")} className="menwe-banner-primary">Apply Now <ArrowRight size={16}/></button><button onClick={()=>go("/admissions")} className="menwe-banner-outline">Download Fee Structure / Prospectus</button></div></div></section>
<section id="contact" className="menwe-section menwe-contact-section"><div className="menwe-section-inner"><div className="menwe-contact-heading"><div><p className="menwe-section-kicker">COME AND VISIT</p><h2>Let’s stay connected</h2><p>Have a question about admissions, learning or school life? Reach out to our team or plan a visit to our Kionyo campus.</p></div><button className="menwe-cta primary" onClick={()=>go("/contact")}>Contact the School <ArrowRight size={16}/></button></div><div className="menwe-contact-grid"><div className="menwe-contact-item"><span><MapPin size={20}/></span><div><b>Address</b><p>P.O. Box 19, Kionyo</p></div></div><div className="menwe-contact-item"><span><Phone size={20}/></span><div><b>Call us</b><p>0142550882</p></div></div><div className="menwe-contact-item"><span><CalendarDays size={20}/></span><div><b>School hours</b><p>Monday – Friday · 7:30 AM – 4:30 PM</p></div></div><a className="menwe-map" href="https://www.google.com/maps/search/?api=1&query=Kionyo%2C%20Kenya" target="_blank" rel="noreferrer"><div className="menwe-map-grid"/><span><MapPin size={17}/> Open Kionyo location in Google Maps <ArrowRight size={15}/></span></a></div></div></section>
</div></PublicLayout>}
