import { Bell, CheckCheck, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";

type Row = Record<string, any>;
export default function NotificationCenter() {
 const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState<string|null>(null);
 const load=async()=>{setLoading(true); try{const db=getSupabase(); const {data:userData,error:userError}=await db.auth.getUser(); if(userError) throw userError; if(!userData.user) throw new Error("Sign in is required."); const {data,error}=await db.from("notifications").select("id,title,body,category,read_at,created_at").eq("recipient_id",userData.user.id).order("created_at",{ascending:false}); if(error) throw error; setRows((data??[]) as Row[]);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load notifications.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const mark=async(id:string)=>{try{const {error}=await getSupabase().from("notifications").update({read_at:new Date().toISOString()}).eq("id",id); if(error) throw error; await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to update notification.");}};
 const markAll=async()=>{try{const {data:userData}=await getSupabase().auth.getUser(); if(!userData.user) return; const {error}=await getSupabase().from("notifications").update({read_at:new Date().toISOString()}).eq("recipient_id",userData.user.id).is("read_at",null); if(error) throw error; await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to mark notifications read.");}};
 const unread=rows.filter(r=>!r.read_at).length;
 return <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-serif text-2xl font-semibold">Notifications</h2><p className="mt-2 text-sm text-[var(--ink)]/60">{unread} unread notification{unread===1?"":"s"}. Read state is persisted in the canonical notifications table.</p></div><div className="flex gap-2"><Bell className="text-[var(--accent)]" size={24}/><button type="button" onClick={()=>void markAll()} disabled={!unread} className="inline-flex items-center gap-2 rounded-xl border border-[var(--ink)]/15 px-3 py-2 text-sm font-semibold disabled:opacity-40"><CheckCheck size={16}/>Mark all read</button></div></div>{loading?<div className="flex justify-center gap-2 py-12 text-sm text-[var(--ink)]/60"><Loader2 className="animate-spin" size={18}/>Loading…</div>:rows.length?<div className="mt-6 grid gap-3">{rows.map(r=><button type="button" key={r.id} onClick={()=>!r.read_at&&void mark(r.id)} className={`rounded-2xl border p-4 text-left ${r.read_at?"border-[var(--ink)]/8 bg-white":"border-[var(--accent)]/30 bg-[var(--accent)]/5"}`}><div className="flex justify-between gap-3"><strong>{r.title}</strong><span className="text-xs text-[var(--ink)]/50">{new Date(r.created_at).toLocaleString()}</span></div><p className="mt-2 text-sm leading-6 text-[var(--ink)]/70">{r.body}</p><p className="mt-2 text-xs font-semibold text-[var(--ink)]/45">{r.category??"General"} · {r.read_at?"Read":"Unread"}</p></button>)}</div>:<p className="mt-6 rounded-2xl border border-dashed border-[var(--ink)]/15 px-5 py-8 text-center text-sm text-[var(--ink)]/55">No notifications yet.</p>}{message&&<p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{message}</p>}</section>;
}
