import { BarChart3, FileUp, ImagePlus, Loader2, Plus, Settings2, Upload } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getRows, insertRow } from "@/lib/database";
import { getSupabase } from "@/lib/supabase";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

type Row = Record<string, unknown>;
const text = (value: unknown, fallback = "—") => value === null || value === undefined || value === "" ? fallback : String(value);
const inputClass = "w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm font-normal outline-none ring-[var(--accent)] transition focus:ring-2";

function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-[1.75rem] border border-[var(--ink)]/10 bg-white p-5 shadow-[0_10px_28px_rgba(29,43,37,.05)] sm:p-7"><h2 className="font-serif text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--ink)]/60">{description}</p><div className="mt-6">{children}</div></section>; }
function Notice({ message, success }: { message: string; success?: boolean }) { return <p className={`rounded-xl px-4 py-3 text-sm leading-6 ${success ? "bg-[var(--sage)]/16 text-[var(--accent)]" : "bg-red-50 text-red-800"}`}>{message}</p>; }

export default function OperationsAdmin() {
  const [tab, setTab] = useState<"settings" | "gallery" | "import" | "reports">("settings");
  const labels: Record<typeof tab, string> = { settings: "School settings", gallery: "Gallery media", import: "CSV import", reports: "Reports" };
  return <div className="grid gap-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">Administration</p><h1 className="mt-2 font-serif text-4xl font-semibold">Operations & reports</h1></div><div className="flex flex-wrap gap-2">{(Object.keys(labels) as (keyof typeof labels)[]).map(key => <button onClick={() => setTab(key)} key={key} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab === key ? "bg-[var(--ink)] text-white" : "bg-white text-[var(--ink)]/65"}`}>{labels[key]}</button>)}</div>{tab === "settings" ? <SettingsPanel /> : tab === "gallery" ? <GalleryPanel /> : tab === "import" ? <CsvImportPanel /> : <ReportsPanel />}</div>;
}

function SettingsPanel() {
  const [settings, setSettings] = useState<Row[]>([]); const [keyName, setKeyName] = useState(""); const [value, setValue] = useState(""); const [isPublic, setIsPublic] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const refresh = useCallback(async () => { try { setSettings((await getRows("school_settings", "key,value,is_public,updated_at", 0, 100, "updated_at")).data); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Settings could not be loaded."); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); try { const parsed = value.trim().startsWith("{") ? JSON.parse(value) : { value: value.trim() }; const { error } = await getSupabase().from("school_settings").upsert({ key: keyName.trim(), value: parsed, is_public: isPublic }); if (error) throw error; setKeyName(""); setValue(""); setIsPublic(false); setMessage("School setting saved."); await refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Enter valid JSON or plain text for the setting value."); } finally { setBusy(false); } };
  return <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel title="School settings" description="Store verified school settings such as the official contact phone, postal address, or term notices. Do not store passwords, service keys, or payment secrets here.">{settings.length === 0 ? <p className="rounded-2xl border border-dashed border-[var(--ink)]/15 px-5 py-8 text-center text-sm text-[var(--ink)]/55">No school settings have been recorded.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr className="border-b border-[var(--ink)]/10 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/45"><th className="px-3 py-3">Key</th><th className="px-3 py-3">Public</th><th className="px-3 py-3">Updated</th></tr></thead><tbody>{settings.map(item => <tr key={text(item.key)} className="border-b border-[var(--ink)]/7 last:border-0"><td className="px-3 py-3 font-medium">{text(item.key)}</td><td className="px-3 py-3">{item.is_public ? "Yes" : "No"}</td><td className="px-3 py-3">{item.updated_at ? new Date(String(item.updated_at)).toLocaleDateString() : "—"}</td></tr>)}</tbody></table></div>}</Panel><Panel title="Save setting" description="A public setting may be read by public pages once it is intentionally used in the page content."><form onSubmit={save} className="grid gap-3"><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Key<input required value={keyName} onChange={event => setKeyName(event.target.value)} className={inputClass} placeholder="For example, school_contact_phone" /></label><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Value<textarea required rows={4} value={value} onChange={event => setValue(event.target.value)} className={inputClass} placeholder="Plain text or valid JSON" /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={isPublic} onChange={event => setIsPublic(event.target.checked)} />Publish this setting for public read access</label>{message && <Notice message={message} success={message.includes("saved")} />}<button disabled={busy} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-55">{busy ? <Loader2 className="animate-spin" size={16} /> : <Settings2 size={16} />}Save setting</button></form></Panel></div>;
}

function GalleryPanel() {
  const { profile } = useSchoolAuth(); const [albums, setAlbums] = useState<Row[]>([]); const [albumId, setAlbumId] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [file, setFile] = useState<File | null>(null); const [caption, setCaption] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const refresh = useCallback(async () => { try { setAlbums((await getRows("gallery_albums", "id,title,description,status", 0, 100, "created_at")).data); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Gallery albums could not be loaded."); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); try { const album = await insertRow("gallery_albums", { title, description: description || null, status: "DRAFT", created_by: profile?.id }); setTitle(""); setDescription(""); setAlbumId(text(album.id, "")); setMessage("Gallery album created as a draft. Upload and publish only approved images."); await refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The gallery album could not be created."); } finally { setBusy(false); } };
  const upload = async (event: React.FormEvent) => { event.preventDefault(); if (!file || !albumId) { setMessage("Choose a gallery album and a valid image first."); return; } if (!["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 5 * 1024 * 1024) { setMessage("Upload a JPG, PNG, or WebP image no larger than 5 MB."); return; } setBusy(true); setMessage(null); try { const key = `gallery/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const storage = getSupabase().storage.from("public-media"); const { error: uploadError } = await storage.upload(key, file, { contentType: file.type, upsert: false }); if (uploadError) throw uploadError; const { data: publicUrl } = storage.getPublicUrl(key); const uploaded = await insertRow("uploaded_files", { owner_id: profile?.id || null, storage_key: key, public_url: publicUrl.publicUrl, filename: file.name, mime_type: file.type, byte_size: file.size, purpose: "gallery" }); await insertRow("gallery_images", { album_id: albumId, file_id: uploaded.id, caption: caption || null, status: "DRAFT" }); setCaption(""); setFile(null); setMessage("Image uploaded and recorded as a draft. Publish the image only after school approval."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The image could not be uploaded."); } finally { setBusy(false); } };
  return <div className="grid gap-6 xl:grid-cols-2"><Panel title="Gallery albums" description="Albums and images are real database records. Draft content is not shown on the public gallery."><form onSubmit={create} className="grid gap-3"><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Album title<input required value={title} onChange={event => setTitle(event.target.value)} className={inputClass} /></label><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Description<textarea rows={3} value={description} onChange={event => setDescription(event.target.value)} className={inputClass} /></label><button disabled={busy} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-55"><Plus size={16} />Create draft album</button></form><div className="mt-7 grid gap-2">{albums.length === 0 ? <p className="text-sm text-[var(--ink)]/55">No albums have been created.</p> : albums.map(album => <div key={text(album.id)} className="rounded-xl bg-[var(--mist)] px-3 py-2 text-sm"><strong>{text(album.title)}</strong><span className="ml-2 text-[var(--ink)]/55">{text(album.status)}</span></div>)}</div></Panel><Panel title="Upload gallery image" description="The file is uploaded to the controlled public-media bucket and linked to a draft gallery image record."><form onSubmit={upload} className="grid gap-3"><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Album<select required value={albumId} onChange={event => setAlbumId(event.target.value)} className={inputClass}><option value="">Select a gallery album</option>{albums.map(album => <option value={text(album.id)} key={text(album.id)}>{text(album.title)}</option>)}</select></label><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Approved image<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setFile(event.target.files?.[0] || null)} className={inputClass} /></label><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Caption<input value={caption} onChange={event => setCaption(event.target.value)} className={inputClass} /></label>{message && <Notice message={message} success={message.includes("uploaded") || message.includes("created")} />}<button disabled={busy} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-55">{busy ? <Loader2 className="animate-spin" size={16} /> : <ImagePlus size={16} />}Upload draft image</button></form></Panel></div>;
}

function CsvImportPanel() {
  const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const importStudents = async (event: React.FormEvent) => { event.preventDefault(); if (!file) { setMessage("Select a CSV file first."); return; } setBusy(true); setMessage(null); try { const raw = await file.text(); const lines = raw.split(/\r?\n/).filter(line => line.trim()); const headers = lines.shift()?.split(",").map(item => item.trim()) ?? []; const required = ["admission_number", "first_name", "last_name"]; if (required.some(field => !headers.includes(field))) throw new Error("The CSV must contain admission_number, first_name, and last_name columns."); const seen = new Set<string>(); const records = lines.map((line, index) => { const cells = line.split(",").map(value => value.trim()); const row = Object.fromEntries(headers.map((header, column) => [header, cells[column] || ""])); if (!row.admission_number || !row.first_name || !row.last_name) throw new Error(`Row ${index + 2} is missing a required value.`); if (seen.has(row.admission_number)) throw new Error(`The file repeats admission number ${row.admission_number}.`); seen.add(row.admission_number); return row; }); if (!records.length) throw new Error("The CSV has no student rows."); for (const row of records) await insertRow("students", { ...row, email: row.email || null, date_of_birth: row.date_of_birth || null, status: "ACTIVE" }); setMessage(`${records.length} student record${records.length === 1 ? "" : "s"} were imported successfully.`); setFile(null); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The CSV import could not complete."); } finally { setBusy(false); } };
  return <Panel title="Import student records" description="Upload a CSV containing `admission_number`, `first_name`, and `last_name`; optional columns include middle_name, date_of_birth, gender, phone, email, and address. Validate the file carefully: this tool creates persistent student records."><form onSubmit={importStudents} className="grid max-w-xl gap-4"><label className="grid gap-1.5 text-sm font-semibold text-[var(--ink)]/75">Student CSV file<input required type="file" accept=".csv,text/csv" onChange={event => setFile(event.target.files?.[0] || null)} className={inputClass} /></label>{message && <Notice message={message} success={message.includes("successfully")} />}<button disabled={busy} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-55">{busy ? <Loader2 className="animate-spin" size={16} /> : <Upload size={16} />}Validate & import students</button></form></Panel>;
}

function ReportsPanel() {
  const [counts, setCounts] = useState<{ label: string; count: number }[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { let alive = true; void Promise.all(["students", "teachers", "parents", "enrollments", "attendance_sessions", "exam_results", "invoices", "payments", "admission_applications", "contact_submissions", "audit_logs"].map(table => getRows(table, "id", 0, 1))).then(results => { if (alive) setCounts(results.map((result, index) => ({ label: ["Students", "Teachers", "Parents", "Active enrolment records", "Attendance sessions", "Exam results", "Invoices", "Payment records", "Admission applications", "Contact submissions", "Audit events"][index], count: result.count }))); }).catch(cause => alive && setMessage(cause instanceof Error ? cause.message : "Reports could not be calculated.")).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  return <Panel title="Administrative record counts" description="These are live counts from the protected database and are not demo metrics.">{loading ? <div className="flex items-center justify-center gap-3 py-10 text-sm text-[var(--ink)]/60"><Loader2 className="animate-spin text-[var(--accent)]" size={18} />Calculating live counts…</div> : message ? <Notice message={message} /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{counts.map(item => <div className="rounded-2xl bg-[var(--mist)] p-4" key={item.label}><BarChart3 className="text-[var(--accent)]" size={19} /><p className="mt-8 text-2xl font-semibold">{item.count}</p><p className="mt-1 text-sm text-[var(--ink)]/60">{item.label}</p></div>)}</div>}</Panel>;
}
