import { useEffect, useState } from "react";
import { AlertCircle, CalendarDays, FileText, GraduationCap, Loader2, LogOut, UserRound } from "lucide-react";
import { useLocation } from "wouter";
import { PortalLayout } from "@/components/PortalLayout";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import ParentAssistant from "@/components/ParentAssistant";
import { getSupabase } from "@/lib/supabase";
type Student={id:string;name:string;admission_number:string};
export default function ParentDashboardPage(){const {user,profile,loading,signOut}=useSchoolAuth();const[,go]=useLocation();const[students,setStudents]=useState<Student[]>([]);const[selected,setSelected]=useState("");const[busy,setBusy]=useState(true);const[message,setMessage]=useState("");useEffect(()=>{if(loading)return;if(!user||!profile||profile.status!=="ACTIVE"||profile.role!=="PARENT"){go("/portal/login");return;}let active=true;(async()=>{try{const db=getSupabase();const {data:parent,error:parentError}=await db.from("parents").select("id").eq("profile_id",user.id).maybeSingle();if(parentError)throw parentError;if(!parent){setMessage("Your account is active, but the parent record is not linked yet. Please contact school administration.");return;}const {data:links,error:linkError}=await db.from("student_parents").select("student_id").eq("parent_id",parent.id);if(linkError)throw linkError;const ids=(links??[]).map((x:any)=>x.student_id).filter(Boolean);if(!ids.length){setMessage("Your account is active, but no learner is linked yet. Please contact school administration.");return;}const {data,error}=await db.from("students").select("id,admission_number,first_name,middle_name,last_name").in("id",ids).eq("status","ACTIVE").order("first_name");if(error)throw error;if(active){const rows=(data??[]).map((s:any)=>({id:s.id,name:[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(" "),admission_number:s.admission_number}));setStudents(rows);setSelected(rows[0]?.id??"");}}catch(e){if(active)setMessage(e instanceof Error?e.message:"Unable to load linked learners.");}finally{if(active)setBusy(false);}})();return()=>{active=false;}},[loading,profile,user,go]);
if(loading||busy)return <PortalLayout role="PARENT"><div className="grid min-h-[70vh] place-items-center"><Loader2 className="animate-spin text-[var(--accent)]"/></div></PortalLayout>;const learner=students.find(s=>s.id===selected)??students[0];return <PortalLayout role="PARENT"><main className="mx-auto w-full max-w-7xl px-4 py-5 sm:px-6 lg:px-8 lg:py-8"><header className="menwe-admin-hero rounded-[2rem] p-6 text-white shadow-xl sm:p-8"><p className="menwe-admin-kicker"><GraduationCap size={14}/> Family workspace</p><h1 className="mt-4 font-serif text-4xl font-semibold sm:text-5xl">Welcome, {profile?.display_name?.split(/\s+/)[0]||"Parent"}.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">Secure access to linked learner progress, school records and support.</p><button onClick={async()=>{await signOut();go("/portal/login");}} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/15 px-4 font-bold"><LogOut size={16}/> Sign out</button></header>{message&&<div role="alert" className="mt-5 flex gap-2 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800"><AlertCircle size={18}/>{message}</div>}{students.length>0&&<><section className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><UserRound className="text-[var(--accent)]"/><p className="mt-3 text-xs font-bold uppercase text-slate-400">Linked learner</p><p className="mt-1 text-xl font-bold text-[var(--ink)]">{learner?.name}</p><p className="mt-1 text-sm text-slate-500">{learner?.admission_number}</p></div><a href="/portal/attendance" className="rounded-2xl border bg-white p-5 shadow-sm"><CalendarDays className="text-[var(--accent)]"/><p className="mt-3 text-xs font-bold uppercase text-slate-400">Attendance</p><p className="mt-1 text-xl font-bold text-[var(--ink)]">View attendance</p><p className="mt-2 text-sm text-[var(--accent)]">Open records →</p></a></section><section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><label className="block text-sm font-bold text-[var(--ink)]">Select learner<select value={learner?.id??""} onChange={e=>setSelected(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border px-4">{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.admission_number}</option>)}</select></label></section><section className="mt-6"><ParentAssistant/></section><section className="mt-6"><a href="/portal/report-cards" className="block rounded-2xl border bg-white p-5 shadow-sm"><FileText className="text-[var(--accent)]"/><h2 className="mt-3 font-bold">Report cards</h2><p className="mt-1 text-sm text-slate-500">Open the protected report-card workspace.</p></a></section></>}</main></PortalLayout>;
}
