import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, BarChart3, Bell, BookOpenCheck, CalendarDays, Clock3, CreditCard, FileText, GraduationCap, LogOut, MessageSquare, UserRound } from "lucide-react";
import { Link, useLocation } from "wouter";
import { PortalLayout } from "@/components/PortalLayout";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import ParentAssistant from "@/components/ParentAssistant";
import { getSupabase } from "@/lib/supabase";

type Student = { id: string; name: string; admission_number: string; gender: string | null };
type AttendanceSummary = { total: number; present: number; absent: number; late: number };
type StudentParentRow = { student_id: string | null };
type StudentRow = { id: string; admission_number: string; first_name: string | null; middle_name: string | null; last_name: string | null; gender: string | null };
type AttendanceRow = { status: string | null };
const EMPTY_ATTENDANCE: AttendanceSummary = { total: 0, present: 0, absent: 0, late: 0 };

function friendlyError(error: unknown) { const text = error instanceof Error ? error.message : String(error); if (/network|fetch|timeout|429/i.test(text)) return "Connection issue. Please check your network and try again."; if (/row-level security|permission denied|not authorized/i.test(text)) return "You are not authorised to view these learner records."; return "Learner information could not be loaded. Please try again."; }

export default function ParentDashboardPage() {
  const { user, profile, loading, signOut } = useSchoolAuth(); const [, go] = useLocation(); const isStudent = profile?.role === "STUDENT";
  const [students,setStudents]=useState<Student[]>([]),[selected,setSelected]=useState(""),[attendance,setAttendance]=useState<AttendanceSummary>(EMPTY_ATTENDANCE),[busy,setBusy]=useState(true),[message,setMessage]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!user?.id||profile?.status!=="ACTIVE"||!["PARENT","STUDENT"].includes(profile.role))return;setBusy(true);setMessage(null);try{const db=getSupabase();let ids:string[]=[];if(isStudent){const{data,error}=await db.from("students").select("id").eq("profile_id",user.id).eq("status","ACTIVE").maybeSingle();if(error)throw error;if(data?.id)ids=[data.id]}else{const{data:parent,error:parentError}=await db.from("parents").select("id").eq("profile_id",user.id).maybeSingle();if(parentError)throw parentError;if(!parent){setStudents([]);setAttendance(EMPTY_ATTENDANCE);setMessage("Your account is active, but the parent record is not linked yet. Please contact school administration.");return}const{data:links,error:linkError}=await db.from("student_parents").select("student_id").eq("parent_id",parent.id);if(linkError)throw linkError;ids=[...new Set((links??[]).map((row:StudentParentRow)=>row.student_id).filter((id):id is string=>Boolean(id)))]}if(!ids.length){setStudents([]);setAttendance(EMPTY_ATTENDANCE);setMessage(isStudent?"Your learner record is not linked yet. Please contact school administration.":"Your account is active, but no learner is linked yet. Please contact school administration.");return}const{data,error}=await db.from("students").select("id,admission_number,first_name,middle_name,last_name,gender").in("id",ids).eq("status","ACTIVE").order("first_name");if(error)throw error;const rows:Student[]=(data??[]).map((student:StudentRow)=>({id:student.id,name:[student.first_name,student.middle_name,student.last_name].filter((part):part is string=>Boolean(part?.trim())).join(" ")||"Learner",admission_number:student.admission_number,gender:student.gender}));setStudents(rows);setSelected(current=>rows.some(row=>row.id===current)?current:rows[0]?.id??"")}catch(error){setStudents([]);setAttendance(EMPTY_ATTENDANCE);setMessage(friendlyError(error))}finally{setBusy(false)}},[isStudent,profile?.role,profile?.status,user?.id]);
  useEffect(()=>{if(loading)return;if(!user||!profile||profile.status!=="ACTIVE"||!["PARENT","STUDENT"].includes(profile.role)){go("/portal/login");return}void load()},[go,load,loading,profile,user]);
  const learner=useMemo(()=>students.find(student=>student.id===selected)??students[0]??null,[selected,students]);
  useEffect(()=>{if(!learner){setAttendance(EMPTY_ATTENDANCE);return}let active=true;const loadAttendance=async()=>{try{const db=getSupabase();const{data:sessions,error:sessionError}=await db.from("attendance_sessions").select("id").order("session_date",{ascending:false});if(sessionError)throw sessionError;const sessionIds=(sessions??[]).map((row:{id:string})=>row.id);if(!sessionIds.length){if(active)setAttendance(EMPTY_ATTENDANCE);return}const{data,error}=await db.from("attendance_records").select("status").eq("student_id",learner.id).in("session_id",sessionIds);if(error)throw error;const summary=(data??[]).reduce<AttendanceSummary>((result,row:AttendanceRow)=>{const status=String(row.status??"").toLowerCase();result.total+=1;if(status==="present")result.present+=1;else if(status==="absent")result.absent+=1;else if(status==="late")result.late+=1;return result},{...EMPTY_ATTENDANCE});if(active)setAttendance(summary)}catch(error){if(active)setMessage(friendlyError(error))}};void loadAttendance();return()=>{active=false}},[learner]);
  const attendanceRate=attendance.total>0?Math.round(((attendance.present+attendance.late)/attendance.total)*100):null;const logout=async()=>{await signOut();go("/portal/login")};const firstName=profile?.full_name?.split(/\s+/)[0]||(isStudent?"Learner":"Parent");
  if(loading||busy)return <PortalLayout role={isStudent?"STUDENT":"PARENT"}><main className="mx-auto grid min-h-[70vh] w-full max-w-7xl place-items-center px-4"><div className="grid w-full max-w-3xl gap-4"><div className="h-56 animate-pulse rounded-[2rem] bg-[var(--mist)]"/><div className="grid gap-4 sm:grid-cols-3"><div className="h-28 animate-pulse rounded-2xl bg-[var(--mist)]"/><div className="h-28 animate-pulse rounded-2xl bg-[var(--mist)]"/><div className="h-28 animate-pulse rounded-2xl bg-[var(--mist)]"/></div></div></main></PortalLayout>;
  const quickLinks=[
    {href:"/portal/timetable",label:"Today’s timetable",description:"Check lessons and the school day at a glance.",icon:Clock3},
    {href:"/portal/homework",label:"Homework & learning",description:"Open assignments and learning work shared with you.",icon:BookOpenCheck},
    {href:"/portal/finance",label:"Fees & payments",description:"Open the secure finance area for fee records.",icon:CreditCard},
    {href:"/portal/report-cards",label:"Report cards",description:"Review published academic results and reports.",icon:FileText},
    {href:"/portal/attendance",label:"Attendance",description:"Review attendance records available to your account.",icon:CalendarDays},
    {href:"/portal/messages",label:"School messages",description:"Stay connected with authorised school communication.",icon:MessageSquare},
  ];
  return <PortalLayout role={isStudent?"STUDENT":"PARENT"}><main className="mx-auto w-full max-w-[1440px] space-y-8 px-4 py-6 sm:px-6 lg:px-8 lg:py-10">
    <header className="menwe-admin-hero rounded-[2.25rem] p-6 text-white shadow-2xl sm:p-9 lg:p-11"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="menwe-admin-kicker"><GraduationCap size={14}/> {isStudent?"Student workspace":"Family workspace"}</p><h1 className="mt-5 text-4xl font-extrabold leading-[1.02] tracking-[-.045em] sm:text-5xl lg:text-6xl">Welcome, {firstName}.</h1><p className="mt-5 max-w-2xl text-[15px] leading-7 text-white/80 sm:text-base">A calm, secure home for learner progress, attendance, academic records, school communication and everyday school tasks.</p><div className="mt-7 flex flex-wrap gap-2"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.07] px-3.5 py-2 text-xs font-bold text-white/80"><span className="menwe-live-dot"/> Live school data</span><span className="rounded-full border border-white/10 bg-white/[.07] px-3.5 py-2 text-xs font-bold text-white/80">Private {isStudent?"learner":"family"} access</span></div></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4 lg:max-w-xs"><div className="flex items-center gap-3"><Bell size={18} className="text-[var(--gold)]"/><div><p className="text-xs font-extrabold uppercase tracking-[.12em] text-white/50">Stay up to date</p><p className="mt-1 text-sm font-semibold text-white/80">Use the notification bell and Messages area for school updates.</p></div></div></div></div><button type="button" onClick={()=>void logout()} className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[var(--gold)] px-4 font-extrabold text-[var(--ink)] shadow-lg transition hover:brightness-105"><LogOut size={16}/> Sign out</button></header>
    {message&&<div role="alert" className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900"><AlertCircle size={18} className="mt-0.5 shrink-0"/>{message}</div>}
    {learner&&<><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className="menwe-admin-metric rounded-[1.35rem]"><UserRound size={20} className="text-[var(--accent)]"/><p className="mt-4 menwe-premium-label">{isStudent?"Your learner":"Linked learner"}</p><p className="mt-2 truncate text-xl font-extrabold">{learner.name}</p><p className="mt-1 text-sm font-semibold text-[var(--ink)]/65">Admission No. {learner.admission_number}</p></article><article className="menwe-admin-metric rounded-[1.35rem]"><UserRound size={20} className="text-[var(--accent)]"/><p className="mt-4 menwe-premium-label">Gender</p><p className="mt-2 text-xl font-extrabold">{learner.gender||"Not recorded"}</p><p className="mt-1 text-sm text-[var(--ink)]/65">Recorded in the learner profile.</p></article><article className="menwe-admin-metric rounded-[1.35rem]"><CalendarDays size={20} className="text-[var(--accent)]"/><p className="mt-4 menwe-premium-label">Attendance</p><p className="mt-2 text-3xl font-black">{attendanceRate===null?"—":`${attendanceRate}%`}</p><p className="mt-1 text-sm text-[var(--ink)]/65">{attendance.total?`${attendance.present} present · ${attendance.absent} absent`:"No records yet"}</p></article><Link href="/portal/report-cards" className="menwe-admin-metric menwe-interactive rounded-[1.35rem]"><BarChart3 size={20} className="text-[var(--accent)]"/><p className="mt-4 menwe-premium-label">Performance</p><p className="mt-2 text-xl font-extrabold">Report cards</p><p className="mt-1 text-sm font-bold text-[var(--accent)]">View academic results →</p></Link></section>
    {students.length>1&&<section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><label className="block text-sm font-extrabold text-[var(--ink)]">Select learner<select aria-label="Select learner" value={learner.id} onChange={event=>setSelected(event.target.value)} className="mt-3 min-h-12 w-full rounded-xl border border-[var(--ink)]/15 bg-white px-4 text-sm font-semibold outline-none focus:ring-2 focus:ring-[var(--accent)]">{students.map(student=><option key={student.id} value={student.id}>{student.name} · {student.admission_number} · {student.gender||"Gender not recorded"}</option>)}</select></label></section>}
    <section><div className="flex items-end justify-between gap-4"><div><p className="menwe-premium-label">Your school workspace</p><h2 className="mt-1 text-2xl font-extrabold tracking-[-.025em] sm:text-3xl">Everything important, one tap away</h2></div><span className="hidden rounded-full bg-[var(--gold)]/10 px-3 py-1.5 text-xs font-bold text-[var(--gold)] sm:inline-flex">6 core services</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{quickLinks.map(({href,label,description,icon:Icon})=><Link key={href} href={href} className="group menwe-card menwe-interactive rounded-[1.5rem] p-6"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[var(--ink)]/5 text-[var(--ink)] transition group-hover:bg-[var(--gold)]/12 group-hover:text-[var(--accent)]"><Icon size={21}/></span><span className="text-lg font-bold text-[var(--ink)]/25 transition group-hover:text-[var(--accent)]">→</span></div><h3 className="mt-5 text-lg font-extrabold">{label}</h3><p className="mt-2 text-sm leading-6 text-[var(--ink)]/62">{description}</p></Link>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><Link href="/portal/attendance" className="menwe-card menwe-interactive rounded-[1.75rem] p-7"><CalendarDays className="text-[var(--accent)]"/><h2 className="mt-4 text-2xl font-extrabold tracking-[-.025em]">Attendance records</h2><p className="mt-2 text-sm leading-7 text-[var(--ink)]/68">Review the protected attendance workspace for records permitted to your account.</p></Link><Link href="/portal/report-cards" className="menwe-card menwe-interactive rounded-[1.75rem] p-7"><FileText className="text-[var(--accent)]"/><h2 className="mt-4 text-2xl font-extrabold tracking-[-.025em]">Academic performance</h2><p className="mt-2 text-sm leading-7 text-[var(--ink)]/68">Open report cards and academic results for the selected learner.</p></Link></section></>}
    {!learner&&<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{quickLinks.map(({href,label,description,icon:Icon})=><Link key={href} href={href} className="menwe-card menwe-interactive rounded-[1.5rem] p-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[var(--ink)]/5 text-[var(--ink)]"><Icon size={21}/></span><h2 className="mt-5 text-lg font-extrabold">{label}</h2><p className="mt-2 text-sm leading-6 text-[var(--ink)]/62">{description}</p></Link>)}</section>}
    <section><ParentAssistant/></section></main></PortalLayout>;
}
