import { Download, FileText, Search, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { PortalLayout } from "@/components/PortalLayout";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

type Row = Record<string, any>;
const t=(v:any,f="")=>v==null?f:String(v);
export default function PastPapersPage(){
 const {user,profile}=useSchoolAuth(); const [rows,setRows]=useState<Row[]>([]); const [subjects,setSubjects]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState(""); const [subject,setSubject]=useState("ALL"); const [year,setYear]=useState("ALL"); const [msg,setMsg]=useState("");
 const load=async()=>{if(!user||!profile)return;setLoading(true);try{const db=getSupabase();const [r,s]=await Promise.all([db.from("past_papers").select("id,title,description,year,term,paper_type,resource_url,class_id,subject_id,created_at,subjects(name,code),classes(name,level)").eq("status","PUBLISHED").order("year",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}),db.from("subjects").select("id,name,code").eq("status","ACTIVE").order("name")]);if(r.error)throw r.error;if(s.error)throw s.error;setRows(r.data??[]);setSubjects(s.data??[])}catch(e){setMsg(e instanceof Error?e.message:"Past papers could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user,profile]);
 const years=useMemo(()=>Array.from(new Set(rows.map(r=>r.year).filter(Boolean))).sort((a,b)=>Number(b)-Number(a)),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const hay=`${t(r.title)} ${t(r.description)} ${t(r.paper_type)} ${t(r.subjects?.name)} ${t(r.classes?.name)} ${t(r.year)}`.toLowerCase();return hay.includes(q.toLowerCase().trim())&&(subject==="ALL"||t(r.subject_id)===subject)&&(year==="ALL"||t(r.year)===year)}),[rows,q,subject,year]);
 if(!profile)return null;
 return <PortalLayout role={profile.role}><main className="mx-auto w-full max-w-[1440px] space-y-6 px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
  <header className="menwe-portal-hero overflow-hidden rounded-[2rem] p-6 text-white sm:p-8"><span className="menwe-portal-kicker"><ShieldCheck size={14}/> Academic resource centre</span><h1 className="mt-4 font-serif text-4xl font-semibold sm:text-5xl">Past papers & downloads</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">A secure school library for past papers, revision papers, marking schemes and other approved learning resources.</p></header>
  <section className="menwe-card rounded-[1.75rem] p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[1fr_220px_160px]"><label className="relative"><Search size={17} className="absolute left-3 top-3.5 opacity-45"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search papers, subjects or classes" className="min-h-11 w-full rounded-xl border border-[var(--ink)]/12 bg-white pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-[var(--accent)]"/></label><select value={subject} onChange={e=>setSubject(e.target.value)} className="min-h-11 rounded-xl border border-[var(--ink)]/12 bg-white px-3 text-sm"><option value="ALL">All subjects</option>{subjects.map(s=><option key={t(s.id)} value={t(s.id)}>{t(s.name)}</option>)}</select><select value={year} onChange={e=>setYear(e.target.value)} className="min-h-11 rounded-xl border border-[var(--ink)]/12 bg-white px-3 text-sm"><option value="ALL">All years</option>{years.map(y=><option key={t(y)} value={t(y)}>{t(y)}</option>)}</select></div></section>
  {msg&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{msg}</div>}
  {loading?<div className="grid place-items-center rounded-2xl border border-[var(--ink)]/10 p-12 text-sm opacity-60">Loading download centre…</div>:filtered.length===0?<div className="menwe-card rounded-2xl p-10 text-center"><FileText className="mx-auto opacity-35" size={38}/><h2 className="mt-4 text-lg font-semibold">No papers available yet</h2><p className="mx-auto mt-2 max-w-lg text-sm opacity-60">The download centre is ready. Approved past papers can be published by school administrators when the library is populated.</p></div>:<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><article key={t(r.id)} className="menwe-card group rounded-2xl p-5 transition-all duration-300 hover:-translate-y-1.5 hover:shadow-xl"><div className="flex items-start justify-between gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[var(--ink)]/5 text-[var(--ink)]"><FileText size={21}/></span><span className="rounded-full bg-[var(--gold)]/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-[var(--gold)]">{t(r.paper_type)}</span></div><h2 className="mt-5 line-clamp-2 text-lg font-bold text-[var(--ink)]">{t(r.title)}</h2><p className="mt-2 line-clamp-2 text-sm leading-5 opacity-60">{t(r.description,"School-approved academic resource")}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold opacity-60"><span>{t(r.subjects?.name,"General")}</span>{r.year&&<span>· {t(r.year)}</span>}{r.term&&<span>· {t(r.term)}</span>}{r.classes?.name&&<span>· {t(r.classes.name)}</span>}</div><a href={t(r.resource_url)} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 text-sm font-bold text-white transition hover:-translate-y-0.5"><Download size={16}/>Open / download</a></article>)}</section>}
 </main></PortalLayout>
}