import { Download, FileText, Loader2, Plus, Search, ShieldCheck, Upload, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { PortalLayout } from "@/components/PortalLayout";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";

type Row = Record<string, any>;
const t=(v:any,f="")=>v==null?f:String(v);
const input="min-h-11 w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm outline-none transition focus:ring-2 focus:ring-[var(--accent)]";
const cleanName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-120);

export default function PastPapersPage(){
 const {user,profile}=useSchoolAuth(); const [rows,setRows]=useState<Row[]>([]); const [subjects,setSubjects]=useState<Row[]>([]); const [classes,setClasses]=useState<Row[]>([]); const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false); const [q,setQ]=useState(""); const [subject,setSubject]=useState("ALL"); const [year,setYear]=useState("ALL"); const [msg,setMsg]=useState(""); const [showCreate,setShowCreate]=useState(false); const [file,setFile]=useState<File|null>(null);
 const admin=["SUPER_ADMIN","ADMIN","HEAD_OF_INSTITUTION","DEPUTY_HOI"].includes(profile?.role??"");
 const [form,setForm]=useState({title:"",description:"",year:String(new Date().getFullYear()),term:"",paper_type:"Past Paper",class_id:"",subject_id:""});
 const load=async()=>{if(!user||!profile)return;setLoading(true);try{const db=getSupabase();const [r,s,c]=await Promise.all([db.from("past_papers").select("id,title,description,year,term,paper_type,resource_url,storage_path,class_id,subject_id,created_at,subjects(name,code),classes(name,level)").eq("status","PUBLISHED").order("year",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}),db.from("subjects").select("id,name,code").eq("status","ACTIVE").order("name"),db.from("classes").select("id,name,level").eq("status","ACTIVE").order("name")]);if(r.error)throw r.error;if(s.error)throw s.error;if(c.error)throw c.error;setRows(r.data??[]);setSubjects(s.data??[]);setClasses(c.data??[])}catch(e){setMsg(e instanceof Error?e.message:"Past papers could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user,profile]);
 const years=useMemo(()=>Array.from(new Set(rows.map(r=>r.year).filter(Boolean))).sort((a,b)=>Number(b)-Number(a)),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const hay=`${t(r.title)} ${t(r.description)} ${t(r.paper_type)} ${t(r.subjects?.name)} ${t(r.classes?.name)} ${t(r.year)}`.toLowerCase();return hay.includes(q.toLowerCase().trim())&&(subject==="ALL"||t(r.subject_id)===subject)&&(year==="ALL"||t(r.year)===year)}),[rows,q,subject,year]);
 const publish=async(e:React.FormEvent)=>{e.preventDefault();if(!user||!admin||!file){setMsg("Choose a past paper file first.");return}if(file.size>50*1024*1024){setMsg("Files must be 50 MB or smaller.");return}setBusy(true);setMsg("");let storagePath="";try{const db=getSupabase();storagePath=`${user.id}/past-papers/${crypto.randomUUID()}-${cleanName(file.name)}`;const up=await db.storage.from("academic-resources").upload(storagePath,file,{upsert:false,contentType:file.type||undefined});if(up.error)throw up.error;const r=await db.from("past_papers").insert({title:form.title.trim(),description:form.description.trim()||null,year:form.year?Number(form.year):null,term:form.term.trim()||null,paper_type:form.paper_type,class_id:form.class_id||null,subject_id:form.subject_id||null,resource_url:null,storage_path:storagePath,status:"PUBLISHED",created_by:user.id}).select("id").single();if(r.error){await db.storage.from("academic-resources").remove([storagePath]);throw r.error}setForm({title:"",description:"",year:String(new Date().getFullYear()),term:"",paper_type:"Past Paper",class_id:"",subject_id:""});setFile(null);setShowCreate(false);setMsg("Past paper uploaded and published successfully.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Past paper could not be published.")}finally{setBusy(false)}};
 const openPaper=async(r:Row)=>{try{let url=t(r.resource_url);if(r.storage_path){const signed=await getSupabase().storage.from("academic-resources").createSignedUrl(t(r.storage_path),3600);if(signed.error||!signed.data?.signedUrl)throw signed.error??new Error();url=signed.data.signedUrl}const parsed=new URL(url);if(!/^https?:$/.test(parsed.protocol))throw new Error();window.open(parsed.toString(),"_blank","noopener,noreferrer")}catch{setMsg("This paper could not be opened.")}};
 if(!profile)return null;
 return <PortalLayout role={profile.role}><main className="mx-auto w-full max-w-[1440px] space-y-6 px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
  <header className="menwe-portal-hero overflow-hidden rounded-[2rem] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="menwe-portal-kicker"><ShieldCheck size={14}/> Academic resource centre</span><h1 className="mt-4 font-serif text-4xl font-semibold sm:text-5xl">Past papers & downloads</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">A secure school library for past papers, revision papers, marking schemes and other approved learning resources.</p></div>{admin&&<button onClick={()=>setShowCreate(v=>!v)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[var(--ink)]"><Plus size={17}/>{showCreate?"Close":"Upload past paper"}</button>}</div></header>
  {showCreate&&admin&&<form onSubmit={publish} className="menwe-card grid gap-3 rounded-[1.75rem] p-5 sm:p-7 md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-xl font-semibold">Upload a past paper</h2><p className="mt-1 text-sm opacity-60">Files are stored privately. Learners receive temporary secure download links.</p></div><input required maxLength={160} placeholder="Title e.g. Grade 7 Mathematics Term 2 2025" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={input}/><select value={form.paper_type} onChange={e=>setForm({...form,paper_type:e.target.value})} className={input}><option>Past Paper</option><option>Revision Paper</option><option>Marking Scheme</option><option>Notes</option><option>Other</option></select><input type="number" min="2000" max="2100" placeholder="Year" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} className={input}/><input placeholder="Term e.g. Term 1" value={form.term} onChange={e=>setForm({...form,term:e.target.value})} className={input}/><select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})} className={input}><option value="">All classes</option>{classes.map(c=><option key={t(c.id)} value={t(c.id)}>{t(c.name)} · {t(c.level)}</option>)}</select><select value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})} className={input}><option value="">All subjects</option>{subjects.map(s=><option key={t(s.id)} value={t(s.id)}>{t(s.name)} ({t(s.code)})</option>)}</select><label className="md:col-span-2 flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[var(--ink)]/20 bg-white px-4 text-center"><Upload size={21} className="mb-2 opacity-50"/><span className="text-sm font-semibold">{file?file.name:"Choose PDF or document"}</span><span className="mt-1 text-xs opacity-50">PDF, Word, PowerPoint, spreadsheet or text · max 50 MB</span><input required type="file" className="sr-only" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><textarea maxLength={1200} placeholder="Short description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className={`${input} min-h-24 md:col-span-2`}/><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-5 text-sm font-bold text-white disabled:opacity-50 md:w-max">{busy?<Loader2 size={16} className="animate-spin"/>:<Upload size={16}/>} {busy?"Uploading…":"Upload & publish"}</button></form>}
  <section className="menwe-card rounded-[1.75rem] p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[1fr_220px_160px]"><label className="relative"><Search size={17} className="absolute left-3 top-3.5 opacity-45"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search papers, subjects or classes" className={`${input} pl-10`}/></label><select value={subject} onChange={e=>setSubject(e.target.value)} className={input}><option value="ALL">All subjects</option>{subjects.map(s=><option key={t(s.id)} value={t(s.id)}>{t(s.name)}</option>)}</select><select value={year} onChange={e=>setYear(e.target.value)} className={input}><option value="ALL">All years</option>{years.map(y=><option key={t(y)} value={t(y)}>{t(y)}</option>)}</select></div></section>
  {msg&&<div role="status" className="flex items-start justify-between gap-3 rounded-2xl border border-[var(--accent)]/20 bg-[var(--accent)]/8 p-4 text-sm"><span>{msg}</span><button onClick={()=>setMsg("")} aria-label="Dismiss"><X size={17}/></button></div>}
  {loading?<div className="grid place-items-center rounded-2xl border border-[var(--ink)]/10 p-12 text-sm opacity-60"><Loader2 size={22} className="animate-spin"/></div>:filtered.length===0?<div className="menwe-card rounded-2xl p-10 text-center"><FileText className="mx-auto opacity-35" size={38}/><h2 className="mt-4 text-lg font-semibold">No papers available yet</h2><p className="mx-auto mt-2 max-w-lg text-sm opacity-60">{admin?"Upload the first paper above to populate the school download centre.":"The school has not published any papers for your account yet."}</p></div>:<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><article key={t(r.id)} className="group rounded-2xl border border-gray-100 bg-white p-5 shadow-md transition-all duration-300 hover:-translate-y-1.5 hover:shadow-xl dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start justify-between gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#061229]/5 text-[#061229] dark:bg-white/8 dark:text-white"><FileText size={21}/></span><span className="rounded-full bg-[#D89B28]/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-[#D89B28]">{t(r.paper_type)}</span></div><h2 className="mt-5 line-clamp-2 text-lg font-bold text-[#061229] dark:text-white">{t(r.title)}</h2><p className="mt-2 line-clamp-2 text-sm leading-5 opacity-60">{t(r.description,"School-approved academic resource")}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold opacity-60"><span>{t(r.subjects?.name,"General")}</span>{r.year&&<span>· {t(r.year)}</span>}{r.term&&<span>· {t(r.term)}</span>}{r.classes?.name&&<span>· {t(r.classes.name)}</span>}</div><button onClick={()=>void openPaper(r)} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 text-sm font-bold text-white transition hover:-translate-y-0.5"><Download size={16}/>Open / download</button></article>)}</section>}
 </main></PortalLayout>;
}
