import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Loader2, LogOut, Megaphone, RefreshCw, Search, ShieldAlert } from "lucide-react";
import { useLocation } from "wouter";
import { PortalLayout } from "@/components/PortalLayout";
import { isAdministrator, useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabase } from "@/lib/supabase";

type Admission = { id: string; reference_code: string; learner_full_name: string; grade_applied: string; parent_full_name: string; parent_phone: string; created_at: string; status: string; [key: string]: unknown };
type Announcement = { id: string; title: string; content: string; category: string; target_audience: string; author_name: string | null; is_pinned: boolean; created_at: string };
const statuses = ["All", "Pending", "Under Review", "Approved", "Rejected"];
const gradeOptions = ["All Grades", "PP1", "PP2", ...Array.from({ length: 9 }, (_, i) => `Grade ${i + 1}`)];
function Guard({ children }: { children: React.ReactNode }) { const { user, profile, loading } = useSchoolAuth(); const [, go] = useLocation(); useEffect(() => { if (!loading && (!user || !profile || !isAdministrator(profile.role))) go("/portal/login"); }, [loading, profile, user, go]); if (loading) return <div className="grid min-h-screen place-items-center">Loading secure command center…</div>; if (!user || !profile || !isAdministrator(profile.role)) return null; return <>{children}</>; }
export default function PortalAdminPage() { return <Guard><AdminContent /></Guard>; }
function AdminContent() {
 const auth = useSchoolAuth(); const [, go] = useLocation(); const [tab,setTab]=useState<"admissions"|"announcements"|"stats">("admissions"); const [apps,setApps]=useState<Admission[]>([]); const [notices,setNotices]=useState<Announcement[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState("All"); const [grade,setGrade]=useState("All Grades"); const [selected,setSelected]=useState<Admission|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [noticeForm,setNoticeForm]=useState({title:"",content:"",category:"General",target_audience:"All",is_pinned:false});
 const load=async()=>{ setBusy(true); setMessage(""); try { const db=getSupabase(); const [a,n]=await Promise.all([db.from("admissions").select("*").order("created_at",{ascending:false}),db.from("announcements").select("*").order("is_pinned",{ascending:false}).order("created_at",{ascending:false})]); if(a.error) throw a.error; if(n.error) throw n.error; setApps((a.data??[]) as Admission[]); setNotices((n.data??[]) as Announcement[]); } catch(e){setMessage(e instanceof Error?e.message:"Unable to load portal data.");} finally{setBusy(false);} };
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>apps.filter(a=>(status==="All"||a.status===status.toLowerCase().replace(" ","_"))&&(grade==="All Grades"||a.grade_applied===grade)&&[a.learner_full_name,a.reference_code,a.parent_phone].join(" ").toLowerCase().includes(search.toLowerCase().trim())),[apps,grade,search,status]);
 const updateStatus=async(id:string,next:string)=>{try{setBusy(true);const {error}=await getSupabase().from("admissions").update({status:next}).eq("id",id);if(error)throw error;setApps(v=>v.map(a=>a.id===id?{...a,status:next}:a));setSelected(v=>v&&v.id===id?{...v,status:next}:v);}catch(e){setMessage(e instanceof Error?e.message:"Status update failed.");}finally{setBusy(false);}};
 const createNotice=async()=>{if(!noticeForm.title.trim()||!noticeForm.content.trim()){setMessage("Enter a title and notice content.");return;}try{setBusy(true);const {data,error}=await getSupabase().from("announcements").insert([{...noticeForm,author_name:auth.profile?.display_name??auth.user?.email??"Menwe Administration"}]).select().single();if(error)throw error;setNotices(v=>[data as Announcement,...v]);setNoticeForm({title:"",content:"",category:"General",target_audience:"All",is_pinned:false});setMessage("Announcement published.");}catch(e){setMessage(e instanceof Error?e.message:"Announcement could not be published.");}finally{setBusy(false);}};
 const deleteNotice=async(id:string)=>{try{setBusy(true);const {error}=await getSupabase().from("announcements").delete().eq("id",id);if(error)throw error;setNotices(v=>v.filter(n=>n.id!==id));}catch(e){setMessage(e instanceof Error?e.message:"Announcement could not be deleted.");}finally{setBusy(false);}};
 const pending=apps.filter(a=>a.status==="pending").length, under=apps.filter(a=>a.status==="under_review").length, approved=apps.filter(a=>a.status==="approved").length;
 return <PortalLayout role={auth.profile!.role}><main className="mx-auto w-full max-w-7xl box-border min-w-0 overflow-hidden px-4 py-5 sm:px-6 lg:px-8 lg:py-8"><header className="rounded-3xl bg-[#061229] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex min-h-12 items-center rounded-full bg-[#D89B28]/15 px-4 py-2 text-xs font-bold uppercase tracking-wider text-[#D89B28]">Staff Command Center</span><h1 className="mt-4 text-3xl font-extrabold sm:text-4xl">Admissions & School Operations</h1><p className="mt-2 text-sm text-white/65">Live Supabase-backed management for Menwe Primary & Junior School.</p></div><button onClick={async()=>{await auth.signOut();go("/portal/login");}} className="min-h-12 inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 px-4 font-bold transition active:scale-[.98] hover:bg-white/10"><LogOut size={17}/> Sign out</button></div></header>
 <nav className="mt-5 grid grid-cols-1 gap-2 sm:grid-cols-3">{([["admissions","Admissions Requests"],["announcements","Announcements"],["stats","School Stats"]] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`min-h-12 rounded-xl px-4 py-3 text-sm font-bold transition active:scale-[.98] ${tab===id?"bg-[#061229] text-white":"bg-white text-slate-600 border border-slate-200"}`}>{label}</button>)}</nav>
 {message&&<div role="status" className="mt-5 flex gap-2 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800"><AlertCircle size={18}/>{message}</div>}
 {tab==="admissions"&&<section className="mt-6 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search learner, reference or parent phone" className="box-border min-h-12 w-full min-w-0 rounded-xl border border-slate-200 pl-10 pr-4 outline-none focus:ring-2 focus:ring-[#D89B28]"/></label><select value={grade} onChange={e=>setGrade(e.target.value)} className="box-border min-h-12 rounded-xl border border-slate-200 px-4 font-semibold"><option>{gradeOptions[0]}</option>{gradeOptions.slice(1).map(g=><option key={g}>{g}</option>)}</select><button onClick={()=>void load()} className="min-h-12 rounded-xl border border-slate-200 px-4 transition active:scale-[.98]"><RefreshCw size={18}/></button></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{statuses.map(s=><button key={s} onClick={()=>setStatus(s)} className={`min-h-12 shrink-0 rounded-full px-4 text-xs font-bold transition active:scale-[.98] ${status===s?"bg-[#D89B28] text-[#061229]":"bg-slate-100 text-slate-600"}`}>{s}</button>)}</div>{busy&&<div className="my-4 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="animate-spin" size={16}/> Syncing Supabase…</div>}<div className="mt-4 grid grid-cols-1 gap-3">{filtered.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="box-border min-h-[48px] w-full min-w-0 max-w-full rounded-2xl border border-slate-200 p-4 text-left transition hover:border-[#D89B28]/50 active:scale-[.98]"><div className="grid grid-cols-1 gap-3 sm:grid-cols-[1fr_auto]"><div><p className="text-xs font-bold text-[#D89B28]">{a.reference_code}</p><h2 className="mt-1 break-words text-base font-bold text-[#061229]">{a.learner_full_name}</h2><p className="mt-1 break-words text-sm text-slate-500">{a.grade_applied} · {a.parent_full_name} · {a.parent_phone}</p></div><span className="inline-flex min-h-10 items-center justify-center rounded-full bg-slate-100 px-3 text-xs font-bold capitalize text-slate-700">{a.status.replace("_"," ")}</span></div><p className="mt-3 text-xs text-slate-400">Submitted {new Date(a.created_at).toLocaleString("en-KE")}</p></button>)}{!filtered.length&&<p className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">No admissions match the current filters.</p>}</div></section>}
 {tab==="announcements"&&<section className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><Megaphone className="text-[#D89B28]"/><h2 className="text-xl font-bold text-[#061229]">Publish notice</h2></div><input value={noticeForm.title} onChange={e=>setNoticeForm({...noticeForm,title:e.target.value})} placeholder="Notice title" className="mt-5 min-h-12 w-full rounded-xl border border-slate-200 px-4"/><textarea value={noticeForm.content} onChange={e=>setNoticeForm({...noticeForm,content:e.target.value})} placeholder="Official notice content" className="mt-3 min-h-32 w-full rounded-xl border border-slate-200 p-4"/><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2"><input value={noticeForm.category} onChange={e=>setNoticeForm({...noticeForm,category:e.target.value})} placeholder="Category" className="min-h-12 rounded-xl border border-slate-200 px-4"/><select value={noticeForm.target_audience} onChange={e=>setNoticeForm({...noticeForm,target_audience:e.target.value})} className="min-h-12 rounded-xl border border-slate-200 px-4"><option>All</option><option>Parents</option><option>Teachers</option><option>Students</option></select></div><label className="mt-3 flex min-h-12 items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={noticeForm.is_pinned} onChange={e=>setNoticeForm({...noticeForm,is_pinned:e.target.checked})}/> Pin announcement</label><button disabled={busy} onClick={()=>void createNotice()} className="mt-3 min-h-12 w-full rounded-xl bg-[#061229] px-5 font-bold text-white transition active:scale-[.98] disabled:opacity-60">Publish announcement</button></div><div className="grid grid-cols-1 gap-3">{notices.map(n=><article key={n.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-bold uppercase tracking-wider text-[#D89B28]">{n.category}{n.is_pinned?" · Pinned":""}</span><h3 className="mt-2 break-words text-lg font-bold text-[#061229]">{n.title}</h3></div><button onClick={()=>void deleteNotice(n.id)} className="min-h-12 rounded-xl px-3 text-sm font-bold text-red-600 transition active:scale-[.98]">Delete</button></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{n.content}</p></article>)}</div></section>}
 {tab==="stats"&&<section className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Enrolled learners", "students", null],["Pending applications","applications",pending],["Under review","applications",under],["Approved applications","applications",approved]].map(([label,_,value],i)=><article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-3 text-4xl font-black text-[#061229]">{i===0?"—":String(value)}</p></article>)}</section>}
 {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-[#061229]/60 p-0 sm:items-center sm:p-5" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-[#D89B28]">{selected.reference_code}</p><h2 className="mt-2 text-2xl font-bold text-[#061229]">{selected.learner_full_name}</h2></div><button onClick={()=>setSelected(null)} className="min-h-12 rounded-xl bg-slate-100 px-4 font-bold">Close</button></div><dl className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2">{Object.entries(selected).filter(([k])=>!['id','created_at','status'].includes(k)).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><dt className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{k.replaceAll("_"," ")}</dt><dd className="mt-1 break-words text-sm font-semibold text-slate-700">{String(v??"—")}</dd></div>)}</dl><div className="mt-6 grid grid-cols-1 gap-2 sm:grid-cols-3"><button onClick={()=>void updateStatus(selected.id,"under_review")} className="min-h-12 rounded-xl border border-amber-200 bg-amber-50 px-3 font-bold text-amber-800 active:scale-[.98]">Mark Under Review</button><button onClick={()=>void updateStatus(selected.id,"approved")} className="min-h-12 rounded-xl bg-emerald-600 px-3 font-bold text-white active:scale-[.98]">Approve</button><button onClick={()=>void updateStatus(selected.id,"rejected")} className="min-h-12 rounded-xl bg-red-600 px-3 font-bold text-white active:scale-[.98]">Reject / Archive</button></div></section></div>}
 </main></PortalLayout>;
}