import { useEffect, useMemo, useState } from "react";
import { AlertCircle, BarChart3, Bell, BookOpenCheck, CalendarDays, CheckCircle2, CircleDollarSign, FileText, GraduationCap, LogOut, MessageCircle, UserRound, WalletCards } from "lucide-react";
import { useLocation } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { requireSupabaseClient } from "@/lib/supabaseClient";

type Student = Record<string, unknown>;
type Assessment = { subject: string; level: string; updatedAt?: string | null };
type FeePayment = { date: string; amount: number; reference: string };
type Report = { title: string; term: string; url?: string | null; date?: string | null };
type Announcement = { title: string; message: string; author: string; date?: string | null };
type Tab = "cbc" | "fees" | "reports" | "announcements";

const subjects = ["Science & Technology", "Mathematics", "English", "Kiswahili", "Social Studies", "Agriculture"];
const levels = ["Exceeding Expectation", "Meeting Expectation", "Approaching Expectation", "Below Expectation"];
const tabs: { id: Tab; label: string; Icon: typeof BookOpenCheck }[] = [
  { id: "cbc", label: "CBC Assessment Rubric", Icon: BookOpenCheck },
  { id: "fees", label: "Fee Statement", Icon: CircleDollarSign },
  { id: "reports", label: "Report Cards", Icon: FileText },
  { id: "announcements", label: "Notices", Icon: Bell },
];
function text(value: unknown, fallback = "Not published") { return typeof value === "string" && value.trim() ? value : fallback; }
function money(value: unknown) { const n = Number(value); return Number.isFinite(n) ? `KSh ${n.toLocaleString("en-KE")}` : "—"; }
function dateText(value?: string | null) { if (!value) return ""; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString("en-KE", { day: "numeric", month: "short", year: "numeric" }); }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <article className={`rounded-2xl border border-gray-100 bg-white p-4 shadow-md transition-all duration-300 active:scale-[0.98] active:bg-slate-50/80 md:hover:-translate-y-1.5 hover:shadow-xl sm:p-6 ${className}`}>{children}</article>; }
function IconBox({ children }: { children: React.ReactNode }) { return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#061229]/5 text-[#061229] sm:h-12 sm:w-12">{children}</span>; }
function Pill({ children }: { children: React.ReactNode }) { return <span className="inline-flex max-w-full rounded-full bg-[#D89B28]/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-[#D89B28]">{children}</span>; }

export default function PortalDashboardPage() {
  const auth = useSchoolAuth(); const [, go] = useLocation();
  const [tab, setTab] = useState<Tab>("cbc"); const [student, setStudent] = useState<Student | null>(null);
  const [assessments, setAssessments] = useState<Assessment[]>([]); const [payments, setPayments] = useState<FeePayment[]>([]); const [reports, setReports] = useState<Report[]>([]); const [announcements, setAnnouncements] = useState<Announcement[]>([]);
  const [feeBalance, setFeeBalance] = useState<number | null>(null); const [attendance, setAttendance] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [dataMessage, setDataMessage] = useState("");
  useEffect(() => { document.title = "Learner Portal Dashboard | Menwe Primary & Junior School"; }, []);
  useEffect(() => { if (auth.loading) return; if (!auth.user) { go("/portal/login"); return; } let cancelled = false;
    const load = async () => { setLoading(true); setDataMessage(""); try { const supabase = requireSupabaseClient(); const email = auth.user?.email?.toLowerCase() ?? ""; let learner: Student | null = null;
      const studentResult = await supabase.from("students").select("*").eq("student_user_id", auth.user!.id).maybeSingle(); if (!studentResult.error && studentResult.data) learner = studentResult.data as Student;
      if (!learner && email) { const parentResult = await supabase.from("students").select("*").eq("parent_email", email).limit(1).maybeSingle(); if (!parentResult.error && parentResult.data) learner = parentResult.data as Student; }
      if (cancelled) return; setStudent(learner); if (!learner) setDataMessage("Your account is active, but no learner record is linked yet. Please contact the ICT desk.");
      const id = text(learner?.id, ""); if (id) { const [a,p,r,n,f,att] = await Promise.all([
        supabase.from("student_assessments").select("*").eq("student_id", id), supabase.from("fee_payments").select("*").eq("student_id", id).order("payment_date", { ascending: false }).limit(12), supabase.from("report_cards").select("*").eq("student_id", id).order("created_at", { ascending: false }).limit(12), supabase.from("announcements").select("*").eq("published", true).order("created_at", { ascending: false }).limit(8), supabase.from("fee_statements").select("*").eq("student_id", id).order("created_at", { ascending: false }).limit(1).maybeSingle(), supabase.from("attendance").select("*").eq("student_id", id)]);
        if (!cancelled) { if (!a.error && a.data) setAssessments(a.data.map((x: any) => ({ subject: text(x.subject ?? x.learning_area, "Subject"), level: text(x.level ?? x.performance_level), updatedAt: x.updated_at ?? x.created_at ?? null }))); if (!p.error && p.data) setPayments(p.data.map((x: any) => ({ date: text(x.payment_date ?? x.created_at, ""), amount: Number(x.amount ?? x.paid_amount ?? 0), reference: text(x.reference ?? x.receipt_number, "School payment") }))); if (!r.error && r.data) setReports(r.data.map((x: any) => ({ title: text(x.title ?? x.report_type, "Academic report"), term: text(x.term ?? x.academic_term, "School term"), url: x.file_url ?? x.url ?? null, date: x.created_at ?? null }))); if (!n.error && n.data) setAnnouncements(n.data.map((x: any) => ({ title: text(x.title, "School announcement"), message: text(x.message ?? x.content, ""), author: text(x.author_name ?? x.author, "Menwe School Administration"), date: x.created_at ?? null }))); if (!f.error && f.data) setFeeBalance(Number(f.data.balance ?? f.data.outstanding_balance ?? f.data.amount_due ?? 0)); if (!att.error && att.data?.length) { const rows = att.data as any[]; setAttendance(Math.round((rows.filter(x => String(x.status ?? "").toLowerCase() === "present").length / rows.length) * 100)); } }
      }
    } catch (error) { if (!cancelled) setDataMessage(error instanceof Error ? error.message : "Learner records could not be loaded. Please contact ICT."); } finally { if (!cancelled) setLoading(false); } };
    void load(); return () => { cancelled = true; }; }, [auth.loading, auth.user, go]);
  const name = text(student?.full_name ?? student?.student_name ?? student?.name, auth.profile?.display_name ?? "Learner"); const grade = text(student?.grade ?? student?.current_grade ?? student?.class_name, "Learning level not published"); const admission = text(student?.admission_number, "Not linked"); const upi = text(student?.upi_number, "Not linked"); const teacher = text(student?.class_teacher_name ?? student?.teacher_name, "Class teacher not published");
  const performance = useMemo(() => { if (!assessments.length) return "Not yet published"; return levels.find(level => assessments.some(a => a.level.toLowerCase() === level.toLowerCase())) ?? assessments[0].level; }, [assessments]);
  const grouped = subjects.map(subject => ({ subject, record: assessments.find(a => a.subject.toLowerCase() === subject.toLowerCase() || a.subject.toLowerCase().includes(subject.split(" ")[0].toLowerCase())) })); const totalPaid = payments.reduce((sum, p) => sum + (Number.isFinite(p.amount) ? p.amount : 0), 0);
  if (auth.loading || loading) return <PublicLayout><div className="grid min-h-[70vh] place-items-center bg-[#F8F9FA] px-5"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-[#D89B28]/25 border-t-[#D89B28]"/><p className="mt-4 text-sm font-semibold text-slate-600">Loading your secure learner portal…</p></div></div></PublicLayout>;
  return <PublicLayout><main className="min-h-screen bg-[#F8F9FA] pb-16"><section className="bg-[#061229] text-white"><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8 lg:py-14"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><Pill>Secure learner portal</Pill><h1 className="mt-4 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">Welcome, {name}.</h1><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-sm text-white/65"><span className="inline-flex items-center gap-2"><GraduationCap size={16} className="text-[#D89B28]"/>{grade}</span><span className="inline-flex items-center gap-2"><UserRound size={16} className="text-[#D89B28]"/>Teacher: {teacher}</span></div></div><button onClick={async()=>{await auth.signOut();go("/portal/login");}} className="min-h-12 inline-flex items-center justify-center gap-2 self-start rounded-xl border border-white/15 px-4 py-3 text-xs font-bold text-white transition active:scale-[0.98] hover:bg-white/10"><LogOut size={15}/> Sign out</button></div><div className="mt-8 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/5 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-white/45">Admission No.</p><p className="mt-2 break-words font-mono text-sm font-bold">{admission}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-white/45">UPI Number</p><p className="mt-2 break-words font-mono text-sm font-bold">{upi}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-white/45">Account</p><p className="mt-2 text-sm font-bold text-emerald-300">Authenticated & protected</p></div></div></div></section><div className="mx-auto max-w-7xl px-5 lg:px-8">{dataMessage&&<div className="mt-6 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800"><AlertCircle size={18}/><p>{dataMessage}</p></div>}<section className="-mt-5 grid grid-cols-1 gap-4 md:grid-cols-3"><Card><IconBox><CalendarDays size={20}/></IconBox><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">Attendance Rate</p><p className="mt-1 text-3xl font-black text-[#061229]">{attendance===null?"—":`${attendance}%`}</p></Card><Card><IconBox><WalletCards size={20}/></IconBox><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">Current Fee Balance</p><p className="mt-1 text-3xl font-black text-[#061229]">{money(feeBalance)}</p></Card><Card><IconBox><BarChart3 size={20}/></IconBox><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">CBC Performance</p><p className="mt-1 break-words text-xl font-black text-[#061229]">{performance}</p></Card></section>
      <div className="relative mt-8"><div className="pointer-events-none absolute left-0 top-0 z-10 h-full w-5 bg-gradient-to-r from-[#F8F9FA] to-transparent sm:hidden"/><div className="pointer-events-none absolute right-0 top-0 z-10 h-full w-5 bg-gradient-to-l from-[#F8F9FA] to-transparent sm:hidden"/><div className="scrollbar-none -mx-5 flex overflow-x-auto whitespace-nowrap gap-2 pb-2 px-5 sm:mx-0 sm:px-0">{tabs.map(({id,label,Icon})=><button key={id} onClick={()=>setTab(id)} className={`min-h-12 shrink-0 inline-flex items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold transition-all duration-200 active:scale-[0.98] ${tab===id?"bg-[#061229] text-white shadow-md":"bg-white text-slate-500 shadow-sm hover:bg-slate-50"}`}><Icon size={16}/>{label}</button>)}</div></div>
      {tab==="cbc"&&<section className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-[1.4fr_.6fr]"><Card><div className="flex items-start justify-between gap-4"><div><Pill>Competency-Based Curriculum</Pill><h2 className="mt-4 font-serif text-3xl font-semibold text-[#061229]">Learning performance</h2></div><IconBox><BookOpenCheck size={21}/></IconBox></div><div className="mt-7 grid gap-3">{grouped.map(({subject,record})=><div key={subject} className="rounded-xl border border-slate-100 p-4 active:scale-[0.99] transition"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h3 className="text-sm font-bold text-[#061229]">{subject}</h3><span className="max-w-full rounded-full bg-[#D89B28]/10 px-3 py-1 text-[10px] font-bold uppercase text-[#D89B28]">{record?.level??"Not yet published"}</span></div>{record?.updatedAt&&<p className="mt-1 text-[11px] text-slate-400">Updated {dateText(record.updatedAt)}</p>}</div>)}</div></Card><Card><Pill>Reporting scale</Pill><h2 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">CBC rubric levels</h2><div className="mt-6 space-y-3">{levels.map((level,i)=><div key={level} className="flex gap-3 rounded-xl bg-slate-50 p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#061229] text-xs font-bold text-white">{i+1}</span><p className="text-xs font-bold text-[#061229]">{level}</p></div>)}</div></Card></section>}
      {tab==="fees"&&<section className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card><div className="flex items-center gap-3"><IconBox><CircleDollarSign size={20}/></IconBox><div><Pill>Financials</Pill><h2 className="mt-2 font-serif text-2xl font-semibold text-[#061229]">Payment history</h2></div></div><div className="mt-6 overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0"><table className="min-w-[600px] w-full text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs uppercase text-slate-400"><th className="pb-3">Date</th><th className="pb-3">Reference</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{payments.map(p=><tr key={`${p.date}-${p.reference}`} className="border-b border-slate-50"><td className="py-3">{dateText(p.date)}</td><td className="py-3">{p.reference}</td><td className="py-3 text-right font-bold">{money(p.amount)}</td></tr>)}{!payments.length&&<tr><td colSpan={3} className="py-8 text-center text-slate-400">No payment history published.</td></tr>}</tbody></table></div><p className="mt-4 text-xs text-slate-500">Recorded payments total: <strong>{money(totalPaid)}</strong></p></Card><Card><Pill>Receipt request</Pill><h2 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">Need a fee receipt?</h2><p className="mt-3 text-sm leading-6 text-slate-500">Request the latest receipt from the school office through WhatsApp.</p><a href={`https://wa.me/254142550882?text=${encodeURIComponent(`Hello Menwe School, I would like to request a fee receipt for ${name}, admission number ${admission}.`)}`} target="_blank" rel="noreferrer" className="mt-6 min-h-12 w-full inline-flex items-center justify-center gap-2 rounded-xl bg-[#D89B28] px-4 py-3 text-sm font-bold text-[#061229] transition active:scale-[0.98] md:w-auto"><MessageCircle size={17}/> Request via WhatsApp</a></Card></section>}
      {tab==="reports"&&<section className="mt-6"><Card><Pill>Reports</Pill><h2 className="mt-4 font-serif text-3xl font-semibold text-[#061229]">Termly report cards</h2><div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">{reports.map(r=><div key={`${r.title}-${r.term}`} className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-[#061229]">{r.title}</h3><p className="mt-1 text-xs text-slate-500">{r.term}{r.date?` · ${dateText(r.date)}`:""}</p></div>{r.url&&<a href={r.url} target="_blank" rel="noreferrer" className="min-h-11 min-w-11 rounded-xl bg-[#061229] px-3 py-2 text-center text-xs font-bold text-white">View</a>}</div></div>)}{!reports.length&&<p className="text-sm text-slate-500">No reports have been published to your account yet.</p>}</div></Card></section>}
      {tab==="announcements"&&<section className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">{announcements.map(a=><Card key={`${a.title}-${a.date}`}><Pill>School notice</Pill><h2 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">{a.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{a.message}</p><p className="mt-5 text-xs font-bold text-[#D89B28]">{a.author}{a.date?` · ${dateText(a.date)}`:""}</p></Card>)}{!announcements.length&&<Card><p className="text-sm text-slate-500">No announcements are currently published.</p></Card>}</section>}
    </div></main></PublicLayout>;
}
