import { Download, GraduationCap, Loader2, Plus, Printer, ShieldCheck, Trash2, Users } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { getSupabase } from "@/lib/supabase";
import { useSchoolAuth, type AppRole } from "@/contexts/SupabaseAuthContext";
import { PortalLayout } from "@/components/PortalLayout";

type Row = Record<string, any>;
const adminRoles: AppRole[] = ["SUPER_ADMIN", "ADMIN", "HEAD_OF_INSTITUTION", "DEPUTY_HOI"];
const input = "min-h-11 w-full rounded-xl border border-[var(--ink)]/12 bg-white px-3 py-2.5 text-sm outline-none focus:border-[var(--gold)]";
const text = (v: unknown, fallback = "—") => v == null || v === "" ? fallback : String(v);
const roles: string[][] = [
  ["HEAD_PREFECT","President / Head Prefect","EXECUTIVE"],["DEPUTY_HEAD_PREFECT","Deputy Head Prefect","EXECUTIVE"],["PRIMARY_DEPUTY","Primary Section Deputy","EXECUTIVE"],
  ["GAMES_PREFECT","Games Prefect","ACTIVITIES"],["ASSISTANT_GAMES_PREFECT","Assistant Games Prefect","ACTIVITIES"],["DINING_PREFECT","Dining Prefect","WELFARE"],["ASSISTANT_DINING_PREFECT","Assistant Dining Prefect","WELFARE"],
  ["COMPOUND_PREFECT","Compound / Environment Prefect","WELFARE"],["ASSISTANT_COMPOUND_PREFECT","Assistant Compound Prefect","WELFARE"],["GOVERNOR","Governor","LEADERSHIP"],["DEPUTY_GOVERNOR","Deputy Governor","LEADERSHIP"],
  ["TOILETS_PREFECT","Toilets / Sanitation Prefect","WELFARE"],["COMPUTER_PREFECT","Computer Prefect","ACADEMIC"],["SCOUT_COMMANDER","Scout Commander","ACTIVITIES"],["LIBRARY_PREFECT","Library Prefect","ACADEMIC"],["HEALTH_PREFECT","Health & First Aid Prefect","WELFARE"],["TIMEKEEPER","Timekeeper","DISCIPLINE"],
  ...Array.from({length:9},(_,i)=>[`CLASS_G${i+1}_PREFECT`,`Grade ${i+1} Class Prefect`,`CLASS`]),
  ...Array.from({length:9},(_,i)=>[`CLASS_G${i+1}_ASSISTANT`,`Grade ${i+1} Class Prefect Assistant`,`CLASS`]),
];

export default function PrefectsBodyPage() {
  const { user, profile } = useSchoolAuth();
  const admin = !!profile && adminRoles.includes(profile.role);
  const [members,setMembers]=useState<Row[]>([]); const [students,setStudents]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  const [form,setForm]=useState({full_name:"",grade:"",position:"HEAD_PREFECT",category:"EXECUTIVE",student_id:""});
  const load=async()=>{if(!profile)return;setLoading(true);try{const db=getSupabase();const [m,s]=await Promise.all([db.from("prefect_body_members").select("id,full_name,grade,position,category,deputy_for,status,student_id,notes").order("category").order("position"),db.from("students").select("id,first_name,middle_name,last_name,admission_number").is("deleted_at",null).eq("status","ACTIVE").order("first_name")]);if(m.error)throw m.error;if(s.error)throw s.error;setMembers(m.data??[]);setStudents(s.data??[]);}catch(e){setMessage(e instanceof Error?e.message:"Prefects body could not be loaded.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[profile]);
  const vacant=useMemo(()=>roles.filter(([key])=>!members.some(m=>m.position===key&&m.status==="ACTIVE")),[members]);
  const create=async(e:FormEvent)=>{e.preventDefault();if(!admin||!user)return;setBusy(true);setMessage(null);try{const r=await getSupabase().from("prefect_body_members").insert({full_name:form.full_name.trim(),grade:form.grade.trim()||null,position:form.position,category:form.category,student_id:form.student_id||null,status:"ACTIVE",created_by:user.id}).select("id").single();if(r.error)throw r.error;setForm({full_name:"",grade:"",position:"HEAD_PREFECT",category:"EXECUTIVE",student_id:""});setMessage("Prefect added to the body.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Prefect could not be added.")}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!admin||!confirm("Remove this prefect from the active body?"))return;const r=await getSupabase().from("prefect_body_members").update({status:"INACTIVE",updated_at:new Date().toISOString()}).eq("id",id);if(r.error)setMessage(r.error.message);else await load()};
  const exportCsv=()=>{const lines=[["Name","Grade","Position","Category","Status"],...members.map(m=>[m.full_name,m.grade,text(roles.find(r=>r[0]===m.position)?.[1]),m.category,m.status])];const csv=lines.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="menwe-prefects-body.csv";a.click();URL.revokeObjectURL(a.href)};
  if(!profile)return null;
  return <PortalLayout role={profile.role}><main className="mx-auto w-full max-w-[1440px] space-y-6 px-4 py-5 sm:px-6 lg:px-8 lg:py-8"><header className="menwe-portal-hero rounded-[2rem] p-6 text-white sm:p-8"><span className="menwe-portal-kicker"><Users size={14}/> Student leadership</span><h1 className="mt-4 font-serif text-4xl font-semibold sm:text-5xl">Prefects Body</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Manage the school prefect leadership structure, appointments, vacancies and class leadership in one secure place.</p></header>
    {admin&&<section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[var(--ink)]/5"><ShieldCheck size={19}/></span><div><h2 className="text-lg font-bold">Leadership management</h2><p className="text-sm text-[var(--ink)]/55">Add confirmed prefects now; vacant positions remain ready for later appointments.</p></div></div><form onSubmit={create} className="grid gap-3 md:grid-cols-5"><select className={input} value={form.position} onChange={e=>{const r=roles.find(x=>x[0]===e.target.value);setForm({...form,position:e.target.value,category:r?.[2]??"GENERAL"})}}>{roles.map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</select><input required className={input} placeholder="Prefect full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input className={input} placeholder="Grade" value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}/><select className={input} value={form.student_id} onChange={e=>{const s=students.find(x=>x.id===e.target.value);const match=s?.admission_number?.match(/G(\d+)/);setForm({...form,student_id:e.target.value,full_name:s?[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(" "):form.full_name,grade:match?`Grade ${match[1]}`:form.grade})}}><option value="">Link learner record (optional)</option>{students.map(s=><option key={s.id} value={s.id}>{[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(" ")} · {s.admission_number}</option>)}</select><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 text-sm font-bold text-white"><Plus size={16}/>Add prefect</button></form></section>}
    <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[var(--accent)]">Student leadership</p><h2 className="mt-1 text-2xl font-bold">Current prefects</h2><p className="mt-1 text-sm text-[var(--ink)]/55">{members.filter(m=>m.status==="ACTIVE").length} filled · {vacant.length} vacant positions</p></div><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--ink)]/10 bg-white px-3 text-xs font-bold"><Download size={15}/>CSV</button><button onClick={()=>window.print()} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[var(--ink)] px-3 text-xs font-bold text-white"><Printer size={15}/>Print</button></div></div>
      {loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin text-[var(--accent)]"/></div>:<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b border-[var(--ink)]/10 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/45"><th className="p-3">Position</th><th className="p-3">Name</th><th className="p-3">Grade</th><th className="p-3">Category</th>{admin&&<th className="p-3">Manage</th>}</tr></thead><tbody>{roles.map(r=>{const m=members.find(x=>x.position===r[0]&&x.status==="ACTIVE");return <tr key={r[0]} className="border-b border-[var(--ink)]/7"><td className="p-3 font-semibold">{r[1]}</td><td className={`p-3 ${m?"":"italic text-[var(--ink)]/40"}`}>{m?m.full_name:"Vacant — appointment pending"}</td><td className="p-3">{m?.grade??"—"}</td><td className="p-3"><span className="rounded-full bg-[var(--gold)]/10 px-3 py-1 text-[10px] font-black">{r[2]}</span></td>{admin&&<td className="p-3">{m?<button onClick={()=>void remove(m.id)} aria-label={`Remove ${m.full_name}`} className="grid h-9 w-9 place-items-center rounded-lg border border-red-200 text-red-600"><Trash2 size={15}/></button>:<span className="text-xs text-[var(--ink)]/35">Waiting for appointment</span>}</td>}</tr>})}</tbody></table></div>}
    </section>
    {message&&<p role="status" className="rounded-xl border border-[var(--gold)]/20 bg-[var(--gold)]/10 px-4 py-3 text-sm">{message}</p>}
    <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex items-center gap-3"><GraduationCap size={20}/><div><h2 className="font-bold">Day-school leadership structure</h2><p className="text-sm text-[var(--ink)]/55">No boarding or dormitory prefect roles are included.</p></div></div><p className="mt-4 text-sm leading-6 text-[var(--ink)]/65">The body covers executive leadership, games, dining, compound/environment, sanitation, computing, library, scouts, health, timekeeping and Grade 1–9 class prefects with assistants. Missing names can be filled later without rebuilding the structure.</p></section>
  </main></PortalLayout>;
}