import { Archive, FileDown, FileText, Loader2, Printer, Trash2, Users, ExternalLink } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { getSupabase } from "@/lib/supabase";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { PortalLayout } from "@/components/PortalLayout";

type Row = Record<string, any>;
const ADMINS = ["SUPER_ADMIN", "ADMIN", "HEAD_OF_INSTITUTION", "DEPUTY_HOI"];
const esc = (v: unknown) => String(v ?? "").replace(/[&<>\"]/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[c] as string));
const pct = (score: unknown, max: unknown) => { const s=Number(score), m=Number(max); return Number.isFinite(s)&&Number.isFinite(m)&&m>0 ? s/m*100 : null; };
const fmt = (v:number|null) => v==null||!Number.isFinite(v) ? "—" : `${v.toFixed(1)}%`;
const cleanType = (v: unknown) => String(v ?? "").trim().toLowerCase().replace(/[-_\s]+/g, "");
const isOpener = (r: Row) => { const t=cleanType(r.exam_type), n=cleanType(r.name); return ["opener","opening","openerexam","openingexam"].includes(t)||n.includes("opener")||n.includes("opening"); };
const isEndTerm = (r: Row) => { const t=cleanType(r.exam_type), n=cleanType(r.name); return ["endterm","endofterm","final","terminal","terminalexam"].includes(t)||n.includes("endterm")||n.includes("endofterm")||n.includes("terminal")||n.includes("final"); };
const performance = (v:number|null) => v==null ? "—" : v>=80 ? "Exceeding Expectation" : v>=60 ? "Meeting Expectation" : v>=40 ? "Approaching Expectation" : "Below Expectation";
const avgValues = (rows:Row[]) => { const values=rows.map(r=>pct(r.score,r.maximum_score)).filter((v):v is number=>v!=null); return values.length?values.reduce((a,b)=>a+b,0)/values.length:null; };

export default function ReportsHubPage(){
 const {user,profile}=useSchoolAuth(); const [,go]=useLocation(); const admin=ADMINS.includes(profile?.role??"");
 const [students,setStudents]=useState<Row[]>([]),[years,setYears]=useState<Row[]>([]),[terms,setTerms]=useState<Row[]>([]),[classes,setClasses]=useState<Row[]>([]);
 const [yearId,setYearId]=useState(""),[termId,setTermId]=useState(""),[classId,setClassId]=useState(""),[studentId,setStudentId]=useState(""),[mode,setMode]=useState<"term"|"annual">("term");
 const [enrollments,setEnrollments]=useState<Row[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const [savedCount,setSavedCount]=useState(0);
 useEffect(()=>{void(async()=>{if(!user)return;setLoading(true);try{const db=getSupabase();const [s,y,t,c,e]=await Promise.all([
  db.from("students").select("id,admission_number,first_name,middle_name,last_name").eq("status","ACTIVE").order("first_name").order("last_name"),
  db.from("academic_years").select("id,name,is_current,status,starts_on,ends_on").eq("status","ACTIVE").order("starts_on",{ascending:false}),
  db.from("terms").select("id,academic_year_id,name,is_current,status,starts_on,ends_on").eq("status","ACTIVE").order("starts_on",{ascending:false}),
  db.from("classes").select("id,name,code,academic_year_id,status").eq("status","ACTIVE").order("name"),
  db.from("enrollments").select("student_id,class_id,academic_year_id,status").eq("status","ACTIVE")
 ]);for(const q of [s,y,t,c,e])if(q.error)throw q.error;setStudents(s.data??[]);setYears(y.data??[]);setTerms(t.data??[]);setClasses(c.data??[]);setEnrollments(e.data??[]);const yr=y.data?.find((x:any)=>x.is_current)?.id??y.data?.[0]?.id??"";setYearId(String(yr));const tm=t.data?.find((x:any)=>x.is_current&&String(x.academic_year_id)===String(yr))?.id??t.data?.find((x:any)=>String(x.academic_year_id)===String(yr))?.id??"";setTermId(String(tm));}catch(e){setMessage(e instanceof Error?e.message:"Reports centre could not be loaded.")}finally{setLoading(false)}})()},[user]);
 const visibleTerms=useMemo(()=>terms.filter(t=>!yearId||String(t.academic_year_id)===yearId),[terms,yearId]);
 const visibleClasses=useMemo(()=>classes.filter(c=>!yearId||String(c.academic_year_id)===yearId),[classes,yearId]);
 const visibleStudents=useMemo(()=>{let ids=new Set(enrollments.filter(e=>!yearId||String(e.academic_year_id)===yearId).filter(e=>!classId||String(e.class_id)===classId).map(e=>String(e.student_id)));return students.filter(s=>ids.size?ids.has(String(s.id)):!classId)},[students,enrollments,yearId,classId]);
 const chosenStudents=useMemo(()=>studentId?visibleStudents.filter(s=>String(s.id)===studentId):visibleStudents,[visibleStudents,studentId]);
 useEffect(()=>{if(studentId&&!visibleStudents.some(s=>String(s.id)===studentId))setStudentId("")},[visibleStudents,studentId]);
 useEffect(()=>{if(!termId||!visibleTerms.some(t=>String(t.id)===termId))setTermId(String(visibleTerms[0]?.id??""))},[visibleTerms,termId]);
 const resetClass=()=>{setClassId("");setStudentId("")};
 const reportWindow=()=>{const w=window.open("","_blank","noopener,noreferrer");if(!w)throw new Error("Please allow pop-ups so reports can be printed or saved as PDF.");return w};
 const printReports=async()=>{if(!yearId||(mode==="term"&&!termId)||!chosenStudents.length)return;setBusy(true);setMessage(null);try{const db=getSupabase();const year=years.find(y=>String(y.id)===yearId);const term=terms.find(t=>String(t.id)===termId);const htmlParts:string[]=[];
  for(const s of chosenStudents){
   const resultQ=mode==="term"?await db.from("exam_results").select("score,maximum_score,grade,subject_id,teacher_comment,exams!inner(id,name,exam_type,term_id,starts_on,ends_on,status),subjects(name,code)").eq("student_id",s.id).eq("exams.term_id",termId):await db.from("exam_results").select("score,maximum_score,grade,subject_id,teacher_comment,exams!inner(id,name,exam_type,term_id,starts_on,ends_on,status),subjects(name,code)").eq("student_id",s.id);
   if(resultQ.error)throw resultQ.error;let rows=(resultQ.data??[]).filter((r:any)=>r.exams?.status==="PUBLISHED");if(mode==="annual")rows=rows.filter((r:any)=>terms.some(t=>String(t.id)===String(r.exams?.term_id)&&String(t.academic_year_id)===yearId)&& (isOpener(r.exams)||isEndTerm(r.exams)));
   const by=new Map<string,Row[]>();for(const r of rows){const k=String(r.subject_id);by.set(k,[...(by.get(k)??[]),r]);}
   const subjectRows=[...by.entries()].map(([id,items])=>{if(mode==="term"){return{id,name:items[0]?.subjects?.name??"Learning Area",score:avgValues(items),grade:items.map(x=>x.grade).find(Boolean)??"—"};}const opener=avgValues(items.filter(isOpener)),end=avgValues(items.filter(isEndTerm)),average=opener!=null&&end!=null?(opener+end)/2:opener??end;return{id,name:items[0]?.subjects?.name??"Learning Area",opener,end,average};}).filter((x:any)=>mode==="term"?x.score!=null:x.opener!=null||x.end!=null);
   const mean=subjectRows.length?subjectRows.reduce((n:any,x:any)=>n+Number(mode==="term"?x.score:x.average),0)/subjectRows.length:null;
   const name=[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(" ");
   const body=mode==="term"?`<thead><tr><th>Learning Area</th><th>Score</th><th>Grade</th><th>Performance Level</th></tr></thead><tbody>${subjectRows.map((x:any)=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.score)}</td><td>${esc(x.grade)}</td><td>${esc(performance(x.score))}</td></tr>`).join("")}</tbody>`:`<thead><tr><th>Learning Area</th><th>Opener</th><th>End Term</th><th>Average</th><th>Performance Level</th></tr></thead><tbody>${subjectRows.map((x:any)=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.opener)}</td><td>${fmt(x.end)}</td><td>${fmt(x.average)}</td><td>${esc(performance(x.average))}</td></tr>`).join("")}</tbody>`;
   htmlParts.push(`<section class="report"><div class="brand"><div><h1>MENWE JUNIOR SCHOOL</h1><p>${mode==="term"?"LEARNER TERM REPORT":"END-OF-YEAR LEARNER REPORT"}</p></div><div class="meta"><b>Academic Year:</b> ${esc(year?.name??"—")}<br>${mode==="term"?`<b>Term:</b> ${esc(term?.name??"—")}`:`<b>Report:</b> Opener + End Term`}</div></div><div class="identity"><b>Learner:</b> ${esc(name)} &nbsp;&nbsp; <b>Admission:</b> ${esc(s.admission_number)}</div><table>${body}</table><div class="summary"><b>${mode==="term"?"Overall Mean":"Annual Mean"}:</b> ${fmt(mean)} &nbsp; <b>Overall Performance:</b> ${esc(performance(mean))}</div><div class="footer">Generated from published assessment results · Menwe Junior School</div></section>`);
  }
  const w=reportWindow();w.document.write(`<!doctype html><html><head><title>Menwe ${mode==="term"?"Term":"Annual"} Reports</title><style>body{font-family:Arial,sans-serif;color:#061229;margin:0}.report{padding:34px;page-break-after:always}.brand{display:flex;justify-content:space-between;border-bottom:3px solid #D89B28;padding-bottom:14px}.brand h1{margin:0;font-size:22px}.brand p{margin:5px 0 0;font-size:11px;letter-spacing:2px}.meta{text-align:right;font-size:12px}.identity{margin:18px 0;padding:12px;background:#f4f5f1;border-radius:8px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #ccd1d8;padding:8px;text-align:left}th{background:#061229;color:#fff}.summary{margin-top:16px;padding:12px;border:1px solid #ccd1d8}.footer{margin-top:28px;font-size:10px;color:#68707d}@media print{.report{page-break-after:always}}</style></head><body>${htmlParts.join("")}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250);setMessage(`${chosenStudents.length} ${mode==="term"?"term":"annual"} report${chosenStudents.length===1?"":"s"} prepared. Use the print dialog to Save as PDF.`);
 }catch(e){setMessage(e instanceof Error?e.message:"The report pack could not be prepared.")}finally{setBusy(false)}};
 const deleteSavedReports=async()=>{if(!admin||!termId)return;if(!window.confirm(`Delete saved report-card records for ${chosenStudents.length===1?"this learner":"the selected learners"} in ${terms.find(t=>String(t.id)===termId)?.name??"this term"}? This does not delete examination marks.`))return;setBusy(true);setMessage(null);try{const db=getSupabase();for(const s of chosenStudents){const q=await db.from("report_cards").delete().eq("student_id",s.id).eq("term_id",termId);if(q.error)throw q.error;}setSavedCount(0);setMessage("Saved report-card records deleted. Examination marks remain untouched and can be used to regenerate reports.")}catch(e){setMessage(e instanceof Error?e.message:"Saved reports could not be deleted.")}finally{setBusy(false)}};
 useEffect(()=>{void(async()=>{if(!admin||!termId||!chosenStudents.length)return;const r=await getSupabase().from("report_cards").select("id",{count:"exact",head:true}).eq("term_id",termId).in("student_id",chosenStudents.map(s=>s.id));setSavedCount(r.count??0)})()},[admin,termId,chosenStudents]);
 if(loading)return <PortalLayout role={profile?.role??"PARENT"}><main className="mx-auto grid min-h-[60vh] max-w-7xl place-items-center p-8"><Loader2 className="animate-spin"/></main></PortalLayout>;
 return <PortalLayout role={profile?.role??"PARENT"}><main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><div className="grid gap-6">
  <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[var(--gold)]/10 text-[var(--gold)]"><FileText size={22}/></div><div><span className="text-xs font-black uppercase tracking-[.14em] text-[var(--gold)]">Academic records</span><h1 className="mt-1 font-serif text-3xl font-semibold">Reports Centre</h1><p className="mt-1 text-sm text-[var(--ink)]/60">Generate, print, save as PDF, and manage learner reports from one place.</p></div></div><button type="button" onClick={()=>go("/portal/report-cards")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[var(--ink)]/15 px-4 text-sm font-bold"><ExternalLink size={16}/>Open report workspace</button></div>
   <div className="mt-6 flex flex-wrap gap-2"><button type="button" onClick={()=>setMode("term")} className={`rounded-full px-4 py-2 text-sm font-bold ${mode==="term"?"bg-[var(--ink)] text-white":"border border-[var(--ink)]/15"}`}>Term report</button><button type="button" onClick={()=>setMode("annual")} className={`rounded-full px-4 py-2 text-sm font-bold ${mode==="annual"?"bg-[var(--ink)] text-white":"border border-[var(--ink)]/15"}`}>End-of-year report</button></div>
   <div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1.5 text-sm font-semibold">Academic year<select value={yearId} onChange={e=>{setYearId(e.target.value);setClassId("");setStudentId("")}} className="min-h-11 rounded-xl border border-[var(--ink)]/15 bg-white px-3"><option value="">Select year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label>{mode==="term"&&<label className="grid gap-1.5 text-sm font-semibold">Term<select value={termId} onChange={e=>setTermId(e.target.value)} className="min-h-11 rounded-xl border border-[var(--ink)]/15 bg-white px-3"><option value="">Select term</option>{visibleTerms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<label className="grid gap-1.5 text-sm font-semibold">Class<select value={classId} onChange={e=>{setClassId(e.target.value);setStudentId("")}} className="min-h-11 rounded-xl border border-[var(--ink)]/15 bg-white px-3"><option value="">All classes</option>{visibleClasses.map(c=><option key={c.id} value={c.id}>{c.name}{c.code?` · ${c.code}`:""}</option>)}</select></label><label className="grid gap-1.5 text-sm font-semibold">Learner<select value={studentId} onChange={e=>setStudentId(e.target.value)} className="min-h-11 rounded-xl border border-[var(--ink)]/15 bg-white px-3"><option value="">All learners</option>{visibleStudents.map(s=><option key={s.id} value={s.id}>{[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(" ")} · {s.admission_number}</option>)}</select></label></div>
  </section>
  <section className="grid gap-4 md:grid-cols-4"><div className="menwe-card rounded-2xl p-5"><div className="flex items-center gap-3"><Users className="text-[var(--gold)]"/><div><p className="text-xs font-bold uppercase opacity-60">Selected learners</p><p className="text-2xl font-bold">{chosenStudents.length}</p></div></div></div><div className="menwe-card rounded-2xl p-5"><div className="flex items-center gap-3"><FileDown className="text-[var(--gold)]"/><div><p className="text-xs font-bold uppercase opacity-60">Report type</p><p className="text-sm font-bold">{mode==="term"?"Term report":"Annual report"}</p></div></div></div><div className="menwe-card rounded-2xl p-5"><div className="flex items-center gap-3"><Printer className="text-[var(--gold)]"/><div><p className="text-xs font-bold uppercase opacity-60">Output</p><p className="text-sm font-bold">Print / Save PDF</p></div></div></div><div className="menwe-card rounded-2xl p-5"><div className="flex items-center gap-3"><Archive className="text-[var(--gold)]"/><div><p className="text-xs font-bold uppercase opacity-60">Saved cards</p><p className="text-sm font-bold">{admin?`${savedCount} saved`:"Protected"}</p></div></div></div></section>
  <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-serif text-2xl font-semibold">Report actions</h2><p className="mt-1 text-sm opacity-60">{studentId?"One learner selected.":classId?"Whole class selected.":"All accessible learners selected."} Choose an action below.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy||!yearId||(mode==="term"&&!termId)||!chosenStudents.length} onClick={()=>void printReports()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-5 text-sm font-bold text-white disabled:opacity-50"><Printer size={16}/>{studentId?"Print individual report":"Print bulk report pack"}</button>{admin&&mode==="term"&&<button type="button" disabled={busy||!termId||!chosenStudents.length} onClick={()=>void deleteSavedReports()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-red-200 px-4 text-sm font-bold text-red-700 disabled:opacity-50"><Trash2 size={16}/>Delete saved reports</button>}</div></div>{message&&<p className="mt-4 rounded-xl bg-[var(--gold)]/10 p-3 text-sm">{message}</p>}
   <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Learner</th><th className="p-3">Admission</th><th className="p-3">Class</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{visibleStudents.map(s=>{const c=enrollments.find(e=>String(e.student_id)===String(s.id)&&String(e.academic_year_id)===yearId);return <tr key={s.id} className={`border-b ${studentId===String(s.id)?"bg-[var(--gold)]/5":""}`}><td className="p-3 font-semibold">{[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(" ")}</td><td className="p-3">{s.admission_number}</td><td className="p-3">{classes.find(x=>String(x.id)===String(c?.class_id))?.name??"—"}</td><td className="p-3 text-right"><button type="button" onClick={()=>{setStudentId(String(s.id));window.scrollTo({top:0,behavior:"smooth"})}} className="inline-flex items-center gap-2 rounded-lg border border-[var(--ink)]/15 px-3 py-2 text-xs font-bold"><FileText size={14}/>Select learner</button></td></tr>})}</tbody></table>{!visibleStudents.length&&<div className="grid place-items-center py-12 text-sm opacity-60">No accessible learners match these filters.</div>}</div>
  </section>
 </div></main></PortalLayout>;
}
