import { useEffect,useState } from "react";
import { BookOpen,Plus,RefreshCw,RotateCcw } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { isAdministrator,useSchoolAuth,type AppRole } from "@/contexts/SupabaseAuthContext";
const TYPES=["COURSE_BOOK","TEACHER_GUIDE","CURRICULUM_DESIGN","SCHEMES_OF_WORK","ANSWER_BOOK","RECORD_BOOK","TEACHER_REFERENCE","ASSESSMENT_MATERIAL","MANUAL","OTHER"];
export default function TeacherResourcesPage(){
 const {profile}=useSchoolAuth();const admin=isAdministrator(profile?.role as AppRole);const [items,setItems]=useState<any[]>([]),[loans,setLoans]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[title,setTitle]=useState(""),[type,setType]=useState(TYPES[0]),[item,setItem]=useState(""),[teacher,setTeacher]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);const s=getSupabase();const [a,b]=await Promise.all([s.from("teacher_library_items").select("*").order("title"),s.from("teacher_library_loans").select("*,item:teacher_library_items(title,item_type),teacher:teachers(first_name,last_name)").order("issued_at",{ascending:false})]);if(a.error||b.error)setError((a.error||b.error)!.message);else{setItems(a.data||[]);setLoans(b.data||[])}if(admin){const t=await s.from("teachers").select("id,first_name,last_name").eq("status","ACTIVE").order("first_name");setTeachers(t.data||[])}setLoading(false)};useEffect(()=>{void load()},[admin]);
 const add=async()=>{if(!title.trim())return;const n=1;const {error:e}=await getSupabase().from("teacher_library_items").insert({title,item_type:type,total_copies:n,available_copies:n,condition:"GOOD",status:"AVAILABLE"});if(e)setError(e.message);else{setTitle("");await load()}};
 const issue=async()=>{const {error:e}=await getSupabase().rpc("teacher_library_issue",{p_item_id:item,p_teacher_id:teacher,p_due_at:null,p_notes:null});if(e)setError(e.message);else{setItem("");setTeacher("");await load()}};
 const receive=async(id:string)=>{const {error:e}=await getSupabase().rpc("teacher_library_return",{p_loan_id:id,p_notes:null});if(e)setError(e.message);else await load()};
 if(loading)return <main className="p-10 text-center">Loading teacher resources…</main>;
 return <main className="mx-auto max-w-7xl px-4 py-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#D89B28]">Staff Library</p><h1 className="text-3xl font-black text-[#061229]">Teacher Resource Register</h1><p className="mt-2 text-sm text-slate-600">Course books, teacher guides, curriculum designs, schemes, answer books, record books and professional references.</p></div><button onClick={()=>void load()} className="rounded-xl border bg-white p-3"><RefreshCw size={17}/></button></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 {admin&&<section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-black">Add staff resource</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border p-3">{TYPES.map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Resource title" className="rounded-xl border p-3"/><button onClick={()=>void add()} className="rounded-xl bg-[#061229] px-4 font-bold text-white"><Plus size={16} className="mr-2 inline"/>Add</button></div></section>}
 {admin&&<section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-black">Issue resource to teacher</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><select value={item} onChange={e=>setItem(e.target.value)} className="rounded-xl border p-3"><option value="">Select resource</option>{items.filter(x=>x.available_copies>0).map(x=><option key={x.id} value={x.id}>{x.title} ({x.available_copies})</option>)}</select><select value={teacher} onChange={e=>setTeacher(e.target.value)} className="rounded-xl border p-3"><option value="">Select teacher</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.first_name} {x.last_name}</option>)}</select><button onClick={()=>void issue()} className="rounded-xl bg-[#D89B28] font-bold">Issue resource</button></div></section>}
 <section className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[700px] w-full text-left text-sm"><thead className="bg-[#061229] text-white"><tr><th className="p-4">Resource</th><th>Type</th><th>Stock</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-t"><td className="p-4 font-bold">{x.title}</td><td>{x.item_type.replaceAll("_"," ")}</td><td>{x.available_copies} / {x.total_copies}</td><td>{x.status}</td></tr>)}{!items.length&&<tr><td colSpan={4} className="p-10 text-center text-slate-500">No teacher resources registered yet.</td></tr>}</tbody></table></section>
 <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-black">Current staff loans</h2><div className="mt-3 space-y-2">{loans.filter(x=>!x.returned_at&&x.status==='ISSUED').map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-4"><span><b>{x.item?.title}</b><small className="ml-2 text-slate-500">{x.teacher?.first_name} {x.teacher?.last_name}</small></span>{admin&&<button onClick={()=>void receive(x.id)} className="rounded-lg border px-3 py-2 text-xs font-bold"><RotateCcw size={14} className="mr-1 inline"/>Receive</button>}</div>)}{!loans.some(x=>!x.returned_at&&x.status==='ISSUED')&&<p className="text-sm text-slate-500">No resources currently issued.</p>}</div></section></main>;
}