import { Loader2, Plus, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabase } from "@/lib/supabase";

type Row = Record<string, unknown>;
const text = (value: unknown, fallback = "") => value === null || value === undefined ? fallback : String(value);
const inputClass = "w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm outline-none ring-[var(--accent)] focus:ring-2";

export default function TeacherAssignmentsDirectory() {
  const { profile } = useSchoolAuth(); const [teachers,setTeachers]=useState<Row[]>([]),[classes,setClasses]=useState<Row[]>([]),[subjects,setSubjects]=useState<Row[]>([]),[assignments,setAssignments]=useState<Row[]>([]); const [teacherId,setTeacherId]=useState(""),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""); const [busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null); const isAdmin=["SUPER_ADMIN","ADMIN"].includes(profile?.role||"");
  const refresh=useCallback(async()=>{try{const db=getSupabase();const [tr,cr,sr,ar]=await Promise.all([isAdmin?db.from("teachers").select("id,profile_id,employee_number,first_name,middle_name,last_name,email,status").eq("status","ACTIVE").order("last_name"):Promise.resolve({data:[],error:null} as any),db.from("classes").select("id,name,level,code,status").eq("status","ACTIVE").order("name"),db.from("subjects").select("id,name,code,status").eq("status","ACTIVE").order("name"),db.from("teacher_assignments").select("id,teacher_id,class_id,subject_id,created_at").order("created_at",{ascending:false})]);for(const r of [tr,cr,sr,ar])if(r.error)throw r.error;setTeachers(tr.data??[]);setClasses(cr.data??[]);setSubjects(sr.data??[]);setAssignments(ar.data??[]);}catch(e){setMessage(e instanceof Error?e.message:"Teacher assignments could not be loaded.");}},[isAdmin]);
  useEffect(()=>{void refresh()},[refresh]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!isAdmin||!teacherId||!classId||!subjectId)return;setBusy(true);setMessage(null);try{const {error}=await getSupabase().from("teacher_assignments").insert({teacher_id:teacherId,class_id:classId,subject_id:subjectId});if(error)throw error;setTeacherId("");setClassId("");setSubjectId("");setMessage("Teacher assignment saved.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"The teacher assignment could not be saved.");}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!isAdmin||!window.confirm("Remove this teacher assignment?"))return;setBusy(true);setMessage(null);try{const {error}=await getSupabase().from("teacher_assignments").delete().eq("id",id);if(error)throw error;setMessage("Teacher assignment removed.");await refresh();}catch(e){setMessage(e instanceof Error?e.message:"The assignment could not be removed.");}finally{setBusy(false)}};
  const teacherName=(id:string)=>{const r=teachers.find(x=>text(x.id)===id);return r?[r.first_name,r.middle_name,r.last_name].filter(Boolean).join(" ")||text(r.email,id):id}; const className=(id:string)=>{const r=classes.find(x=>text(x.id)===id);return r?`${text(r.name)}${r.code?` · ${text(r.code)}`:""}`:id}; const subjectName=(id:string)=>{const r=subjects.find(x=>text(x.id)===id);return r?`${text(r.name)}${r.code?` · ${text(r.code)}`:""}`:id};
  return <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><h2 className="font-serif text-2xl font-semibold tracking-tight">Teacher assignments</h2><p className="mt-2 text-sm leading-6 text-[var(--ink)]/60">Assign teachers to a class and subject. These assignments are the access source for teaching workflows.</p>{isAdmin&&<form onSubmit={create} className="mt-6 grid gap-3 lg:grid-cols-4"><select required value={teacherId} onChange={e=>setTeacherId(e.target.value)} className={inputClass}><option value="">Select teacher</option>{teachers.map(r=><option key={text(r.id)} value={text(r.id)}>{teacherName(text(r.id))}{r.employee_number?` · ${text(r.employee_number)}`:""}</option>)}</select><select required value={classId} onChange={e=>setClassId(e.target.value)} className={inputClass}><option value="">Select class</option>{classes.map(r=><option key={text(r.id)} value={text(r.id)}>{text(r.name)}{r.code?` · ${text(r.code)}`:""}</option>)}</select><select required value={subjectId} onChange={e=>setSubjectId(e.target.value)} className={inputClass}><option value="">Select subject</option>{subjects.map(r=><option key={text(r.id)} value={text(r.id)}>{text(r.name)}{r.code?` · ${text(r.code)}`:""}</option>)}</select><button disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-55">{busy?<Loader2 className="animate-spin" size={16}/>:<Plus size={16}/>}Assign</button></form>}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-[var(--ink)]/10 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/45"><th className="px-3 py-3">Teacher</th><th className="px-3 py-3">Class</th><th className="px-3 py-3">Subject</th>{isAdmin&&<th className="px-3 py-3">Action</th>}</tr></thead><tbody>{assignments.map(r=><tr key={text(r.id)} className="border-b border-[var(--ink)]/7 last:border-0"><td className="px-3 py-3 font-semibold">{teacherName(text(r.teacher_id))}</td><td className="px-3 py-3">{className(text(r.class_id))}</td><td className="px-3 py-3">{subjectName(text(r.subject_id))}</td>{isAdmin&&<td className="px-3 py-3"><button type="button" disabled={busy} onClick={()=>void remove(text(r.id))} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-2 py-1 text-xs font-semibold text-red-700"><Trash2 size={13}/>Remove</button></td>}</tr>)}{assignments.length===0&&<tr><td colSpan={isAdmin?4:3} className="px-3 py-8 text-center text-sm text-[var(--ink)]/55">No teacher assignments have been created yet. An administrator can assign a teacher to a class and subject above.</td></tr>}</tbody></table></div>{message&&<p role="status" className="mt-4 rounded-xl bg-[var(--sage)]/16 px-4 py-3 text-sm text-[var(--accent)]">{message}</p>}</section>;
}
