import { useEffect, useMemo, useState } from "react";
import { Download, ExternalLink, FileText, FileUp, Link2, Loader2, Plus, RefreshCw, Search, Trash2, Upload, X } from "lucide-react";
import { getSupabase } from "@/lib/supabase";
import { isAdministrator, useSchoolAuth, type AppRole } from "@/contexts/SupabaseAuthContext";

const RESOURCE_TYPES = [["SCHEME_OF_WORK","Scheme of Work"],["LESSON_PLAN","Lesson Plan"],["RECORD_BOOK","Record Book"],["TEACHER_NOTES","Teacher Notes"],["LEARNER_NOTES","Learner Notes"],["REVISION_MATERIAL","Revision Material"],["PAST_PAPER","Past Paper"],["ASSIGNMENT","Assignment"],["TEACHER_GUIDE","Teacher Guide"],["CURRICULUM_DESIGN","Curriculum Design"],["ANSWER_BOOK","Answer Book"],["OTHER","Other"]] as const;
const MAX_FILE_SIZE = 15 * 1024 * 1024;
const ALLOWED_EXTENSIONS = ["pdf","doc","docx","xls","xlsx","ppt","pptx","txt","jpg","jpeg","png"];
const ALLOWED_MIME_TYPES = new Set(["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation","text/plain","image/jpeg","image/png"]);
const typeLabel = (v:string) => RESOURCE_TYPES.find(([k]) => k === v)?.[1] ?? v.replaceAll("_"," ");
const formatSize = (n?:number|null) => !n ? "—" : n < 1024 ? n+" B" : n < 1048576 ? (n/1024).toFixed(0)+" KB" : (n/1048576).toFixed(1)+" MB";

export default function TeacherResourcesPage(){
 const {profile,user}=useSchoolAuth(); const role=profile?.role as AppRole|undefined; const admin=isAdministrator(role); const teacher=role==="TEACHER"; const canUpload=admin||teacher;
 const [resources,setResources]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[terms,setTerms]=useState<any[]>([]),[years,setYears]=useState<any[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[typeFilter,setTypeFilter]=useState("ALL"),[audienceFilter,setAudienceFilter]=useState("ALL"),[statusFilter,setStatusFilter]=useState("ALL"),[showUpload,setShowUpload]=useState(false);
 const [sourceType,setSourceType]=useState<"FILE"|"LINK">("FILE"),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[resourceType,setResourceType]=useState("REVISION_MATERIAL"),[audience,setAudience]=useState("BOTH"),[status,setStatus]=useState("PUBLISHED"),[subjectId,setSubjectId]=useState(""),[classId,setClassId]=useState(""),[termId,setTermId]=useState(""),[academicYearId,setAcademicYearId]=useState(""),[externalUrl,setExternalUrl]=useState(""),[file,setFile]=useState<File|null>(null);
 const load=async()=>{setLoading(true);setError("");const s=getSupabase();const rq=s.from("school_resources").select("*,subject:subjects(name,code),class:classes(name,level),term:terms(name),academic_year:academic_years(name),teacher:teachers(first_name,last_name)").order("created_at",{ascending:false});if(!admin&&!teacher)rq.eq("status","PUBLISHED");const [r,sub,cls,trm,yr]=await Promise.all([rq,s.from("subjects").select("id,name,code").order("name"),s.from("classes").select("id,name,level").eq("status","ACTIVE").order("name"),s.from("terms").select("id,name,academic_year_id,is_current").eq("status","ACTIVE").order("starts_on"),s.from("academic_years").select("id,name,is_current,status").eq("status","ACTIVE").order("starts_on",{ascending:false})]);const e=r.error||sub.error||cls.error||trm.error||yr.error;if(e)setError(e.message);setResources(r.data||[]);setSubjects(sub.data||[]);setClasses(cls.data||[]);setTerms(trm.data||[]);setYears(yr.data||[]);setLoading(false)};
 useEffect(()=>{void load()},[admin,teacher]);
 const visibleTerms=useMemo(()=>terms.filter(t=>!academicYearId||t.academic_year_id===academicYearId),[terms,academicYearId]);
 const filtered=useMemo(()=>resources.filter(r=>{const hay=(r.title+" "+(r.description||"")+" "+(r.subject?.name||"")+" "+(r.class?.name||"")+" "+(r.original_file_name||"")).toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(typeFilter==="ALL"||r.resource_type===typeFilter)&&(audienceFilter==="ALL"||r.audience===audienceFilter)&&(statusFilter==="ALL"||r.status===statusFilter)}),[resources,query,typeFilter,audienceFilter,statusFilter]);
 const resetForm=()=>{setSourceType("FILE");setTitle("");setDescription("");setResourceType("REVISION_MATERIAL");setAudience("BOTH");setStatus("PUBLISHED");setSubjectId("");setClassId("");setTermId("");setAcademicYearId(years.find(y=>y.is_current)?.id||"");setExternalUrl("");setFile(null)};
 const save=async()=>{if(!canUpload||!user||!title.trim())return;setBusy(true);setError("");let uploadedPath:string|null=null;try{const s=getSupabase();let teacherId:string|null=null;if(teacher){const {data:t,error:e}=await s.from("teachers").select("id").eq("profile_id",user.id).eq("status","ACTIVE").maybeSingle();if(e||!t)throw new Error(e?.message||"Your active teacher record could not be found.");teacherId=t.id}let filePath:string|null=null,originalFileName:string|null=null,mimeType:string|null=null,fileSize:number|null=null;if(sourceType==="FILE"){if(!file)throw new Error("Choose a file to upload.");if(file.size>MAX_FILE_SIZE)throw new Error("File is too large. Maximum upload size is 15 MB.");const ext=file.name.split(".").pop()?.toLowerCase()||"";if(!ALLOWED_EXTENSIONS.includes(ext)||!ALLOWED_MIME_TYPES.has(file.type))throw new Error("Unsupported file type. Approved school document, presentation, spreadsheet, image or PDF only.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");filePath=(teacherId||"admin")+"/"+crypto.randomUUID()+"-"+safe;uploadedPath=filePath;const {error:e}=await s.storage.from("school-resources").upload(filePath,file,{contentType:file.type,upsert:false});if(e)throw e;originalFileName=file.name;mimeType=file.type;fileSize=file.size}else{if(!/^https:\/\//i.test(externalUrl.trim()))throw new Error("Educational links must use HTTPS.")}const {error:e}=await s.from("school_resources").insert({title:title.trim(),description:description.trim()||null,resource_type:resourceType,audience,subject_id:subjectId||null,class_id:classId||null,term_id:termId||null,academic_year_id:academicYearId||null,uploaded_by_teacher_id:teacherId,file_path:filePath,external_url:sourceType==="LINK"?externalUrl.trim():null,original_file_name:originalFileName,mime_type:mimeType,file_size:fileSize,status});if(e){if(uploadedPath)await s.storage.from("school-resources").remove([uploadedPath]);throw e}resetForm();setShowUpload(false);await load()}catch(e){setError(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}};
 const openResource=async(r:any)=>{setError("");if(r.external_url){window.open(r.external_url,"_blank","noopener,noreferrer");return}const {data,error:e}=await getSupabase().storage.from("school-resources").createSignedUrl(r.file_path,300,{download:r.original_file_name||true});if(e||!data?.signedUrl){setError(e?.message||"Could not prepare the secure download.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const removeResource=async(r:any)=>{if(!window.confirm("Delete \""+r.title+"\"?"))return;setBusy(true);setError("");try{const s=getSupabase();const {error:e}=await s.from("school_resources").delete().eq("id",r.id);if(e)throw e;if(r.file_path)await s.storage.from("school-resources").remove([r.file_path]);await load()}catch(e){setError(e instanceof Error?e.message:"Could not delete the resource.")}finally{setBusy(false)}};
 if(loading)return <main className="flex min-h-[60vh] items-center justify-center"><Loader2 className="animate-spin"/></main>;
 return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><header className="rounded-3xl bg-[#061229] p-6 text-white shadow-sm md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#D89B28]">Academic Resources</p><h1 className="mt-2 text-3xl font-black">Resources Library</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Securely share revision notes, exams, assignments, schemes of work, curriculum designs, presentations and approved educational links.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-white/20 bg-white/10 p-3"><RefreshCw size={18}/></button>{canUpload&&<button onClick={()=>{resetForm();setShowUpload(true)}} className="rounded-xl bg-[#D89B28] px-4 py-3 font-bold text-[#061229]"><Plus size={17} className="mr-2 inline"/>Add resource</button>}</div></div></header>
 {error&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <section className="mt-5 grid gap-3 lg:grid-cols-[1fr_220px_180px_160px]"><label className="flex items-center gap-2 rounded-xl border bg-white px-3"><Search size={17} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resources, subjects or classes…" className="w-full bg-transparent p-3 outline-none"/></label><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} className="rounded-xl border bg-white p-3"><option value="ALL">All resource types</option>{RESOURCE_TYPES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select value={audienceFilter} onChange={e=>setAudienceFilter(e.target.value)} className="rounded-xl border bg-white p-3"><option value="ALL">All audiences</option><option value="TEACHERS">Teachers</option><option value="LEARNERS">Learners</option><option value="BOTH">Teachers & learners</option></select>{(admin||teacher)&&<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl border bg-white p-3"><option value="ALL">All status</option><option value="PUBLISHED">Published</option><option value="DRAFT">Draft</option><option value="ARCHIVED">Archived</option></select>}</section>
 <section className="mt-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Resources</p><p className="mt-1 text-3xl font-black text-[#061229]">{resources.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Showing</p><p className="mt-1 text-3xl font-black text-[#061229]">{filtered.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">Access</p><p className="mt-2 font-bold">{canUpload?(admin?"Administrator upload & management":"Teacher upload & own management"):"Published resources only"}</p></div></section>
 <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=><article key={r.id} className="rounded-2xl border bg-white p-5 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-slate-100 p-3">{r.external_url?<Link2 size={21}/>:<FileText size={21}/>}</div><div className="flex gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{r.status}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{r.audience==="BOTH"?"Teachers + learners":r.audience==="TEACHERS"?"Teachers":"Learners"}</span></div></div><h2 className="mt-4 font-black text-[#061229]">{r.title}</h2><p className="mt-1 text-xs font-bold uppercase tracking-wide text-[#D89B28]">{typeLabel(r.resource_type)}</p><p className="mt-2 line-clamp-2 text-sm text-slate-600">{r.description||r.original_file_name||r.external_url}</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500">{r.subject?.name&&<span className="rounded-lg bg-slate-50 px-2 py-1">{r.subject.name}</span>}{r.class?.name&&<span className="rounded-lg bg-slate-50 px-2 py-1">{r.class.name}</span>}{r.term?.name&&<span className="rounded-lg bg-slate-50 px-2 py-1">{r.term.name}</span>}{r.academic_year?.name&&<span className="rounded-lg bg-slate-50 px-2 py-1">{r.academic_year.name}</span>}{r.file_size&&<span className="rounded-lg bg-slate-50 px-2 py-1">{formatSize(r.file_size)}</span>}</div><div className="mt-4 flex justify-end gap-2 border-t pt-3"><button onClick={()=>void openResource(r)} className="rounded-lg bg-[#061229] px-3 py-2 text-xs font-bold text-white">{r.external_url?<><ExternalLink size={14} className="mr-1 inline"/>Open link</>:<><Download size={14} className="mr-1 inline"/>Download</>}</button>{(admin||teacher)&&<button disabled={busy} onClick={()=>void removeResource(r)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 size={14}/></button>}</div></article>)}{!filtered.length&&<div className="rounded-2xl border bg-white p-10 text-center text-slate-500 md:col-span-2 xl:col-span-3">No resources match your search.</div>}</section>
 {showUpload&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#D89B28]">{admin?"Administrator":"Teacher"} upload</p><h2 className="text-2xl font-black text-[#061229]">Add school resource</h2></div><button onClick={()=>setShowUpload(false)} className="rounded-xl border p-2"><X size={18}/></button></div>
 <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="text-sm font-bold">Title *</span><input value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 w-full rounded-xl border p-3" placeholder="e.g. Grade 7 Mathematics Revision Notes"/></label><label className="md:col-span-2"><span className="text-sm font-bold">Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3"/></label><label><span className="text-sm font-bold">Category *</span><select value={resourceType} onChange={e=>setResourceType(e.target.value)} className="mt-1 w-full rounded-xl border p-3">{RESOURCE_TYPES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label><span className="text-sm font-bold">Audience *</span><select value={audience} onChange={e=>setAudience(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="TEACHERS">Teachers</option><option value="LEARNERS">Learners</option><option value="BOTH">Teachers & learners</option></select></label><label><span className="text-sm font-bold">Subject</span><select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">All / not specified</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span className="text-sm font-bold">Grade / Class</span><select value={classId} onChange={e=>setClassId(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">All / not specified</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="text-sm font-bold">Academic year</span><select value={academicYearId} onChange={e=>setAcademicYearId(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">Not specified</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?" (Current)":""}</option>)}</select></label><label><span className="text-sm font-bold">Term</span><select value={termId} onChange={e=>setTermId(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="">Not specified</option>{visibleTerms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span className="text-sm font-bold">Status *</span><select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="PUBLISHED">Published</option><option value="DRAFT">Draft</option>{admin&&<option value="ARCHIVED">Archived</option>}</select></label>
 <div className="md:col-span-2 rounded-2xl border bg-slate-50 p-4"><div className="flex gap-2"><button type="button" onClick={()=>setSourceType("FILE")} className={sourceType==="FILE"?"rounded-xl bg-[#061229] px-4 py-2 text-sm font-bold text-white":"rounded-xl border bg-white px-4 py-2 text-sm font-bold"}><FileUp size={15} className="mr-2 inline"/>Upload file</button><button type="button" onClick={()=>setSourceType("LINK")} className={sourceType==="LINK"?"rounded-xl bg-[#061229] px-4 py-2 text-sm font-bold text-white":"rounded-xl border bg-white px-4 py-2 text-sm font-bold"}><Link2 size={15} className="mr-2 inline"/>Educational link / video</button></div>{sourceType==="FILE"?<div className="mt-4"><input type="file" accept={ALLOWED_EXTENSIONS.map(x=>"."+x).join(",")} onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full rounded-xl border bg-white p-3"/>{file&&<p className="mt-1 text-xs text-slate-500">{file.name} · {formatSize(file.size)} · Maximum 15 MB</p>}<p className="mt-2 text-xs text-slate-500">PDF, Word, Excel, PowerPoint, text, JPG and PNG. Executable/dangerous files are blocked.</p></div>:<div className="mt-4"><input value={externalUrl} onChange={e=>setExternalUrl(e.target.value)} className="w-full rounded-xl border bg-white p-3" placeholder="https://www.youtube.com/…"/><p className="mt-2 text-xs text-slate-500">Only HTTPS links are accepted.</p></div>}</div></div>
 <div className="mt-6 flex justify-end gap-2"><button onClick={()=>setShowUpload(false)} className="rounded-xl border px-4 py-3 font-bold">Cancel</button><button disabled={busy||!title.trim()||(sourceType==="FILE"?!file:!externalUrl.trim())} onClick={()=>void save()} className="rounded-xl bg-[#061229] px-5 py-3 font-bold text-white disabled:opacity-50">{busy?"Saving…":"Save resource"}</button></div></div></div>}
 </main>;
}