import { Loader2, Plus, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useSchoolAuth } from "@/contexts/SupabaseAuthContext";
import { getSupabase } from "@/lib/supabase";

type Row = Record<string, unknown>;
const text = (value: unknown, fallback = "") => value === null || value === undefined ? fallback : String(value);
const inputClass = "w-full rounded-xl border border-[var(--ink)]/15 bg-white px-3 py-2.5 text-sm outline-none ring-[var(--accent)] focus:ring-2";

export default function TeacherAssignmentsDirectory() {
  const { profile } = useSchoolAuth(); const [teachers, setTeachers] = useState<Row[]>([]); const [classes, setClasses] = useState<Row[]>([]); const [subjects, setSubjects] = useState<Row[]>([]); const [assignments, setAssignments] = useState<Row[]>([]); const [teacherId, setTeacherId] = useState(""); const [classId, setClassId] = useState(""); const [subject, setSubject] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const isAdmin = ["SUPER_ADMIN", "ADMIN"].includes(profile?.role || "");
  const refresh = useCallback(async () => { try { const client = getSupabase(); const [teacherResult, classResult, subjectResult, assignmentResult] = await Promise.all([client.from("profiles").select("id,display_name,email,role").in("role", ["teacher", "staff"]).eq("is_disabled", false).order("display_name"), client.from("classes").select("id,name,level,grade").order("name"), client.from("subjects").select("id,name,level").order("name"), client.from("teacher_assignments").select("id,teacher_id,class_id,subject,created_at").order("created_at", { ascending: false })]); const errors = [teacherResult.error, classResult.error, subjectResult.error, assignmentResult.error].filter(Boolean); if (errors.length) throw errors[0]; setTeachers((teacherResult.data ?? []) as unknown as Row[]); setClasses((classResult.data ?? []) as unknown as Row[]); setSubjects((subjectResult.data ?? []) as unknown as Row[]); setAssignments((assignmentResult.data ?? []) as unknown as Row[]); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Teacher assignments could not be loaded."); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!isAdmin) return; setBusy(true); setMessage(null); try { const { error } = await getSupabase().from("teacher_assignments").insert({ teacher_id: teacherId, class_id: classId, subject }); if (error) throw error; setTeacherId(""); setClassId(""); setSubject(""); setMessage("Teacher assignment saved and will govern class and subject access."); await refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The teacher assignment could not be saved."); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!isAdmin || !window.confirm("Remove this teacher assignment?")) return; setBusy(true); try { const { error } = await getSupabase().from("teacher_assignments").delete().eq("id", id); if (error) throw error; setMessage("Teacher assignment removed."); await refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "The assignment could not be removed."); } finally { setBusy(false); } };
  const teacherName = (id: string) => text(teachers.find(row => text(row.id) === id)?.display_name, id);
  const className = (id: string) => { const row = classes.find(item => text(item.id) === id); return row ? `${text(row.name)} (${text(row.grade)})` : id; };
  return <section className="menwe-card rounded-[1.75rem] p-5 sm:p-7"><h2 className="font-serif text-2xl font-semibold tracking-tight">Teacher assignments</h2><p className="mt-2 text-sm leading-6 text-[var(--ink)]/60">Assignments are the canonical class-and-subject authorization source. A teacher is not granted another subject merely by sharing the same class.</p>{isAdmin && <form onSubmit={create} className="mt-6 grid gap-3 lg:grid-cols-4"><select required value={teacherId} onChange={event => setTeacherId(event.target.value)} className={inputClass}><option value="">Select teacher</option>{teachers.map(row => <option key={text(row.id)} value={text(row.id)}>{text(row.display_name)}{row.email ? ` — ${text(row.email)}` : ""}</option>)}</select><select required value={classId} onChange={event => setClassId(event.target.value)} className={inputClass}><option value="">Select class</option>{classes.map(row => <option key={text(row.id)} value={text(row.id)}>{text(row.name)} · {text(row.grade)}</option>)}</select><select required value={subject} onChange={event => setSubject(event.target.value)} className={inputClass}><option value="">Select subject</option>{subjects.map(row => <option key={text(row.id)} value={text(row.name)}>{text(row.name)}{row.level ? ` · ${text(row.level)}` : ""}</option>)}</select><button disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-55">{busy ? <Loader2 className="animate-spin" size={16} /> : <Plus size={16} />}Assign</button></form>}<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-[var(--ink)]/10 text-xs font-bold uppercase tracking-[.12em] text-[var(--ink)]/45"><th className="px-3 py-3">Teacher</th><th className="px-3 py-3">Class</th><th className="px-3 py-3">Subject</th>{isAdmin && <th className="px-3 py-3">Action</th>}</tr></thead><tbody>{assignments.map(row => <tr key={text(row.id)} className="border-b border-[var(--ink)]/7 last:border-0"><td className="px-3 py-3">{teacherName(text(row.teacher_id))}</td><td className="px-3 py-3">{className(text(row.class_id))}</td><td className="px-3 py-3">{text(row.subject)}</td>{isAdmin && <td className="px-3 py-3"><button type="button" disabled={busy} onClick={() => void remove(text(row.id))} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-2 py-1 text-xs font-semibold text-red-700"><Trash2 size={13} />Remove</button></td>}</tr>)}{assignments.length === 0 && <tr><td colSpan={isAdmin ? 4 : 3} className="px-3 py-8 text-center text-sm text-[var(--ink)]/55">No teacher assignments have been created.</td></tr>}</tbody></table></div>{message && <p role="status" className="mt-4 rounded-xl bg-[var(--sage)]/16 px-4 py-3 text-sm text-[var(--accent)]">{message}</p>}</section>;
}