import { BookOpen, FlaskConical, HeartHandshake, Medal, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

const stats = [["1961", "Founded & Established"], ["23", "Dedicated Educators"], ["Abogeta", "Sub-County Flagship School"], ["100%", "CBC Curriculum Aligned"]] as const;
const highlights = [[BookOpen, "Academic Rigor", "Strong foundations, purposeful teaching and high expectations."], [ShieldCheck, "Character & Faith", "Discipline, integrity and God-fearing values in everyday school life."], [Medal, "Sports & Co-Curricular", "Football, athletics, music, STEM and leadership pathways."], [FlaskConical, "Modern CBC Integration", "Practical, learner-centred experiences that connect knowledge to life."]] as const;

export default function AboutSection() {
  return <section id="about" className="bg-[#F8F9FA] px-5 py-20 lg:px-10 lg:py-28" aria-labelledby="about-section-title">
    <div className="mx-auto max-w-7xl">
      <div className="grid items-center gap-12 lg:grid-cols-[.92fr_1.08fr] lg:gap-20">
        <div className="relative min-h-[480px] sm:min-h-[540px]">
          <div className="absolute left-0 top-0 h-[390px] w-[72%] overflow-hidden rounded-3xl border-[7px] border-white bg-[#061229] shadow-[0_25px_60px_rgba(6,18,41,.15)]"><img src="/hero-community.svg" alt="Menwe school community illustration" loading="lazy" decoding="async" className="h-full w-full object-cover p-8" /></div>
          <div className="absolute bottom-0 right-0 h-[255px] w-[62%] overflow-hidden rounded-3xl border-[7px] border-white bg-[#D89B28]/10 shadow-[0_25px_60px_rgba(6,18,41,.15)]"><img src="/hero-learning.svg" alt="Menwe learning illustration" loading="lazy" decoding="async" className="h-full w-full object-cover p-8" /></div>
          <div className="absolute left-4 top-[315px] grid grid-cols-2 gap-2 sm:left-7">{stats.map(([value, label]) => <div key={label} className="rounded-2xl border border-white/70 bg-white/85 px-4 py-3 shadow-[0_15px_35px_rgba(6,18,41,.13)] backdrop-blur-xl"><strong className="block text-lg font-extrabold tracking-tight text-[#061229]">{value}</strong><span className="mt-0.5 block max-w-[125px] text-[9px] font-semibold leading-3 text-[#64748B]">{label}</span></div>)}</div>
        </div>
        <div>
          <span className="inline-flex rounded-full border border-[#D89B28]/25 bg-[#D89B28]/10 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.18em] text-[#C58B1E]">• ABOUT MENWE PRIMARY &amp; JSS</span>
          <h2 id="about-section-title" className="mt-5 max-w-3xl font-['Plus_Jakarta_Sans'] text-4xl font-extrabold leading-[1.05] tracking-[-.045em] text-[#061229] sm:text-5xl">Nurturing Character &amp; Empowering Minds in Abogeta Since 1961.</h2>
          <p className="mt-6 max-w-2xl text-sm leading-7 text-[#64748B]">Established in 1961, Menwe Primary &amp; Junior School has grown alongside families in Kionyo and across Abogeta Sub-County. For more than six decades, our community has trusted Menwe to provide a strong academic foundation while nurturing confident, disciplined and compassionate young people.</p>
          <p className="mt-4 max-w-2xl text-sm leading-7 text-[#64748B]">Today, our Primary and Junior Secondary School community combines CBC excellence with faith-based values, talent development and a safe learning environment. We prepare every learner not only to achieve academically, but to contribute positively to family, community and society.</p>
          <div className="mt-8 grid gap-5 sm:grid-cols-2">{highlights.map(([Icon, title, text]) => <div key={title} className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-md"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#D89B28]/10 text-[#C58B1E]"><Icon size={19}/></span><div><h3 className="text-xs font-extrabold text-[#061229]">{title}</h3><p className="mt-1 text-[10px] leading-4 text-[#64748B]">{text}</p></div></div>)}</div>
        </div>
      </div>
      <div className="mt-24 border-t border-slate-200 pt-20">
        <div className="mx-auto max-w-3xl text-center"><span className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#C58B1E]">SCHOOL LEADERSHIP &amp; FACULTY</span><h2 className="mt-3 font-['Plus_Jakarta_Sans'] text-3xl font-extrabold tracking-[-.04em] text-[#061229] sm:text-4xl">Guided by Committed Leadership</h2><p className="mt-3 text-sm leading-6 text-[#64748B]">Our institution thrives under the guidance of experienced administrators and 23 passionate teachers.</p></div>
        <div className="mt-10 grid gap-5 lg:grid-cols-3">
          <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-56 bg-[#061229]"><img src="/hero-community.svg" alt="Menwe school leadership illustration" loading="lazy" decoding="async" className="h-full w-full object-cover p-8"/></div><div className="p-6"><span className="text-[9px] font-extrabold uppercase tracking-[.17em] text-[#C58B1E]">PRINCIPAL / HEADTEACHER</span><h3 className="mt-2 text-base font-extrabold text-[#061229]">Mr. Simon Muriungi Muthemba</h3><p className="mt-3 text-[11px] leading-5 text-[#64748B]">“We build a school where academic ambition is matched by character, confidence and a clear vision for every learner’s future.”</p></div></article>
          <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-56 bg-[#D89B28]/10"><img src="/hero-learning.svg" alt="Menwe deputy leadership illustration" loading="lazy" decoding="async" className="h-full w-full object-cover p-8"/></div><div className="p-6"><span className="text-[9px] font-extrabold uppercase tracking-[.17em] text-[#C58B1E]">DEPUTY PRINCIPAL / DEPUTY HEADTEACHER</span><h3 className="mt-2 text-base font-extrabold text-[#061229]">Mr. Patrick Kimathi</h3><p className="mt-3 text-[11px] leading-5 text-[#64748B]">“Discipline and student welfare create the foundation for character. We work with learners and families to help every child feel supported and responsible.”</p></div></article>
          <article className="flex flex-col justify-between rounded-2xl border border-slate-200 bg-[#061229] p-7 text-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#D89B28]/15 text-[#D89B28]"><UsersRound size={24}/></span><span className="mt-7 block text-[9px] font-extrabold uppercase tracking-[.18em] text-[#D89B28]">TEACHING STAFF</span><h3 className="mt-2 text-2xl font-extrabold tracking-tight">Our 23 Educators</h3><p className="mt-4 text-[11px] leading-5 text-slate-300">A dedicated TSC/BOM teaching team serving learners across Primary and JSS, combining experience, care and a commitment to student success.</p></div><div className="mt-8 flex items-center gap-2 text-[10px] font-bold text-slate-300"><Sparkles size={14} className="text-[#D89B28]"/> Qualified. Caring. Learner-centred.</div></article>
        </div>
      </div>
    </div>
  </section>;
}
