import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, FileText, MessageCircle, Phone, Send, ShieldCheck, UserRound, X } from "lucide-react";
import { supabaseClient } from "@/lib/supabaseClient";

const navy = "#061229";
const gold = "#D89B28";
const WHATSAPP = "254142550882";

export type AdmissionsFormModalProps = { open: boolean; onClose: () => void };

type FormData = {
  learnerFullName: string; dateOfBirth: string; gender: string; entryGrade: string; previousSchool: string;
  guardianName: string; relationship: string; primaryPhone: string; whatsappNumber: string; email: string; physicalAddress: string;
  upiNumber: string; birthCertificateNumber: string; specialNeedsNotes: string;
};

const initial: FormData = { learnerFullName:"", dateOfBirth:"", gender:"", entryGrade:"", previousSchool:"", guardianName:"", relationship:"", primaryPhone:"", whatsappNumber:"", email:"", physicalAddress:"", upiNumber:"", birthCertificateNumber:"", specialNeedsNotes:"" };
const grades = ["PP1","PP2","Grade 1","Grade 2","Grade 3","Grade 4","Grade 5","Grade 6","JSS Grade 7","JSS Grade 8","JSS Grade 9"];
const steps = ["Learner", "Guardian", "Documents", "Review"];

function Field({ label, name, value, onChange, type="text", required=false, placeholder="" }: { label:string; name:string; value:string; onChange:(name:string,value:string)=>void; type?:string; required?:boolean; placeholder?:string }) {
  return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-600">{label}{required && <span className="text-[#D89B28]"> *</span>}</span><input name={name} value={value} onChange={e=>onChange(name,e.target.value)} type={type} required={required} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-[#061229] outline-none transition focus:border-[#D89B28] focus:ring-4 focus:ring-[#D89B28]/10" /></label>;
}

export default function AdmissionsFormModal({ open, onClose }: AdmissionsFormModalProps) {
  const [step,setStep] = useState(0); const [data,setData] = useState<FormData>(initial); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [success,setSuccess] = useState<{ref:string; whatsapp:string}|null>(null);
  const update = (name:string,value:string) => setData(d=>({...d,[name]:value}));
  const canNext = useMemo(()=> step===0 ? !!(data.learnerFullName&&data.dateOfBirth&&data.gender&&data.entryGrade) : step===1 ? !!(data.guardianName&&data.relationship&&data.primaryPhone) : true,[data,step]);
  if(!open) return null;
  const next = () => { setError(""); if(canNext) setStep(s=>Math.min(3,s+1)); else setError("Please complete the required fields before continuing."); };
  const previous = () => { setError(""); setStep(s=>Math.max(0,s-1)); };
  const whatsappText = (reference:string) => `Menwe Primary & Junior School Online Admission Inquiry\nReference: ${reference}\n\nLearner\nName: ${data.learnerFullName}\nDOB: ${data.dateOfBirth}\nGender: ${data.gender}\nEntry: ${data.entryGrade}\nPrevious school: ${data.previousSchool || "Not provided"}\n\nGuardian\nName: ${data.guardianName}\nRelationship: ${data.relationship}\nPhone: ${data.primaryPhone}\nWhatsApp: ${data.whatsappNumber || "Not provided"}\nEmail: ${data.email || "Not provided"}\nLocation: ${data.physicalAddress || "Not provided"}\n\nRecords\nUPI/NEMIS: ${data.upiNumber || "Not provided"}\nBirth certificate: ${data.birthCertificateNumber || "Not provided"}\nSpecial needs/medical notes: ${data.specialNeedsNotes || "None provided"}`;
  const submit = async (e:FormEvent) => { e.preventDefault(); setBusy(true); setError("");
    try {
      if(!supabaseClient) throw new Error("The admissions service is temporarily unavailable. Please use WhatsApp or call 0142550882.");
      const { data: row, error: dbError } = await supabaseClient.from("admissions_inquiries").insert({ learner_full_name:data.learnerFullName, date_of_birth:data.dateOfBirth, gender:data.gender, entry_grade:data.entryGrade, previous_school:data.previousSchool || null, guardian_name:data.guardianName, relationship:data.relationship, primary_phone:data.primaryPhone, whatsapp_number:data.whatsappNumber || null, email:data.email || null, physical_address:data.physicalAddress || null, upi_number:data.upiNumber || null, birth_certificate_number:data.birthCertificateNumber || null, special_needs_notes:data.specialNeedsNotes || null }).select("reference_id").single();
      if(dbError) throw dbError;
      const ref = row.reference_id as string; const text = whatsappText(ref); const url = `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`; setSuccess({ref,whatsapp:url});
    } catch(err) { setError(err instanceof Error ? err.message : "We could not submit the application. Please try again or contact the school office."); } finally { setBusy(false); }
  };
  const close = () => { if(!busy){ onClose(); if(success){setSuccess(null);setStep(0);setData(initial);} } };
  return <div className="fixed inset-0 z-[80] overflow-y-auto bg-[#061229]/75 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-label="Online admissions application">
    <div className="mx-auto my-2 max-w-4xl overflow-hidden rounded-2xl bg-[#F8F9FA] shadow-xl sm:my-8">
      <div className="flex items-center justify-between bg-[#061229] px-5 py-4 text-white sm:px-7"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#D89B28]">Menwe Admissions</p><h2 className="mt-1 font-serif text-xl font-semibold">Online application inquiry</h2></div><button onClick={close} className="rounded-xl p-2 text-white/70 transition hover:bg-white/10 hover:text-white" aria-label="Close"><X size={20}/></button></div>
      {success ? <div className="p-6 sm:p-10"><div className="mx-auto max-w-xl rounded-2xl border border-emerald-100 bg-white p-7 text-center shadow-md"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><CheckCircle2 size={32}/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-[#D89B28]">Inquiry received</p><h3 className="mt-2 font-serif text-3xl font-semibold text-[#061229]">Your application is on record.</h3><p className="mt-3 text-sm leading-6 text-slate-600">Keep your reference number for follow-up with the admissions office.</p><div className="mt-6 rounded-xl bg-[#061229] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-widest text-white/50">Application reference</p><p className="mt-2 font-mono text-2xl font-bold text-[#D89B28]">{success.ref}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><a href={success.whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#D89B28] px-4 py-3 text-sm font-bold text-[#061229]"><MessageCircle size={17}/> Send details on WhatsApp</a><button onClick={close} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-[#061229]">Close application</button></div><p className="mt-6 text-xs leading-5 text-slate-500">Next: the school office will review the inquiry and contact the guardian using the details provided. You may also call 0142550882 or visit the school office.</p></div></div> : <form onSubmit={submit}>
        <div className="border-b border-slate-200 bg-white px-5 py-5 sm:px-7"><div className="grid grid-cols-4 gap-2">{steps.map((label,i)=><div key={label} className="flex items-center gap-2"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold ${i===step?"bg-[#061229] text-white":i<step?"bg-[#D89B28] text-[#061229]":"bg-slate-100 text-slate-400"}`}>{i<step?<CheckCircle2 size={15}/>:i+1}</span><span className={`hidden text-[10px] font-bold uppercase tracking-wider sm:block ${i===step?"text-[#061229]":"text-slate-400"}`}>{label}</span></div>)}</div></div>
        <div className="p-5 sm:p-8">{step===0&&<section><div className="mb-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><UserRound size={21}/></span><h3 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">Tell us about the learner</h3><p className="mt-1 text-sm text-slate-500">Start with the information needed to understand the intended entry point.</p></div><div className="grid gap-5 md:grid-cols-2"><Field label="Full name" name="learnerFullName" value={data.learnerFullName} onChange={update} required placeholder="Learner's full name"/><Field label="Date of birth" name="dateOfBirth" value={data.dateOfBirth} onChange={update} type="date" required/><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-600">Gender *</span><select value={data.gender} onChange={e=>update("gender",e.target.value)} required className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#D89B28]"><option value="">Select gender</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></label><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-600">Entry grade *</span><select value={data.entryGrade} onChange={e=>update("entryGrade",e.target.value)} required className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#D89B28]"><option value="">Select entry grade</option>{grades.map(g=><option key={g}>{g}</option>)}</select></label><div className="md:col-span-2"><Field label="Previous school" name="previousSchool" value={data.previousSchool} onChange={update} placeholder="Current or previous school, if applicable"/></div></div></section>}
        {step===1&&<section><div className="mb-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><Phone size={21}/></span><h3 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">Parent or guardian details</h3><p className="mt-1 text-sm text-slate-500">Give us the best way to reach the person responsible for the learner.</p></div><div className="grid gap-5 md:grid-cols-2"><Field label="Guardian name" name="guardianName" value={data.guardianName} onChange={update} required/><Field label="Relationship" name="relationship" value={data.relationship} onChange={update} required placeholder="Parent, guardian, etc."/><Field label="Primary phone" name="primaryPhone" value={data.primaryPhone} onChange={update} required placeholder="e.g. 07xx xxx xxx"/><Field label="WhatsApp number" name="whatsappNumber" value={data.whatsappNumber} onChange={update} placeholder="If different from primary phone"/><Field label="Email" name="email" value={data.email} onChange={update} type="email"/><Field label="Physical address / village" name="physicalAddress" value={data.physicalAddress} onChange={update} placeholder="Village, Kionyo / Abogeta area"/></div></section>}
        {step===2&&<section><div className="mb-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><FileText size={21}/></span><h3 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">Learner records and support information</h3><p className="mt-1 text-sm text-slate-500">This step captures identifiers and information the admissions team may need before enrollment.</p></div><div className="grid gap-5 md:grid-cols-2"><Field label="NEMIS / UPI number" name="upiNumber" value={data.upiNumber} onChange={update} placeholder="If already assigned"/><Field label="Birth certificate number" name="birthCertificateNumber" value={data.birthCertificateNumber} onChange={update}/><div className="md:col-span-2"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-600">Special needs / medical notes</span><textarea name="specialNeedsNotes" value={data.specialNeedsNotes} onChange={e=>update("specialNeedsNotes",e.target.value)} rows={5} placeholder="Share relevant information that will help the school support the learner. Please do not include unnecessary sensitive details." className="w-full resize-y rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#D89B28] focus:ring-4 focus:ring-[#D89B28]/10"/></label></div></div><div className="mt-5 rounded-xl border border-[#D89B28]/20 bg-[#D89B28]/10 p-4 text-xs leading-5 text-[#061229]"><ShieldCheck className="mb-2" size={18}/>For your protection, this form does not ask you to upload identity documents online. The admissions office can advise which originals or copies are required after review.</div></section>}
        {step===3&&<section><div className="mb-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#061229]/5 text-[#061229]"><ClipboardCheck size={21}/></span><h3 className="mt-4 font-serif text-2xl font-semibold text-[#061229]">Review before sending</h3><p className="mt-1 text-sm text-slate-500">Check the details carefully. Your inquiry will be saved securely and a WhatsApp message will be prepared for the school office.</p></div><div className="grid gap-4 md:grid-cols-2">{[["Learner",`${data.learnerFullName} · ${data.entryGrade} · ${data.gender}`],["Birth date",data.dateOfBirth],["Previous school",data.previousSchool||"Not provided"],["Guardian",`${data.guardianName} · ${data.relationship}`],["Phone",data.primaryPhone],["WhatsApp",data.whatsappNumber||"Not provided"],["Email",data.email||"Not provided"],["Location",data.physicalAddress||"Not provided"],["NEMIS / UPI",data.upiNumber||"Not provided"],["Birth certificate",data.birthCertificateNumber||"Not provided"]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-[#061229] break-words">{value}</p></div>)}<div className="md:col-span-2 rounded-xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Support notes</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{data.specialNeedsNotes||"None provided"}</p></div></div></section>}
        {error&&<div role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
        <div className="mt-8 flex flex-col-reverse justify-between gap-3 border-t border-slate-200 pt-5 sm:flex-row">{step>0?<button type="button" onClick={previous} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-[#061229]"><ArrowLeft size={16}/> Back</button>:<span/>}{step<3?<button type="button" onClick={next} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#061229] px-6 py-3 text-sm font-bold text-white shadow-md transition-all hover:-translate-y-1 hover:shadow-xl">Continue <ArrowRight size={16}/></button>:<button type="submit" disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#D89B28] px-6 py-3 text-sm font-extrabold text-[#061229] shadow-md transition-all hover:-translate-y-1 hover:shadow-xl disabled:cursor-wait disabled:opacity-60">{busy?<><Send size={16} className="animate-pulse"/> Sending…</>:<><Send size={16}/> Submit inquiry</>}</button>}</div></div>
      </form>}
      <div className="flex flex-col gap-2 border-t border-slate-200 bg-white px-5 py-4 text-center text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:text-left"><span>Menwe Primary & Junior School · Kionyo, Abogeta Sub-County, Meru County</span><span className="inline-flex items-center justify-center gap-1.5 font-semibold text-[#061229]"><Phone size={13}/> 0142550882</span></div>
    </div>
  </div>;
}
