import { useEffect, useMemo, useState } from "react";
import { BarChart3, Loader2 } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

type Admission = { status: string; grade_applied: string };
type Attendance = { status: string; date: string };

export default function AdminAnalytics() {
  const [admissions, setAdmissions] = useState<Admission[]>([]);
  const [attendance, setAttendance] = useState<Attendance[]>([]);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; (async () => { try { const db=getSupabase(); const [a,att]=await Promise.all([db.from("admissions").select("status,grade_applied"),db.from("daily_attendance").select("status,date").gte("date",new Date(Date.now()-6*86400000).toISOString().slice(0,10))]); if(a.error)throw a.error;if(att.error)throw att.error;if(active){setAdmissions((a.data??[]) as Admission[]);setAttendance((att.data??[]) as Attendance[]);}} catch(e){if(active)setMessage(e instanceof Error?e.message:"Analytics are temporarily unavailable.");} finally{if(active)setLoading(false);}})(); return()=>{active=false}},[]);
  const admissionCounts=useMemo(()=>({pending:admissions.filter(x=>x.status==="pending").length,approved:admissions.filter(x=>x.status==="approved").length,enrolled:admissions.filter(x=>["enrolled","admitted"].includes(x.status)).length}),[admissions]);
  const grades=useMemo(()=>{const m=new Map<string,number>();admissions.forEach(x=>m.set(x.grade_applied,(m.get(x.grade_applied)??0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,9)},[admissions]);
  const present=attendance.filter(x=>x.status==="Present").length; const absent=attendance.filter(x=>x.status==="Absent").length; const total=present+absent+attendance.filter(x=>x.status==="Late").length; const presentPct=total?Math.round(present/total*100):0; const absentPct=total?Math.round(absent/total*100):0;
  if(loading)return <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 size={16} className="animate-spin"/>Loading analytics…</div></section>;
  return <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><BarChart3 className="text-[#D89B28]"/><div><h2 className="text-2xl font-bold text-[#061229]">School analytics</h2><p className="text-sm text-slate-500">Lightweight operational metrics from live Supabase records.</p></div></div>{message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}<div className="mt-6 grid grid-cols-1 gap-5 lg:grid-cols-3"><article className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold text-[#061229]">Weekly attendance</h3><div className="mt-5 h-8 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-emerald-500" style={{width:`${presentPct}%`}}/></div><div className="mt-3 flex justify-between text-sm"><span>Present {presentPct}%</span><span>Absent {absentPct}%</span></div><p className="mt-2 text-xs text-slate-500">Late: {total?Math.round(attendance.filter(x=>x.status==="Late").length/total*100):0}%</p></article><article className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold text-[#061229]">Admissions pipeline</h3><div className="mt-5 space-y-3">{[["Pending",admissionCounts.pending],["Approved",admissionCounts.approved],["Enrolled",admissionCounts.enrolled]].map(([label,value])=><div key={String(label)}><div className="mb-1 flex justify-between text-xs font-bold"><span>{label}</span><span>{String(value)}</span></div><div className="h-3 rounded-full bg-slate-200"><div className="h-3 rounded-full bg-[#D89B28]" style={{width:`${admissions.length?Math.max(4,Number(value)/admissions.length*100):0}%`}}/></div></div>)}</div></article><article className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold text-[#061229]">Grade distribution</h3><div className="mt-4 space-y-2">{grades.length?grades.map(([grade,count])=><div key={grade} className="flex min-h-12 items-center gap-3"><span className="w-20 shrink-0 text-xs font-bold text-slate-600">{grade}</span><div className="h-3 flex-1 rounded-full bg-slate-200"><div className="h-3 rounded-full bg-[#061229]" style={{width:`${Math.max(5,count/(grades[0]?.[1]||1)*100)}%`}}/></div><b className="w-6 text-right text-xs">{count}</b></div>):<p className="text-sm text-slate-500">No admissions data yet.</p>}</div></article></div></section>;
}
