import { useEffect, useState } from "react";
import { Loader2, TrendingUp } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

type Entry = { id:string; term:string; grade_level:string; learning_area:string; strand:string|null; substrand:string|null; sba_type:string; sba_title:string; achievement_code:string|null; teacher_remarks:string|null; competency_scores:Record<string,unknown>|null };
const points:Record<string,number>={EE1:8,EE2:7,ME1:6,ME2:5,AE1:4,AE2:3,BE1:2,BE2:1};
const label:Record<string,string>={EE1:"Exceeding — advanced",EE2:"Exceeding — secure",ME1:"Meeting — secure",ME2:"Meeting — developing",AE1:"Approaching — progressing",AE2:"Approaching — emerging",BE1:"Below — support required",BE2:"Below — intensive support"};
export default function CbcPortfolioView({ upi }:{upi:string}){
 const [rows,setRows]=useState<Entry[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 useEffect(()=>{let active=true;const run=async()=>{setLoading(true);setMessage("");try{const {data,error}=await getSupabase().from("cbc_portfolio_entries").select("id,term,grade_level,learning_area,strand,substrand,sba_type,sba_title,achievement_code,teacher_remarks,competency_scores").eq("learner_upi",upi).order("created_at",{ascending:false});if(error)throw error;if(active)setRows((data??[]) as Entry[]);}catch{if(active)setMessage("The cumulative portfolio is temporarily unavailable.");}finally{if(active)setLoading(false);}};if(upi)void run();else setLoading(false);return()=>{active=false}},[upi]);
 const avg=rows.length?rows.reduce((s,r)=>s+(points[r.achievement_code||""]||0),0)/rows.filter(r=>points[r.achievement_code||""]).length:0;
 if(loading)return <div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin text-[#D89B28]"/></div>;
 return <section className="w-full min-w-0 max-w-full box-border rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#D89B28]">Multi-term SBA portfolio</p><h2 className="mt-1 text-2xl font-bold text-[#061229]">Learning evidence & competencies</h2></div><div className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-slate-50 px-4 text-sm font-bold text-[#061229]"><TrendingUp size={18} className="text-[#D89B28]"/>{avg?`${avg.toFixed(1)}/8 average evidence`:"No scored evidence yet"}</div></div>{message&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">{message}</p>}<div className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-2">{rows.map(r=><article key={r.id} className="w-full min-w-0 max-w-full box-border rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="break-words font-bold text-[#061229]">{r.learning_area}</p><p className="mt-1 break-words text-xs text-slate-500">{r.grade_level} · {r.term}</p></div>{r.achievement_code&&<span className="shrink-0 rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-800">{r.achievement_code} · {points[r.achievement_code]}/8</span>}</div><p className="mt-3 break-words text-sm font-semibold text-slate-700">{r.sba_title}</p>{(r.strand||r.substrand)&&<p className="mt-1 break-words text-xs text-slate-500">{r.strand}{r.strand&&r.substrand?" → ":""}{r.substrand}</p>}{r.teacher_remarks&&<p className="mt-3 break-words text-sm leading-6 text-slate-600">{r.teacher_remarks}</p>}{r.achievement_code&&<p className="mt-3 text-xs text-slate-400">{label[r.achievement_code]||"Achievement evidence"}</p>}</article>)}{!rows.length&&<p className="text-sm text-slate-500">No portfolio evidence has been published for this learner yet.</p>}</div></section>;
}
