import { FormEvent, useState } from "react";
import { Loader2, Send, Sparkles } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

type Message={role:"user"|"assistant";content:string};
export default function ParentAssistant(){
 const [messages,setMessages]=useState<Message[]>([{role:"assistant",content:"Hello. I can help with your linked learner's fees, CBC progress, school announcements and general CBC guidance."}]);
 const [input,setInput]=useState(""); const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user" as const,content:text}];setMessages(next);setInput("");setBusy(true);try{const {data:{session}}=await getSupabase().auth.getSession();if(!session)throw new Error("Please sign in again.");const base=(import.meta.env.VITE_SUPABASE_URL as string|undefined)?.trim();if(!base)throw new Error("Supabase is not configured.");const res=await fetch(`${base}/functions/v1/parent-assistant`,{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({messages:next})});const payload=await res.json().catch(()=>({}));if(!res.ok)throw new Error(payload.error||"Assistant unavailable.");setMessages(v=>[...v,{role:"assistant",content:String(payload.message||"I could not find enough information to answer that.")}]);}catch(err){setMessages(v=>[...v,{role:"assistant",content:err instanceof Error?err.message:"The assistant is temporarily unavailable."}]);}finally{setBusy(false)}};
 return <section className="w-full min-w-0 max-w-full box-border rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-amber-50 text-[#D89B28]"><Sparkles size={20}/></span><div><p className="text-xs font-bold uppercase tracking-wider text-[#D89B28]">Secure family assistant</p><h2 className="text-2xl font-bold text-[#061229]">Ask about your school portal</h2></div></div><div className="mt-5 grid max-h-80 gap-3 overflow-y-auto pr-1">{messages.map((m,i)=><div key={i} className={`max-w-[90%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==="user"?"ml-auto bg-[#061229] text-white":"bg-slate-50 text-slate-700"}`}>{m.content}</div>)}</div><form onSubmit={submit} className="mt-5 flex flex-col gap-3 sm:flex-row"><input aria-label="Ask parent assistant" value={input} onChange={e=>setInput(e.target.value)} className="box-border min-h-12 w-full min-w-0 max-w-full rounded-xl border border-slate-200 px-4" placeholder="e.g. What is my child's latest CBC progress?"/><button disabled={busy||!input.trim()} className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[#D89B28] px-5 font-bold text-[#061229] active:scale-[.98] disabled:opacity-60">{busy?<Loader2 className="animate-spin" size={18}/>:<Send size={18}/>}Ask</button></form><p className="mt-3 text-xs text-slate-400">Only information authorized for your parent account is made available to the assistant.</p></section>;
}
