import { ArrowRight, ArrowUpRight, Check, ChevronDown, Facebook, Instagram, Mail, MapPin, Menu, Phone, ShieldCheck, Sparkles, X, Youtube, BookOpen, HeartHandshake, GraduationCap } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import Footer from "./Footer";
import SchoolFAQAssistant from "./SchoolFAQAssistant";
import { prefetchPublicRoute } from "@/lib/publicNavigation";

const SCHOOL_PHONE = "0142550882";
const SCHOOL_EMAILS = ["Menweprimaryandjunior@gmail.com", "menweprimaryschool94@gmail.com"] as const;
const SCHOOL_PO_BOX = "P.O. Box 19, Kionyo";
const socialChannels = [
  { label: "Facebook", icon: Facebook, href: "#", configured: false },
  { label: "Twitter", icon: X, href: "#", configured: false },
  { label: "Instagram", icon: Instagram, href: "#", configured: false },
] as const;
const links = [["Home", "/"], ["About", "/about"], ["Academics", "/academics"], ["Admissions", "/admissions"], ["News", "/news"], ["Events", "/events"], ["Gallery", "/gallery"], ["Contact", "/contact"]] as const;
const discoverLinks = [["School life", "/school-life"], ["For families", "/families"], ["How it works", "/how-it-works"]] as const;
const legalLinks = [["Terms & conditions", "/terms"], ["Privacy", "/privacy"], ["Cookies", "/cookies"]] as const;
const footerPrinciples = [
  { label: "Learning", title: "A clear path through school", copy: "Keep academics, attendance and everyday school life connected in one experience.", icon: BookOpen },
  { label: "Families", title: "Closer communication", copy: "Make it easier for families to stay informed and connected with the school.", icon: HeartHandshake },
  { label: "Growth", title: "Built around the learner", copy: "A thoughtful digital experience for the people who teach, learn and support children.", icon: GraduationCap },
] as const;

export function SchoolMark({ compact = false, inverted = false }: { compact?: boolean; inverted?: boolean }) {
  return <div className="flex items-center gap-3"><div className="relative grid h-11 w-11 shrink-0 place-items-center rounded-[1rem] bg-[var(--ink)] text-white shadow-[0_10px_24px_rgba(29,43,37,.18)] ring-1 ring-white/20"><div className="absolute inset-[3px] rounded-[.78rem] border border-[var(--gold)]/55" /><span className="relative font-serif text-xl font-bold leading-none">M</span></div>{!compact && <div className="leading-tight"><p className={`font-serif text-[17px] font-semibold tracking-tight ${inverted ? "text-white" : "text-[var(--ink)]"}`}>Menwe</p><p className="mt-0.5 text-[9px] font-bold uppercase tracking-[0.19em] text-[var(--accent)]">Primary & Junior School</p></div>}</div>;
}
const primaryNav = [["About", "/about"], ["Academics", "/academics"], ["Admissions", "/admissions"], ["News", "/news"], ["Events", "/events"]] as const;

function UtilityBar() {
  return <div className="menwe-utility-bar"><div className="mx-auto flex min-h-10 max-w-7xl items-center justify-between gap-4 px-5 py-1.5 lg:px-8"><div className="flex min-w-0 flex-wrap items-center gap-x-5 gap-y-1.5"><span className="hidden items-center gap-1.5 font-bold text-[var(--gold)] sm:inline-flex"><Sparkles size={12}/> Admissions open for 2026</span><a href={`tel:${SCHOOL_PHONE}`} className="menwe-utility-link"><Phone size={13}/> <span>{SCHOOL_PHONE}</span></a><a href={`mailto:${SCHOOL_EMAILS[0]}`} className="menwe-utility-link utility-email"><Mail size={13}/> <span>{SCHOOL_EMAILS[0]}</span></a></div><div className="hidden shrink-0 items-center gap-4 md:flex"><span className="menwe-utility-location"><MapPin size={13}/> {SCHOOL_PO_BOX}</span><div className="flex items-center gap-1.5" aria-label="Social media"><span className="mr-1 text-[10px] font-bold uppercase tracking-[.12em] text-white/35">Follow</span>{socialChannels.map(({label,icon:Icon,href,configured})=>configured ? <a key={label} href={href} aria-label={label} className="menwe-social-icon"><Icon size={13}/></a> : <span key={label} aria-label={`${label} profile coming soon`} title={`${label} profile coming soon`} className="menwe-social-icon opacity-45"><Icon size={13}/></span>)}</div></div></div></div>;
}

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  const [location, setLocation] = useLocation();
  const [open, setOpen] = useState(false);
  const [discoverOpen, setDiscoverOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const go = (to: string) => { setLocation(to); setOpen(false); setDiscoverOpen(false); window.scrollTo({ top: 0, behavior: "auto" }); };
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 18); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); setDiscoverOpen(false); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, []);
  const isActive = (path: string) => location === path || (path !== "/" && location.startsWith(`${path}/`));
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);

  return <div className="min-h-screen bg-[var(--paper)] text-[var(--ink)]">
    <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-full focus:bg-[var(--gold)] focus:px-4 focus:py-2 focus:text-sm focus:font-bold focus:text-[var(--ink)]">Skip to main content</a>
    <header className="sticky top-0 z-50 border-b border-[var(--ink)]/10 bg-[var(--paper)] shadow-[0_8px_28px_rgba(29,43,37,.08)] transition-all duration-300">
      <UtilityBar />
      <div className={`mx-auto flex max-w-7xl items-center justify-between px-5 transition-all duration-300 lg:px-8 ${scrolled ? "h-[68px]" : "h-[76px]"}`}>
        <button onClick={() => go("/")} className="menwe-focus-ring group shrink-0 rounded-2xl text-left" aria-label="Menwe Primary & Junior School home"><SchoolMark /></button>
        <nav className="hidden items-center gap-0.5 lg:flex" aria-label="Public navigation">
          <button onPointerEnter={() => prefetchPublicRoute("/")} onFocus={() => prefetchPublicRoute("/")} onClick={() => go("/")} aria-current={location === "/" ? "page" : undefined} className={`relative rounded-full px-3.5 py-2.5 text-[13px] font-semibold transition-all ${location === "/" ? "bg-white text-[var(--ink)] shadow-sm ring-1 ring-[var(--ink)]/8" : "text-[var(--ink)]/62 hover:bg-white/65 hover:text-[var(--ink)]"}`}>Home{location === "/" && <span className="absolute inset-x-3 bottom-1 h-0.5 rounded-full bg-[var(--gold)]" />}</button>
          {primaryNav.map(([label, path]) => { const active = isActive(path); return <button key={path} onPointerEnter={() => prefetchPublicRoute(path)} onFocus={() => prefetchPublicRoute(path)} onClick={() => go(path)} aria-current={active ? "page" : undefined} className={`relative rounded-full px-3.5 py-2.5 text-[13px] font-semibold transition-all ${active ? "bg-white text-[var(--ink)] shadow-sm ring-1 ring-[var(--ink)]/8" : "text-[var(--ink)]/62 hover:bg-white/65 hover:text-[var(--ink)]"}`}>{label}{active && <span className="absolute inset-x-3 bottom-1 h-0.5 rounded-full bg-[var(--gold)]" />}</button>; })}
          <div className="relative"><button onPointerEnter={() => discoverLinks.forEach(([, path]) => prefetchPublicRoute(path))} onClick={() => setDiscoverOpen(value => !value)} aria-expanded={discoverOpen} aria-haspopup="menu" className={`flex items-center gap-1.5 rounded-full px-3.5 py-2.5 text-[13px] font-semibold transition-all ${discoverOpen ? "bg-white text-[var(--ink)] shadow-sm ring-1 ring-[var(--ink)]/8" : "text-[var(--ink)]/62 hover:bg-white/65 hover:text-[var(--ink)]"}`}>Explore <ChevronDown size={13} className={`transition-transform duration-300 ${discoverOpen ? "rotate-180" : ""}`} /></button>{discoverOpen && <div role="menu" className="absolute right-0 top-[calc(100%+12px)] w-[310px] overflow-hidden rounded-[1.35rem] border border-[var(--ink)]/9 bg-[var(--paper)] p-2 shadow-[0_24px_60px_rgba(29,43,37,.16)]"><div className="px-3 pb-2 pt-2"><p className="text-[9px] font-extrabold uppercase tracking-[.22em] text-[var(--accent)]">Discover Menwe</p><p className="mt-1 text-xs leading-5 text-[var(--ink)]/48">A closer look at the people, culture and journey behind the school.</p></div>{discoverLinks.map(([label, path]) => <button key={path} role="menuitem" onClick={() => go(path)} className="group flex w-full items-center justify-between rounded-xl px-3 py-3 text-left transition hover:bg-white"><span><span className="block text-sm font-bold">{label}</span><span className="mt-0.5 block text-[10px] text-[var(--ink)]/40">Explore this part of Menwe</span></span><ArrowUpRight size={14} className="text-[var(--ink)]/25 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[var(--accent)]" /></button>)}</div>}</div>
          <button onPointerEnter={() => prefetchPublicRoute("/gallery")} onFocus={() => prefetchPublicRoute("/gallery")} onClick={() => go("/gallery")} aria-current={isActive("/gallery") ? "page" : undefined} className={`relative ml-0.5 rounded-full px-3.5 py-2.5 text-[13px] font-semibold transition-all ${isActive("/gallery") ? "bg-white text-[var(--ink)] shadow-sm ring-1 ring-[var(--ink)]/8" : "text-[var(--ink)]/62 hover:bg-white/65 hover:text-[var(--ink)]"}`}>Gallery{isActive("/gallery") && <span className="absolute inset-x-3 bottom-1 h-0.5 rounded-full bg-[var(--gold)]" />}</button>
          <button onPointerEnter={() => prefetchPublicRoute("/contact")} onFocus={() => prefetchPublicRoute("/contact")} onClick={() => go("/contact")} aria-current={isActive("/contact") ? "page" : undefined} className={`relative rounded-full px-3.5 py-2.5 text-[13px] font-semibold transition-all ${isActive("/contact") ? "bg-white text-[var(--ink)] shadow-sm ring-1 ring-[var(--ink)]/8" : "text-[var(--ink)]/62 hover:bg-white/65 hover:text-[var(--ink)]"}`}>Contact{isActive("/contact") && <span className="absolute inset-x-3 bottom-1 h-0.5 rounded-full bg-[var(--gold)]" />}</button>
        </nav>
        <div className="hidden items-center gap-2 lg:flex"><button onClick={() => go("/admissions")} className="group inline-flex items-center gap-1.5 rounded-full bg-[var(--ink)] px-4 py-2.5 text-[12px] font-extrabold text-white shadow-[0_8px_24px_rgba(29,43,37,.14)] transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_12px_30px_rgba(29,43,37,.2)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">Start application <ArrowRight size={14} className="transition-transform group-hover:translate-x-0.5" /></button><button onClick={() => go("/portal/login")} className="menwe-interactive group flex items-center gap-2 rounded-full border border-[var(--ink)]/12 bg-white px-4 py-2.5 text-[12px] font-bold text-[var(--ink)] shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[var(--mist)]"><ShieldCheck size={14} className="text-[var(--accent)]" /></span> Portal <ArrowUpRight size={13} className="opacity-40 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></button></div>
        <button onClick={() => setOpen(value => !value)} className="menwe-focus-ring grid h-11 w-11 place-items-center rounded-2xl border border-[var(--ink)]/12 bg-white shadow-sm lg:hidden" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open}>{open ? <X size={20} /> : <Menu size={20} />}</button>
      </div>
      {open && <div className="absolute inset-x-0 top-full max-h-[calc(100vh-68px)] overflow-y-auto border-b border-[var(--ink)]/10 bg-[var(--paper)] px-5 pb-6 pt-3 shadow-[0_24px_40px_rgba(29,43,37,.12)] lg:hidden"><nav className="mx-auto grid max-w-xl gap-1.5" aria-label="Mobile public navigation">{links.map(([label, path]) => { const active = location === path; return <button key={path} onPointerEnter={() => prefetchPublicRoute(path)} onFocus={() => prefetchPublicRoute(path)} onClick={() => go(path)} aria-current={active ? "page" : undefined} className={`flex items-center justify-between rounded-2xl px-4 py-3.5 text-left text-sm font-bold ${active ? "bg-white shadow-sm ring-1 ring-[var(--ink)]/8" : "hover:bg-white/70"}`}><span>{label}</span>{active && <Check size={17} className="text-[var(--accent)]" />}</button>; })}<div className="my-1 grid grid-cols-3 gap-1.5">{discoverLinks.map(([label, path]) => <button key={path} onClick={() => go(path)} className="rounded-2xl border border-[var(--ink)]/8 bg-white/55 px-3 py-3 text-left transition hover:bg-white"><span className="block text-[10px] font-extrabold uppercase tracking-[.12em] text-[var(--accent)]">Explore</span><span className="mt-1 block text-xs font-bold">{label}</span></button>)}</div><button onPointerEnter={() => prefetchPublicRoute("/admissions")} onFocus={() => prefetchPublicRoute("/admissions")} onClick={() => go("/admissions")} className="mt-1 flex items-center justify-center gap-2 rounded-2xl bg-[var(--ink)] px-4 py-3.5 text-sm font-bold text-white shadow-lg shadow-[var(--ink)]/15"><ArrowRight size={17} /> Start an application</button><button onPointerEnter={() => prefetchPublicRoute("/portal/login")} onFocus={() => prefetchPublicRoute("/portal/login")} onClick={() => go("/portal/login")} className="flex items-center justify-center gap-2 rounded-2xl border border-[var(--ink)]/10 bg-white px-4 py-3.5 text-sm font-bold text-[var(--ink)]"><ShieldCheck size={17} className="text-[var(--accent)]" /> Secure portal login <ArrowUpRight size={15} className="opacity-60" /></button></nav></div>}
    </header>
    <main id="main-content" tabIndex={-1}>{children}</main>
    <Footer />
    <SchoolFAQAssistant />
  </div>;
}
