import { ArrowRight, ArrowUpRight, Check, ChevronRight, Menu, ShieldCheck, Sparkles, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

const links = [["Home", "/"], ["About", "/about"], ["Academics", "/academics"], ["Admissions", "/admissions"], ["News", "/news"], ["Events", "/events"], ["Gallery", "/gallery"], ["Contact", "/contact"]] as const;
const discoverLinks = [["School life", "/school-life"], ["For families", "/families"], ["How it works", "/how-it-works"]] as const;

export function SchoolMark({ compact = false }: { compact?: boolean }) { return <div className="flex items-center gap-3"><div className="relative grid h-11 w-11 shrink-0 place-items-center rounded-[1rem] bg-[var(--ink)] text-white shadow-[0_10px_24px_rgba(29,43,37,.18)] ring-1 ring-white/20"><div className="absolute inset-[3px] rounded-[.78rem] border border-[var(--gold)]/45" /><span className="relative font-serif text-xl font-bold leading-none">M</span></div>{!compact && <div className="leading-tight"><p className="font-serif text-[17px] font-semibold tracking-tight text-[var(--ink)]">Menwe</p><p className="mt-0.5 text-[9px] font-bold uppercase tracking-[0.19em] text-[var(--accent)]">Primary & Junior School</p></div>}</div>; }

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  const [location, setLocation] = useLocation(); const [open, setOpen] = useState(false);
  const go = (to: string) => { setLocation(to); setOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  return <div className="min-h-screen bg-[var(--paper)] text-[var(--ink)]">
    <header className="sticky top-0 z-50 border-b border-[var(--ink)]/10 bg-[var(--paper)]/88 shadow-[0_8px_30px_rgba(29,43,37,.05)] backdrop-blur-2xl">
      <div className="hidden border-b border-[var(--ink)]/[0.06] bg-white/35 lg:block"><div className="mx-auto flex h-8 max-w-7xl items-center justify-between px-8 text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--ink)]/50"><span>Menwe Primary & Junior School</span><span className="flex items-center gap-2"><span className="menwe-live-dot" /> A welcoming place to learn</span></div></div>
      <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={() => go("/")} className="menwe-focus-ring group rounded-2xl text-left" aria-label="Menwe Primary & Junior School home"><SchoolMark /></button>
        <nav className="hidden items-center gap-1 lg:flex" aria-label="Public navigation">{links.map(([label, path]) => { const active = location === path; return <button key={path} onClick={() => go(path)} aria-current={active ? "page" : undefined} className={`relative rounded-full px-3.5 py-2.5 text-[13px] font-semibold transition-all ${active ? "bg-white text-[var(--ink)] shadow-sm ring-1 ring-[var(--ink)]/8" : "text-[var(--ink)]/62 hover:bg-white/65 hover:text-[var(--ink)]"}`}>{label}{active && <span className="absolute inset-x-3 bottom-1 h-0.5 rounded-full bg-[var(--gold)]" />}</button>; })}</nav>
        <div className="hidden items-center gap-2 lg:flex"><button onClick={() => go("/how-it-works")} className="menwe-link-line rounded-full px-3.5 py-2.5 text-[12px] font-bold text-[var(--ink)]/55 transition hover:bg-white hover:text-[var(--ink)]">Discover <ChevronRight size={13} /></button><button onClick={() => go("/portal/login")} className="menwe-interactive group flex items-center gap-2 rounded-full border border-[var(--ink)]/12 bg-white/60 px-4 py-2.5 text-[13px] font-bold text-[var(--ink)] shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"><ShieldCheck size={16} className="text-[var(--accent)]" /> Portal login <ArrowUpRight size={14} className="opacity-45 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></button></div>
        <button onClick={() => setOpen(value => !value)} className="menwe-focus-ring grid h-11 w-11 place-items-center rounded-2xl border border-[var(--ink)]/12 bg-white/70 shadow-sm lg:hidden" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open}>{open ? <X size={20} /> : <Menu size={20} />}</button>
      </div>
      {open && <div className="absolute inset-x-0 top-full border-b border-[var(--ink)]/10 bg-[var(--paper)]/98 px-5 pb-6 pt-3 shadow-[0_24px_40px_rgba(29,43,37,.12)] backdrop-blur-2xl lg:hidden"><nav className="mx-auto grid max-w-xl gap-1.5" aria-label="Mobile public navigation">{[...links, ...discoverLinks].map(([label, path]) => { const active = location === path; return <button key={path} onClick={() => go(path)} aria-current={active ? "page" : undefined} className={`flex items-center justify-between rounded-2xl px-4 py-3.5 text-left text-sm font-bold ${active ? "bg-white shadow-sm ring-1 ring-[var(--ink)]/8" : "hover:bg-white/70"}`}><span>{label}</span>{active && <Check size={17} className="text-[var(--accent)]" />}</button>; })}<button onClick={() => go("/portal/login")} className="mt-2 flex items-center justify-center gap-2 rounded-2xl bg-[var(--ink)] px-4 py-3.5 text-sm font-bold text-white shadow-lg shadow-[var(--ink)]/15"><ShieldCheck size={17} /> Secure portal login <ArrowUpRight size={15} className="opacity-70" /></button></nav></div>}
    </header>
    <main>{children}</main>
    <footer className="relative mt-24 overflow-hidden bg-[var(--ink)] text-white">
      <div className="menwe-aurora menwe-aurora-one opacity-10" /><div className="menwe-aurora menwe-aurora-two opacity-10" />
      <div className="relative mx-auto max-w-[1440px] px-5 pb-8 pt-14 sm:pt-16 lg:px-10 lg:pt-20">
        <div className="relative mb-14 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.045] p-6 backdrop-blur-xl sm:p-8 lg:p-10">
          <div className="pointer-events-none absolute -right-20 -top-28 h-72 w-72 rounded-full border border-[var(--gold)]/15" /><div className="pointer-events-none absolute -right-8 -top-16 h-48 w-48 rounded-full border border-white/8" />
          <div className="relative grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center">
            <div><div className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.22em] text-[var(--gold)]"><span className="menwe-live-dot" /> Stay connected</div><h2 className="mt-3 max-w-3xl font-serif text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">A better school experience begins with a simple connection.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/52">Explore Menwe, learn about admissions, or enter the secure school portal when you have an authorised account.</p></div>
            <div className="flex flex-wrap gap-2 lg:justify-end"><button onClick={() => go("/admissions")} className="menwe-glow-button group inline-flex items-center justify-center gap-2 rounded-full bg-[var(--gold)] px-5 py-3 text-sm font-extrabold text-[var(--ink)] transition hover:-translate-y-0.5">Explore admissions <ArrowRight size={15} className="transition group-hover:translate-x-1" /></button><button onClick={() => go("/contact")} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/12 bg-white/[.07] px-5 py-3 text-sm font-bold text-white transition hover:bg-white/[.12]">Contact school <ArrowUpRight size={15} /></button></div>
          </div>
        </div>
        <div className="grid gap-12 lg:grid-cols-[1.35fr_.72fr_.72fr_.9fr]">
          <div><SchoolMark compact /><p className="mt-6 max-w-md text-sm leading-7 text-white/50">A calm public home for Menwe Primary & Junior School — bringing learning, families and school operations into one thoughtful experience.</p><div className="mt-7 flex flex-wrap gap-2"><span className="menwe-trust-chip"><ShieldCheck size={13} /> Role-aware access</span><span className="menwe-trust-chip"><Sparkles size={13} /> Built for school life</span></div></div>
          <div><p className="text-[9px] font-extrabold uppercase tracking-[.24em] text-[var(--gold)]">School</p><div className="mt-5 grid gap-3">{links.slice(1,6).map(([label,path]) => <button key={path} onClick={() => go(path)} className="menwe-footer-link group flex w-fit items-center gap-2 text-left text-sm">{label}<ArrowUpRight size={12} className="opacity-40 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:opacity-100" /></button>)}</div></div>
          <div><p className="text-[9px] font-extrabold uppercase tracking-[.24em] text-[var(--gold)]">Discover</p><div className="mt-5 grid gap-3">{discoverLinks.map(([label,path]) => <button key={path} onClick={() => go(path)} className="menwe-footer-link group flex w-fit items-center gap-2 text-left text-sm">{label}<ArrowUpRight size={12} className="opacity-40 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:opacity-100" /></button>)}<button onClick={() => go("/gallery")} className="menwe-footer-link group flex w-fit items-center gap-2 text-left text-sm">Gallery <ArrowUpRight size={12} className="opacity-40 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:opacity-100" /></button></div></div>
          <div><p className="text-[9px] font-extrabold uppercase tracking-[.24em] text-[var(--gold)]">For your next step</p><div className="mt-5 space-y-4"><button onClick={() => go("/admissions")} className="group flex w-full items-center justify-between rounded-2xl border border-white/8 bg-white/[.045] p-4 text-left transition hover:-translate-y-0.5 hover:bg-white/[.075]"><span><span className="block text-sm font-bold">Admissions</span><span className="mt-1 block text-xs text-white/38">Begin an application</span></span><ArrowUpRight size={15} className="text-[var(--gold)] transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></button><button onClick={() => go("/portal/login")} className="group flex w-full items-center justify-between rounded-2xl border border-white/8 bg-white/[.045] p-4 text-left transition hover:-translate-y-0.5 hover:bg-white/[.075]"><span><span className="block text-sm font-bold">Secure portal</span><span className="mt-1 block text-xs text-white/38">For authorised users</span></span><ShieldCheck size={15} className="text-[var(--gold)]" /></button></div></div>
        </div>
        <div className="mt-14 grid gap-5 border-t border-white/8 pt-6 text-[10px] font-semibold text-white/32 sm:grid-cols-[1fr_auto] sm:items-center"><div className="flex flex-wrap gap-x-5 gap-y-2"><span>© {new Date().getFullYear()} Menwe Primary & Junior School</span><span>Public information</span><span>Secure school operations</span></div><div className="flex items-center gap-2 text-white/28"><span className="h-1.5 w-1.5 rounded-full bg-[var(--gold)]" /> Built for learning, families & community</div></div>
      </div>
    </footer>
  </div>;
}
