create or replace function public.admin_people_directory(p_tab text, p_page integer default 0, p_page_size integer default 15, p_query text default '', p_grade text default 'ALL', p_admission_status text default 'ALL')
returns table(row_data jsonb, total_count bigint)
language sql stable security definer
set search_path = public, private, auth
as $$
with params as (select greatest(0,p_page) page_no, least(50,greatest(1,p_page_size)) page_size, lower(trim(coalesce(p_query,''))) q, coalesce(nullif(trim(p_grade),''),'ALL') grade_filter, coalesce(nullif(trim(p_admission_status),''),'ALL') status_filter),
learner_base as (select s.id,s.admission_number,s.first_name,s.middle_name,s.last_name,s.birth_certificate_number,s.date_of_birth,s.gender,s.address,s.admission_date,s.status,e.id enrollment_id,e.class_id,e.stream_id,e.enrolled_on,e.status enrollment_status,c.name class_name,c.level class_level,c.code class_code,st.name stream_name,pp.full_name parent_name,pp.phone parent_phone,pp.id parent_id,sp.relationship parent_relationship from public.students s left join lateral (select e.* from public.enrollments e where e.student_id=s.id order by (e.status='ACTIVE') desc,e.enrolled_on desc nulls last,e.created_at desc limit 1) e on true left join public.classes c on c.id=e.class_id left join public.streams st on st.id=e.stream_id left join lateral (select sp.*,p.profile_id from public.student_parents sp join public.parents p on p.id=sp.parent_id where sp.student_id=s.id and sp.is_primary=true limit 1) sp on true left join public.profiles pp on pp.id=sp.profile_id where s.deleted_at is null),
learner_filtered as (select lb.* from learner_base lb cross join params x where (x.q='' or lower(concat_ws(' ',lb.admission_number,lb.first_name,lb.middle_name,lb.last_name,lb.birth_certificate_number,lb.date_of_birth,lb.gender,lb.class_name,lb.class_level,lb.stream_name,lb.admission_date,lb.parent_name,lb.parent_phone,lb.address,lb.status)) like '%'||x.q||'%') and (x.grade_filter='ALL' or coalesce(lb.class_name,lb.class_level,'')=x.grade_filter)),
admission_filtered as (select a.* from public.admission_applications a cross join params x where (x.q='' or lower(concat_ws(' ',a.reference,a.student_first_name,a.student_last_name,a.date_of_birth,a.gender,a.current_school,a.grade_applying_for,a.guardian_name,a.guardian_phone,a.guardian_email,a.guardian_relationship,a.address,a.additional_information,a.status::text)) like '%'||x.q||'%') and (x.status_filter='ALL' or upper(a.status::text)=upper(x.status_filter)) and (x.grade_filter='ALL' or coalesce(a.grade_applying_for,'')=x.grade_filter)),
staff_filtered as (select p.* from public.profiles p cross join params x where lower(p.role::text) in ('teacher','staff','admin','head_of_institution','deputy_hoi','super_admin') and (x.q='' or lower(concat_ws(' ',p.full_name,p.email,p.phone,p.role::text,p.status::text)) like '%'||x.q||'%')),
chosen as ((select lf.id,to_jsonb(lf) data,count(*) over() total from learner_filtered lf cross join params x where lower(p_tab)='learners' and private.is_admin() order by lf.first_name,lf.last_name,lf.id limit (select page_size from params) offset ((select page_no from params)*(select page_size from params))) union all (select af.id,to_jsonb(af) data,count(*) over() total from admission_filtered af cross join params x where lower(p_tab)='admissions' and private.is_admin() order by af.created_at desc,af.id limit (select page_size from params) offset ((select page_no from params)*(select page_size from params))) union all (select sf.id,to_jsonb(sf) data,count(*) over() total from staff_filtered sf cross join params x where lower(p_tab)='staff' and private.is_admin() order by sf.full_name,sf.id limit (select page_size from params) offset ((select page_no from params)*(select page_size from params))))
select data,total from chosen order by id;
$$;
revoke all on function public.admin_people_directory(text,integer,integer,text,text,text) from public,anon;
grant execute on function public.admin_people_directory(text,integer,integer,text,text,text) to authenticated;
